### PR TITLE
chore: fix C lint errors (issue #9072)

### LINKED ISSUE #9072: Fix C lint errors
## C Linting Failures

Linting failures were detected in the automated lint workflow run.

### Workflow Details

-   Run: https://github.com/stdlib-js/stdlib/actions/runs/20251666973
-   Type: C Linting
-   Date: 2025-12-16 00:27:02 UTC

### Error Details

```

lib/node_modules/@stdlib/random/base/mt19937/test/fixtures/c/runner.c:151:46: style: Parameter 'x' can be declared as pointer to const [constParameterPointer]
void ui32_to_f64( double *out, unsigned int *x, unsigned int len ) {
                                             ^
lib/node_modules/@stdlib/random/base/mt19937/test/fixtures/c/runner.c:166:46: style: Parameter 'x' can be declared as pointer to const [constParameterPointer]
void f64_to_ui32( unsigned int *out, double *x, unsigned int len ) {
                                             ^
```

### Pull Request Instructions

-   Please use the following PR title format:
"chore: fix C lint errors (issue #<ISSUE_NUMBER>)".
-   Reference this issue in the "Related Issues" section of the PR body as "resolves #<ISSUE_NUMBER>".

### PR DESCRIPTION
**Pull request by GeoDaoyu**
Resolves #9072.

## Description

> What is the purpose of this pull request?

This pull request:

-   fix C lint errors

## Related Issues

> Does this pull request have any related issues?

This pull request has the following related issues:

-   #9072

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

### AI Assistance

> When authoring the changes proposed in this PR, did you use any kind of AI assistance?

-   [ ] Yes
-   [x] No

If you answered "yes" above, how did you use AI assistance?

-   [ ] Code generation (e.g., when writing an implementation or fixing a bug)
-   [ ] Test/benchmark generation
-   [ ] Documentation (including examples)
-   [ ] Research and understanding

#### Disclosure

> If you answered "yes" to using AI assistance, please provide a short disclosure indicating how you used AI assistance. This helps reviewers determine how much scrutiny to apply when reviewing your contribution. Example disclosures: "This PR was written primarily by Claude Code." or "I consulted ChatGPT to understand the codebase, but the proposed changes were fully authored manually by myself.".

{{TODO: add disclosure if applicable}}

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

### CODE REVIEW

File: lib/node_modules/@stdlib/random/base/mt19937/test/fixtures/c/runner.c [hunk 1]
```diff
@@ -148,7 +148,7 @@ void rand_array_ui32( unsigned int *out, const unsigned int len, const unsigned
 * @param x    input array
 * @param len  array length
 */
-void ui32_to_f64( double *out, unsigned int *x, unsigned int len ) {
+void ui32_to_f64( double *out, const unsigned int *x, unsigned int len ) {
```
Comment (kgryte) [inline lib/node_modules/@stdlib/random/base/mt19937/test/fixtures/c/runner.c]:
```suggestion
void ui32_to_f64( double *out, const unsigned int *x, const unsigned int len ) {
```

File: lib/node_modules/@stdlib/random/base/mt19937/test/fixtures/c/runner.c [hunk 2]
```diff
@@ -163,7 +163,7 @@ void ui32_to_f64( double *out, unsigned int *x, unsigned int len ) {
 * @param x    input array
 * @param len  array length
 */
-void f64_to_ui32( unsigned int *out, double *x, unsigned int len ) {
+void f64_to_ui32( unsigned int *out, const double *x, unsigned int len ) {
```
Comment (kgryte) [inline lib/node_modules/@stdlib/random/base/mt19937/test/fixtures/c/runner.c]:
```suggestion
void f64_to_ui32( unsigned int *out, const double *x, const unsigned int len ) {
```

**Review by kgryte — APPROVED** [review]
LGTM
