### PR TITLE
chore: fix JavaScript lint errors (issue #7744)

### LINKED ISSUE #7744: Fix JavaScript lint errors
## JavaScript Linting Failures

  Linting failures were detected in the automated JavaScript lint workflow run.

  ### Workflow Details

  - Run: https://github.com/stdlib-js/stdlib/actions/runs/16533771422
  - Type: JavaScript Linting
  - Date: 2025-07-26 00:11:53 UTC

  ### Error Details
  ```
  make[1]: Entering directory '/home/runner/work/stdlib/stdlib'

Linting file: lib/node_modules/@stdlib/random/iter/poisson/lib/main.js

Linting file: lib/node_modules/@stdlib/stats/base/dists/normal/stdev/lib/native.js

Linting file: lib/node_modules/@stdlib/strided/napi/unary/lib/main.js

Linting file: lib/node_modules/@stdlib/math/base/special/ahavercos/lib/main.js

Linting file: lib/node_modules/@stdlib/array/base/scatter-filled/lib/main.js

Linting file: lib/node_modules/@stdlib/utils/prepend/lib/prepend_array.js

Linting file: lib/node_modules/@stdlib/math/base/special/erf/lib/polyval_qq.js

Linting file: lib/node_modules/@stdlib/stats/base/dists/laplace/skewness/lib/main.js

Linting file: lib/node_modules/@stdlib/plot/ctor/lib/props/x-max/get.js

/home/runner/work/stdlib/stdlib/lib/node_modules/@stdlib/plot/ctor/lib/props/x-max/get.js
  24:46  warning  Unexpected 'todo' comment: 'TODO: replace with mod when written'                            no-warning-comments
  42:8   error    Using the `new Array()` constructor is not allowed; use an array literal with push instead  stdlib/no-new-array

✖ 2 problems (1 error, 1 warning)

Linting failed.

Linting file: lib/node_modules/@stdlib/slice/base/normalize-multi-slice/lib/index.js

Linting file: lib/node_modules/@stdlib/stats/strided/smax/lib/smax.js

Linting file: lib/node_modules/@stdlib/plot/base/ctor/lib/props/x-label/get.js

Linting file: lib/node_modules/@stdlib/stats/strided/snanmin/lib/ndarray.js

Linting file: lib/node_modules/@stdlib/math/base/special/sici/lib/polyval_cn.js

Linting file: lib/node_modules/@stdlib/stats/base/dists/bradford/median/lib/index.js

Linting file: lib/node_modules/@stdlib/stats/base/dists/binomial/median/lib/main.js

Linting file: lib/node_modules/@stdlib/plot/base/ctor/lib/props/line-style/get.js

Linting file: lib/node_modules/@stdlib/utils/writable-properties-in/lib/index.js

Linting file: lib/node_modules/@stdlib/ndarray/base/every/lib/6d_complex.js

Linting file: lib/node_modules/@stdlib/math/base/special/ceiln/lib/native.js

Linting file: lib/node_modules/@stdlib/namespace/lib/main.js

Linting file: lib/node_modules/@stdlib/stats/base/dists/f/skewness/lib/native.js

Linting file: lib/node_modules/@stdlib/ndarray/base/includes/lib/10d_complex.js

Linting file: lib/node_modules/@stdlib/math/strided/special/lib/index.js
make[1]: *** [/home/runner/work/stdlib/stdlib/tools/make/lib/lint/javascript/eslint.mk:255: eslint-files] Error 1
make[1]: Leaving directory '/home/runner/work/stdlib/stdlib'
make: *** [/home/runner/work/stdlib/stdlib/tools/make/lib/lint/javascript/Makefile:158: lint-javascript-files] Error 2
  ```

  ### Pull Request Instructions

  -   Please use the following PR title format:
  "chore: fix JavaScript lint errors (issue #<ISSUE_NUMBER>)".
  -   Reference this issue in the "Related Issues" section of the PR body as "resolves #<ISSUE_NUMBER>".

### PR DESCRIPTION
**Pull request by Pradyumn-cloud**
• Removed Outdated TODO comment
• Resolved error Using the 'new Array()' constructor is not allowed

Resolves #7744 

## Description

resolving linting error

## Parent Issues
Tracking issue: Resolve JavaScript lint errors #5377 

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

### CODE REVIEW

File: lib/node_modules/@stdlib/plot/ctor/lib/props/x-max/get.js [hunk 1]
```diff
@@ -21,7 +21,7 @@
 // MODULES //
 
 var isNull = require( '@stdlib/assert/is-null' );
-var max = require( './../../utils/max.js' ); // TODO: replace with mod when written
+var max = require( './../../utils/max.js' );
```
Comment (kgryte) [inline lib/node_modules/@stdlib/plot/ctor/lib/props/x-max/get.js]: This TODO is not outdated. Still relevant.

Comment (kgryte) [inline lib/node_modules/@stdlib/plot/ctor/lib/props/x-max/get.js]:
```suggestion
var max = require( './../../utils/max.js' ); // TODO: replace with stdlib package import when added
```

**Review by kgryte — APPROVED** [review]
