### PR TITLE
chore: fix JavaScript lint errors (issue #10000)

### LINKED ISSUE #10000: Fix JavaScript lint errors
## JavaScript Linting Failures

  Linting failures were detected in the automated JavaScript lint workflow run.

  ### Workflow Details

  - Run: https://github.com/stdlib-js/stdlib/actions/runs/21534945468
  - Type: JavaScript Linting
  - Date: 2026-01-31 00:13:47 UTC

  ### Error Details
  ```
  make[1]: Entering directory '/home/runner/work/stdlib/stdlib'

Linting file: lib/node_modules/@stdlib/plot/hist/lib/props/is-defined/get.js

Linting file: lib/node_modules/@stdlib/ndarray/base/some-by/lib/3d_accessors.js

Linting file: lib/node_modules/@stdlib/math/iter/special/trunc2/lib/index.js

Linting file: lib/node_modules/@stdlib/stats/iter/mprod/lib/main.js

Linting file: lib/node_modules/@stdlib/stats/base/dists/exponential/cdf/lib/index.js

Linting file: lib/node_modules/@stdlib/assert/is-boolean/lib/object.js

Linting file: lib/node_modules/@stdlib/stats/array/nanvariancech/lib/index.js

Linting file: lib/node_modules/@stdlib/random/gamma/lib/index.js

Linting file: lib/node_modules/@stdlib/assert/is-uri/lib/index.js

Linting file: lib/node_modules/@stdlib/plot/components/svg/axis/lib/props/auto-render/get.js

Linting file: lib/node_modules/@stdlib/stats/array/nanstdevpn/lib/main.js

Linting file: lib/node_modules/@stdlib/stats/base/dists/poisson/variance/lib/index.js

Linting file: lib/node_modules/@stdlib/utils/pluck/lib/defaults.js

Linting file: lib/node_modules/@stdlib/random/array/hypergeometric/lib/main.js

Linting file: lib/node_modules/@stdlib/_tools/makie/plugins/makie-install-node-addons/lib/main.js

/home/runner/work/stdlib/stdlib/lib/node_modules/@stdlib/_tools/makie/plugins/makie-install-node-addons/lib/main.js
  35:2  error  'proc' is not defined  no-undef
  48:3  error  'proc' is not defined  no-undef
  60:2  error  'proc' is not defined  no-undef
  70:2  error  'proc' is not defined  no-undef

✖ 4 problems (4 errors, 0 warnings)

Linting failed.

Linting file: lib/node_modules/@stdlib/number/ctor/lib/index.js

Linting file: lib/node_modules/@stdlib/math/base/special/gammaincinv/scripts/evalrational.js

Linting file: lib/node_modules/@stdlib/array/base/zeros3d/lib/main.js

Linting file: lib/node_modules/@stdlib/stats/base/snanvariancech/lib/snanvariancech.native.js
make[1]: *** [/home/runner/work/stdlib/stdlib/tools/make/lib/lint/javascript/eslint.mk:261: eslint-files] Error 1
make[1]: Leaving directory '/home/runner/work/stdlib/stdlib'
make: *** [/home/runner/work/stdlib/stdlib/tools/make/lib/lint/javascript/Makefile:158: lint-javascript-files] Error 2
  ```

  ### Pull Request Instructions

  -   Please use the following PR title format:
  "chore: fix JavaScript lint errors (issue #<ISSUE_NUMBER>)".
  -   Reference this issue in the "Related Issues" section of the PR body as "resolves #<ISSUE_NUMBER>".

### PR DESCRIPTION
**Pull request by Sid-V5**
Fixed the `no-undef` ESLint errors in `makie-install-node-addons/lib/main.js` by replacing undefined `proc` references with `process`.

Resolves #10000

## Problem

Four module-scoped callback functions (`onError`, `onFinish`, `stdout`, `stderr`) reference `proc`, but `proc` is only declared as a local variable inside the `plugin()` function. This causes 4 ESLint `no-undef` errors:

```
35:2  error  'proc' is not defined  no-undef
48:3  error  'proc' is not defined  no-undef
60:2  error  'proc' is not defined  no-undef
70:2  error  'proc' is not defined  no-undef
```

## Fix

The callbacks use `proc.exitCode`, `proc.stdout.write()`, and `proc.stderr.write()` these are operations on the **Node.js global `process` object**, not the child process spawned inside `plugin()`. Replaced all 4 occurrences of `proc` with `process` in the module-scoped callbacks:

```diff
 function onError( error ) {
-	proc.exitCode = 1;
+	process.exitCode = 1;

 function onFinish( code ) {
-		proc.exitCode = code;
+		process.exitCode = code;

 function stdout( data ) {
-	proc.stdout.write( data );
+	process.stdout.write( data );

 function stderr( data ) {
-	proc.stderr.write( data );
+	process.stderr.write( data );
```

The local `var proc` inside `plugin()` continues to hold the child process handle from `spawn()` and is unaffected.

- [x] Read, understood, and followed the [contributing guidelines](https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md)

### CODE REVIEW

File: lib/node_modules/@stdlib/_tools/makie/plugins/makie-install-node-addons/lib/main.js [hunk 1]
```diff
@@ -32,7 +32,7 @@ var spawn = require( 'child_process' ).spawn;
 * @param {Error} error - error object
 */
 function onError( error ) {
-	proc.exitCode = 1;
+	process.exitCode = 1;
```
Comment (Planeshifter) [inline lib/node_modules/@stdlib/_tools/makie/plugins/makie-install-node-addons/lib/main.js]: The right fix here is to add the missing import rather than switching to the `process` global.

If you look at every other sibling makie plugin (e.g., `makie-test`, `makie-benchmark`, `makie-examples` -- all 21 of them), they all have this at line 23:

```js
var proc = require( 'process' );
var spawn = require( 'child_process' ).spawn;
```

This file is the only one missing that `require( 'process' )` import. That's the actual root cause of the lint error.

The fix should be to add `var proc = require( 'process' );` before the `spawn` require (line 23) and then revert all four callback changes back to using `proc`. This keeps consistency with every other plugin in this directory and follows the stdlib convention of using `require('process')` rather than relying on the `process` global.

**Review by Planeshifter — CHANGES_REQUESTED** [review]
Thanks for opening a PR!

File: lib/node_modules/@stdlib/_tools/makie/plugins/makie-install-node-addons/lib/main.js [hunk 2]
```diff
@@ -14,12 +14,13 @@
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
-*/
+*/\
```
Comment (Planeshifter) [inline lib/node_modules/@stdlib/_tools/makie/plugins/makie-install-node-addons/lib/main.js]:
```suggestion
*/
```

File: lib/node_modules/@stdlib/_tools/makie/plugins/makie-install-node-addons/lib/main.js [hunk 3]
```diff
@@ -4,7 +4,7 @@
 * Copyright (c) 2018 The Stdlib Authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
-* you may not use this file except in compliance with the License.
+* you may not use this file except in compliance with the License.\
```
Comment (Planeshifter) [inline lib/node_modules/@stdlib/_tools/makie/plugins/makie-install-node-addons/lib/main.js]:
```suggestion
* you may not use this file except in compliance with the License.
```

File: lib/node_modules/@stdlib/_tools/makie/plugins/makie-install-node-addons/lib/main.js [hunk 4]
```diff
@@ -61,7 +62,7 @@ function stdout( data ) {
 }
 
 /**
-* Callback invoked upon receiving data from `stderr`.
+* Callback invoked upon receiving data from `stderr`.\
```
Comment (Planeshifter) [inline lib/node_modules/@stdlib/_tools/makie/plugins/makie-install-node-addons/lib/main.js]:
```suggestion
* Callback invoked upon receiving data from `stderr`.
```

File: lib/node_modules/@stdlib/_tools/makie/plugins/makie-install-node-addons/lib/main.js [hunk 5]
```diff
@@ -83,7 +84,7 @@ function stderr( data ) {
 function plugin( dir, cwd, subpath ) {
 	var opts;
 	var args;
-	var proc;
+	var child;
```
Comment (Planeshifter) [inline lib/node_modules/@stdlib/_tools/makie/plugins/makie-install-node-addons/lib/main.js]:
```suggestion
	var child;
	var opts;
	var args;
```

**Review by Planeshifter — APPROVED** [review]
Looks good after clean-up.

**Review by Planeshifter — CHANGES_REQUESTED** [review]
Landing this PR is blocked until the contributing guidelines acknowledgment is added to the pull request body.

**Review by Planeshifter — APPROVED** [review]
Thanks; let's land your first PR! 🎉
