### PR TITLE
chore: fix JavaScript lint errors (issue #8701)

### LINKED ISSUE #8701: Fix JavaScript lint errors
## JavaScript Linting Failures

  Linting failures were detected in the automated JavaScript lint workflow run.

  ### Workflow Details

  - Run: https://github.com/stdlib-js/stdlib/actions/runs/19841713483
  - Type: JavaScript Linting
  - Date: 2025-12-02 00:15:59 UTC

  ### Error Details
  ```
  make[1]: Entering directory '/home/runner/work/stdlib/stdlib'

Linting file: lib/node_modules/@stdlib/math/strided/special/ssqrt/lib/main.js

Linting file: lib/node_modules/@stdlib/_tools/pkgs/entry-points/lib/resolve.js

/home/runner/work/stdlib/stdlib/lib/node_modules/@stdlib/_tools/pkgs/entry-points/lib/resolve.js
  54:8  error  Using the `new Array()` constructor is not allowed; use an array literal with push instead  stdlib/no-new-array

✖ 1 problem (1 error, 0 warnings)

Linting failed.

Linting file: lib/node_modules/@stdlib/stats/base/dists/binomial/kurtosis/lib/main.js

Linting file: lib/node_modules/@stdlib/strided/base/map-by2/lib/index.js

Linting file: lib/node_modules/@stdlib/constants/time/hours-in-day/lib/index.js

Linting file: lib/node_modules/@stdlib/math/base/special/hypot/lib/index.js

Linting file: lib/node_modules/@stdlib/math/base/special/gammainc/lib/main.js

Linting file: lib/node_modules/@stdlib/math/base/special/powf/lib/polyval_p.js

Linting file: lib/node_modules/@stdlib/random/streams/minstd/lib/debug.js

Linting file: lib/node_modules/@stdlib/math/strided/ops/sub/lib/types.js

Linting file: lib/node_modules/@stdlib/math/base/napi/ternary/lib/index.js

Linting file: lib/node_modules/@stdlib/random/streams/cauchy/lib/validate.js

Linting file: lib/node_modules/@stdlib/ndarray/base/flag/lib/index.js

Linting file: lib/node_modules/@stdlib/assert/is-float64ndarray-like/lib/main.js

Linting file: lib/node_modules/@stdlib/ndarray/base/unary-strided1d/lib/initialize_array_views.js

Linting file: lib/node_modules/@stdlib/stats/strided/dsvariancepn/lib/dsvariancepn.native.js

Linting file: lib/node_modules/@stdlib/array/convert-same/lib/main.js

Linting file: lib/node_modules/@stdlib/math/base/special/polygamma/lib/index.js

Linting file: lib/node_modules/@stdlib/math/base/special/spencef/lib/main.js
make[1]: *** [/home/runner/work/stdlib/stdlib/tools/make/lib/lint/javascript/eslint.mk:261: eslint-files] Error 1
make[1]: Leaving directory '/home/runner/work/stdlib/stdlib'
make: *** [/home/runner/work/stdlib/stdlib/tools/make/lib/lint/javascript/Makefile:158: lint-javascript-files] Error 2
make[1]: Entering directory '/home/runner/work/stdlib/stdlib'

Linting file: lib/node_modules/@stdlib/blas/ext/base/scusum/benchmark/benchmark.ndarray.native.js

Linting file: lib/node_modules/@stdlib/complex/float64/base/mul/benchmark/benchmark.strided.js

Linting file: lib/node_modules/@stdlib/string/num2words/benchmark/benchmark.js

Linting file: lib/node_modules/@stdlib/stats/base/ndarray/dmediansorted/benchmark/benchmark.js

Linting file: lib/node_modules/@stdlib/stats/base/dists/logistic/mgf/benchmark/benchmark.js

Linting file: lib/node_modules/@stdlib/stats/strided/dnanmaxabs/benchmark/benchmark.ndarray.native.js

Linting file: lib/node_modules/@stdlib/blas/base/dcopy/benchmark/benchmark.native.js

Linting file: lib/node_modules/@stdlib/utils/key-by-right/benchmark/benchmark.js

/home/runner/work/stdlib/stdlib/lib/node_modules/@stdlib/utils/key-by-right/benchmark/benchmark.js
  40:8  error  Using the `new Array()` constructor is not allowed; use an array literal with push instead  stdlib/no-new-array
  72:8  error  Using the `new Array()` constructor is not allowed; use an array literal with push instead  stdlib/no-new-array

✖ 2 problems (2 errors, 0 warnings)

Linting failed.

Linting file: lib/node_modules/@stdlib/stats/base/dists/laplace/entropy/benchmark/benchmark.js
make[1]: *** [/home/runner/work/stdlib/stdlib/tools/make/lib/lint/javascript/eslint.mk:261: eslint-files] Error 1
make[1]: Leaving directory '/home/runner/work/stdlib/stdlib'
make: *** [/home/runner/work/stdlib/stdlib/tools/make/lib/lint/javascript/Makefile:158: lint-javascript-files] Error 2
  ```

  ### Pull Request Instructions

  -   Please use the following PR title format:
  "chore: fix JavaScript lint errors (issue #<ISSUE_NUMBER>)".
  -   Reference this issue in the "Related Issues" section of the PR body as "resolves #<ISSUE_NUMBER>".

### PR DESCRIPTION
**Pull request by JavaTypedScript**
---
type: pre_commit_static_analysis_report
description: Results of running static analysis checks when committing changes. report:
  - task: lint_filenames status: passed
  - task: lint_editorconfig status: passed
  - task: lint_markdown status: na
  - task: lint_package_json status: na
  - task: lint_repl_help status: na
  - task: lint_javascript_src status: passed
  - task: lint_javascript_cli status: na
  - task: lint_javascript_examples status: na
  - task: lint_javascript_tests status: na
  - task: lint_javascript_benchmarks status: passed
  - task: lint_python status: na
  - task: lint_r status: na
  - task: lint_c_src status: na
  - task: lint_c_examples status: na
  - task: lint_c_benchmarks status: na
  - task: lint_c_tests_fixtures status: na
  - task: lint_shell status: na
  - task: lint_typescript_declarations status: passed
  - task: lint_typescript_tests status: na
  - task: lint_license_headers status: passed ---

Resolves #8701 .

## Description

> What is the purpose of this pull request?

This pull request:

-   This resolve new Array Constructor linting error by replacing them by nulls of @stdlib/array/base/nulls.

## Related Issues

> Does this pull request have any related issues?

This pull request has the following related issues:

-   resolves #8701 

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

### AI Assistance

> When authoring the changes proposed in this PR, did you use any kind of AI assistance?

-   [ ] Yes
-   [x] No

If you answered "yes" above, how did you use AI assistance?

-   [ ] Code generation (e.g., when writing an implementation or fixing a bug)
-   [ ] Test/benchmark generation
-   [ ] Documentation (including examples)
-   [ ] Research and understanding

#### Disclosure

> If you answered "yes" to using AI assistance, please provide a short disclosure indicating how you used AI assistance. This helps reviewers determine how much scrutiny to apply when reviewing your contribution. Example disclosures: "This PR was written primarily by Claude Code." or "I consulted ChatGPT to understand the codebase, but the proposed changes were fully authored manually by myself.".

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

### CODE REVIEW

File: lib/node_modules/@stdlib/_tools/pkgs/entry-points/lib/resolve.js [hunk 1]
```diff
@@ -50,20 +50,20 @@ function getPkgs( pkgs, dir, clbk ) {
 
 	len = pkgs.length;
 	debug( 'Resolving %d packages...', len );
-
-	out = new Array( len );
+
```
Comment (kgryte) [inline lib/node_modules/@stdlib/_tools/pkgs/entry-points/lib/resolve.js]:
```suggestion

```

**Comment by JavaTypedScript** [comment]
@kgryte hey, i am new here, saw your review, so i wanted to ask, whether I have to change the other 2 files also to be able to merge?

**Comment by kgryte** [comment]
@JavaTypedScript Sorry. I got interrupted in the middle of my review. Will finish shortly, and we'll get this PR in.

**Review by kgryte — APPROVED** [review]
LGTM

**Comment by JavaTypedScript** [comment]
Thanks for this reply, no problem> @JavaTypedScript Sorry. I got interrupted in the middle of my review. Will finish shortly, and we'll get this PR in.
