### PR TITLE
chore: fix JavaScript lint errors

### LINKED ISSUE #6004: Fix JavaScript lint errors
## JavaScript Linting Failures

Linting failures were detected in the automated JavaScript lint workflow run.

### Workflow Details

- Run: https://github.com/stdlib-js/stdlib/actions/runs/13823886807
- Type: JavaScript Linting
- Date: 2025-03-13 00:09:28 UTC

### Error Details
```
/home/runner/work/stdlib/stdlib/lib/node_modules/@stdlib/utils/get-prototype-of/lib/polyfill.js
  45:22  error  Object is used without loading it beforehand via require()  stdlib/require-globals

✖ 1 problem (1 error, 0 warnings)

/home/runner/work/stdlib/stdlib/lib/node_modules/@stdlib/_tools/pkgs/deps/lib/sync.js
  43:1  error  Encountered an error while running code: `Cannot find module '/foo/bar/baz' from '/home/runner/work/stdlib/stdlib'`.Did you mean to include a `// throws <Error>` annotation instead of `// returns [{...}]`?  stdlib/jsdoc-doctest

✖ 1 problem (1 error, 0 warnings)
  1 error and 0 warnings potentially fixable with the `--fix` option.
```

### PR DESCRIPTION
**Pull request by JaySoni1**
## Summary

This pull request fixes JavaScript lint errors identified in the automated JavaScript lint workflow.

### Files Modified
1. `lib/node_modules/@stdlib/utils/get-prototype-of/lib/polyfill.js`
2. `lib/node_modules/@stdlib/_tools/pkgs/deps/lib/sync.js`

---

### 1. `polyfill.js`

- **Problem**: `Object` was used without being loaded via `require()`.
- **Lint Error**:  
  `/home/runner/work/stdlib/stdlib/lib/node_modules/@stdlib/utils/get-prototype-of/lib/polyfill.js`  
  `45:22  error  Object is used without loading it beforehand via require()  stdlib/require-globals`

- **Fix**: Added the required `require` statement for `Object`.

#### Changes Made:

```javascript
// Add this at the top with other requires
var Object = require( '@stdlib/utils/global-object' );

// Lines 45-46 updated as:
if ( obj instanceof Object ) {
    return Object.prototype;
}
```

---

### 2. `sync.js`

- **Problem**: JSDoc example incorrectly showed a return example for a scenario that throws an error.
- **Lint Error**:  
  `/home/runner/work/stdlib/stdlib/lib/node_modules/@stdlib/_tools/pkgs/deps/lib/sync.js`  
  `43:1  error  Encountered an error while running code: Cannot find module '/foo/bar/baz'. Did you mean to include a // throws <Error> annotation instead of // returns [{...}]?  stdlib/jsdoc-doctest`

- **Fix**: Updated the JSDoc example annotation to correctly indicate an error is thrown.

#### Changes Made:

```javascript
/**
* @example
* var pkgs = [ '/foo/bar/baz' ];
* // throws <Error>
* var deps = pkgDeps( pkgs );
*/
```

---

## Checklist ✅

- [x] Read, understood, and followed the [contributing guidelines](https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md)
- [x] Fixed all linting errors mentioned in #6004
- [x] Ran `npm test` locally and all tests passed successfully
- [x] Ensured there are no breaking changes
- [x] PR addresses both identified lint errors in `polyfill.js` and `sync.js`

---

## Related Issues

- Fixes: #6004
- Parent Issue: #5377

---

## Additional Notes

- If there’s any feedback, happy to address it.
- Thank you for reviewing my contribution!

### CODE REVIEW

File: lib/node_modules/@stdlib/_tools/pkgs/deps/lib/sync.js [hunk 1]
```diff
@@ -58,7 +58,7 @@ var debug = logger( 'pkg-deps:sync' );
 * var pkgs = [ '/foo/bar/baz' ];
 *
 * var deps = pkgDeps( pkgs );
-* // returns [{...}]
+* // throws <Error>
```
Comment (kgryte) [inline lib/node_modules/@stdlib/_tools/pkgs/deps/lib/sync.js]:
```suggestion
* // e.g., returns [{...}]
```

The error here is not intended. This example is intended to be illustrative; hence, we can use `e.g.,` to disable doctesting.

File: lib/node_modules/@stdlib/utils/get-prototype-of/lib/polyfill.js [hunk 2]
```diff
@@ -22,6 +22,7 @@
 
 var nativeClass = require( '@stdlib/utils/native-class' );
 var getProto = require( './proto.js' );
+var Object = require( '@stdlib/object/ctor' );
```
Comment (kgryte) [inline lib/node_modules/@stdlib/utils/get-prototype-of/lib/polyfill.js]:
```suggestion
var Object = require( '@stdlib/object/ctor' );
var getProto = require( './proto.js' );
```

Incorrect require order.

**Review by kgryte — APPROVED** [review]

**Comment by kgryte** [comment]
As the CI failure does not stem from changes introduced in this PR and tests pass, I'll go ahead and merge.
