### PR TITLE
chore: fix JavaScript lint errors (issue #11327)

### LINKED ISSUE #11327: Fix JavaScript lint errors
## JavaScript Linting Failures

  Linting failures were detected in the automated JavaScript lint workflow run.

  ### Workflow Details

  - Run: https://github.com/stdlib-js/stdlib/actions/runs/24110587178
  - Type: JavaScript Linting
  - Date: 2026-04-08 00:24:55 UTC

  ### Error Details
  ```
  make[1]: Entering directory '/home/runner/work/stdlib/stdlib'

Linting file: lib/node_modules/@stdlib/ndarray/base/some-by/lib/3d_blocked.js

Linting file: lib/node_modules/@stdlib/repl/lib/settings_alias_args.js

Linting file: lib/node_modules/@stdlib/regexp/extended-length-path/lib/regexp.js

Linting file: lib/node_modules/@stdlib/blas/ext/base/gcusumpw/lib/accessors.js

Linting file: lib/node_modules/@stdlib/constants/float64/sqrt-two/lib/index.js

Linting file: lib/node_modules/@stdlib/random/streams/negative-binomial/lib/validate.js

Linting file: lib/node_modules/@stdlib/stats/base/dists/discrete-uniform/ctor/lib/main.js

Linting file: lib/node_modules/@stdlib/number/float64/base/signbit/lib/index.js

Linting file: lib/node_modules/@stdlib/_tools/static-analysis/js/program-summary/lib/expression2key.js

Linting file: lib/node_modules/@stdlib/stats/strided/dmeankbn/lib/native.js

Linting file: lib/node_modules/@stdlib/array/base/copy/lib/main.js

Linting file: lib/node_modules/@stdlib/stats/base/dists/frechet/entropy/lib/index.js

Linting file: lib/node_modules/@stdlib/namespace/pkg2standalone/scripts/build.js

Linting file: lib/node_modules/@stdlib/math/base/special/gcd/lib/binary_gcd.js

Linting file: lib/node_modules/@stdlib/blas/ext/base/dapxsumpw/lib/dapxsumpw.native.js

Linting file: lib/node_modules/@stdlib/ndarray/base/unary/lib/5d_blocked.js

Linting file: lib/node_modules/@stdlib/stats/base/ztest/one-sample/results/float64/lib/index.js

Linting file: lib/node_modules/@stdlib/error/to-json/lib/type.js

Linting file: lib/node_modules/@stdlib/error/tools/msg2id/lib/index.js

/home/runner/work/stdlib/stdlib/lib/node_modules/@stdlib/error/tools/msg2id/lib/index.js
  21:1  error  Displayed return value is `8t`, but expected `8Z` instead  stdlib/jsdoc-doctest

✖ 1 problem (1 error, 0 warnings)
  1 error and 0 warnings potentially fixable with the `--fix` option.

Linting failed.

Linting file: lib/node_modules/@stdlib/math/strided/special/sramp/lib/ndarray.js

Linting file: lib/node_modules/@stdlib/stats/base/snanvariance/lib/index.js

Linting file: lib/node_modules/@stdlib/ndarray/base/unary-accumulate/lib/4d_blocked_accessors.js

Linting file: lib/node_modules/@stdlib/random/kumaraswamy/lib/index.js

Linting file: lib/node_modules/@stdlib/constants/complex64/lib/index.js

Linting file: lib/node_modules/@stdlib/stats/strided/distances/dminkowski/lib/index.js

Linting file: lib/node_modules/@stdlib/assert/is-equal-uint8array/lib/index.js
make[1]: *** [/home/runner/work/stdlib/stdlib/tools/make/lib/lint/javascript/eslint.mk:261: eslint-files] Error 1
make[1]: Leaving directory '/home/runner/work/stdlib/stdlib'
make: *** [/home/runner/work/stdlib/stdlib/tools/make/lib/lint/javascript/Makefile:158: lint-javascript-files] Error 2
make[1]: Entering directory '/home/runner/work/stdlib/stdlib'

Linting file: lib/node_modules/@stdlib/ndarray/unshift/test/test.assign.js

Linting file: lib/node_modules/@stdlib/array/base/fill-by/test/test.js

Linting file: lib/node_modules/@stdlib/_tools/eslint/rules/jsdoc-no-multiple-blank-lines/test/fixtures/invalid.js

Linting file: lib/node_modules/@stdlib/random/streams/laplace/test/test.validate.js

Linting file: lib/node_modules/@stdlib/math/strided/special/dcbrt-by/test/test.main.js

Linting file: lib/node_modules/@stdlib/fs/read-ndjson/test/test.async.js

Linting file: lib/node_modules/@stdlib/_tools/github/star-repo/test/test.query.js

Linting file: lib/node_modules/@stdlib/datasets/month-names-en/test/test.cli.js

Linting file: lib/node_modules/@stdlib/stats/base/dists/logistic/test/test.js

Linting file: lib/node_modules/@stdlib/simulate/iter/sawtooth-wave/test/test.js

Linting file: lib/node_modules/@stdlib/stats/base/dists/betaprime/quantile/test/test.quantile.js

Linting file: lib/node_modules/@stdlib/random/base/kumaraswamy/test/test.factory.js

Linting file: lib/node_modules/@stdlib/stats/strided/svariancewd/test/test.js

Linting file: lib/node_modules/@stdlib/blas/ext/base/dsum/test/test.dsum.native.js

Linting file: lib/node_modules/@stdlib/math/base/special/roundb/test/test.js

/home/runner/work/stdlib/stdlib/lib/node_modules/@stdlib/math/base/special/roundb/test/test.js
  165:17  error  Use `// returns` after variable declarations or assignment expressions instead of `=>`  stdlib/doctest-marker

✖ 1 problem (1 error, 0 warnings)

Linting failed.

Linting file: lib/node_modules/@stdlib/blas/ext/base/sdsnansum/test/test.sdsnansum.native.js

Linting file: lib/node_modules/@stdlib/_tools/eslint/rules/jsdoc-list-item-content-indent/test/fixtures/invalid.js
make[1]: *** [/home/runner/work/stdlib/stdlib/tools/make/lib/lint/javascript/eslint.mk:261: eslint-files] Error 1
make[1]: Leaving directory '/home/runner/work/stdlib/stdlib'
make: *** [/home/runner/work/stdlib/stdlib/tools/make/lib/lint/javascript/Makefile:158: lint-javascript-files] Error 2
  ```

  ### Pull Request Instructions

  -   Please use the following PR title format:
  "chore: fix JavaScript lint errors (issue #<ISSUE_NUMBER>)".
  -   Reference this issue in the "Related Issues" section of the PR body as "resolves #<ISSUE_NUMBER>".

### PR DESCRIPTION
**Pull request by bhumikasudarshani-cmd**
## Related Issues

resolves #11327

## Description

Fixed two lint errors:
-->Corrected JSDoc return value from `8t` to `8Z` in `@stdlib/error/tools/msg2id`
--> Replaced `=>` with `// returns` marker in `@stdlib/math/base/special/roundb` test file

- [x] Read, understood, and followed the [contributing guidelines](https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md)

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

### CODE REVIEW

**Comment by bhumikasudarshani-cmd** [comment]
I have read and agree to the contributing guidelines.

File: lib/node_modules/@stdlib/error/tools/msg2id/lib/index.js [hunk 1]
```diff
@@ -27,7 +27,7 @@
 * var msg2id = require( '@stdlib/error/tools/msg2id' );
 *
 * var v = msg2id( 'invalid option. `%s` option must be an array. Option: `%s`.' );
-* // returns '8t'
+* // returns 8Z
```
Comment (GeoDaoyu) [inline lib/node_modules/@stdlib/error/tools/msg2id/lib/index.js]: The return value is a string and it should be '8Z'.

**Review by GeoDaoyu — COMMENTED** [review]
The return value is a string.

File: lib/node_modules/@stdlib/error/tools/msg2id/lib/index.js (hunk 1 above)
Comment (bhumikasudarshani-cmd) [reply lib/node_modules/@stdlib/error/tools/msg2id/lib/index.js]: Thanks for the review. I've added '8Z' to correctly reflect that the return value is a string.

**Review by kgryte — APPROVED** [review]

**Review by kgryte — APPROVED** [review]
