### PR TITLE
chore: fix JavaScript lint errors (issue #6417 )

### LINKED ISSUE #6417: Fix JavaScript lint errors
## JavaScript Linting Failures

  Linting failures were detected in the automated JavaScript lint workflow run.

  ### Workflow Details

  - Run: https://github.com/stdlib-js/stdlib/actions/runs/14118981304
  - Type: JavaScript Linting
  - Date: 2025-03-28 00:09:24 UTC

  ### Error Details
  ```
  make[1]: Entering directory '/home/runner/work/stdlib/stdlib'

Linting file: lib/node_modules/@stdlib/stats/base/sstdevtk/lib/index.js

Linting file: lib/node_modules/@stdlib/stats/incr/mmaxabs/lib/main.js

Linting file: lib/node_modules/@stdlib/namespace/lib/namespace/i.js

Linting file: lib/node_modules/@stdlib/assert/is-circular-plain-object/lib/main.js

Linting file: lib/node_modules/@stdlib/blas/ext/base/dnannsumkbn/lib/native.js

Linting file: lib/node_modules/@stdlib/stats/incr/nansumabs2/lib/index.js

Linting file: lib/node_modules/@stdlib/random/base/normal/lib/main.js

Linting file: lib/node_modules/@stdlib/ndarray/maybe-broadcast-array/lib/main.js

Linting file: lib/node_modules/@stdlib/array/base/flatten4d-by/lib/index.js

Linting file: lib/node_modules/@stdlib/stats/base/dnanvariancetk/lib/ndarray.native.js

Linting file: lib/node_modules/@stdlib/stats/base/dists/hypergeometric/skewness/lib/index.js

Linting file: lib/node_modules/@stdlib/_tools/search/pkg-index/lib/index.js

Linting file: lib/node_modules/@stdlib/_tools/bundle/pkg-list/lib/main.js

/home/runner/work/stdlib/stdlib/lib/node_modules/@stdlib/_tools/bundle/pkg-list/lib/main.js
  198:2  warning  Unexpected 'todo' comment: 'TODO: support other bundlers'  no-warning-comments

✖ 1 problem (0 errors, 1 warning)


Linting file: lib/node_modules/@stdlib/math/base/assert/uint32-is-pow2/lib/main.js

Linting file: lib/node_modules/@stdlib/string/tools/grapheme-cluster-break/lib/index.js

Linting file: lib/node_modules/@stdlib/stats/base/cumaxabs/lib/accessors.js

Linting file: lib/node_modules/@stdlib/streams/node/from-strided-array/lib/factory.js

Linting file: lib/node_modules/@stdlib/_tools/github/org-repos/lib/factory.js

Linting file: lib/node_modules/@stdlib/utils/async/if-then/lib/main.js

/home/runner/work/stdlib/stdlib/lib/node_modules/@stdlib/utils/async/if-then/lib/main.js
  122:10  error  Using the `new Array()` constructor is not allowed; use an array literal with push instead  stdlib/no-new-array

✖ 1 problem (1 error, 0 warnings)

Linting failed.

Linting file: lib/node_modules/@stdlib/blas/ext/base/dsnannsumors/lib/ndarray.js

Linting file: lib/node_modules/@stdlib/math/iter/special/digamma/lib/main.js

Linting file: lib/node_modules/@stdlib/complex/float64/base/neg/lib/native.js

Linting file: lib/node_modules/@stdlib/math/iter/tools/map3/lib/index.js
make[1]: *** [/home/runner/work/stdlib/stdlib/tools/make/lib/lint/javascript/eslint.mk:255: eslint-files] Error 1
make[1]: Leaving directory '/home/runner/work/stdlib/stdlib'
make: *** [/home/runner/work/stdlib/stdlib/tools/make/lib/lint/javascript/Makefile:158: lint-javascript-files] Error 2
  ```

  ### Pull Request Instructions

  -   Please use the following PR title format:
  "chore: fix JavaScript lint errors (issue #<ISSUE_NUMBER>)".
  -   Reference this issue in the "Related Issues" section of the PR body as "resolves #<ISSUE_NUMBER>".

### PR DESCRIPTION
**Pull request by t-sibiraj**
Resolves #6417 

## Description

> What is the purpose of this pull request?

This pull request:

-   Fixes a linting error in lib/node_modules/@stdlib/utils/async/if-then/lib/main.js by replacing the usage of new Array() with an array literal ([]) and .push().

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves #6417 

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

### CODE REVIEW

**Comment by kgryte** [comment]
This PR contains various unrelated changes.

File: lib/node_modules/@stdlib/utils/async/if-then/lib/main.js [hunk 1]
```diff
@@ -119,10 +119,9 @@ function ifthenAsync( predicate, x, y, done ) {
 			return done( error );
 		}
 		nargs = arguments.length;
-		args = new Array( nargs );
-		args[ 0 ] = null;
+		args = [ null ];
 		for ( i = 1; i < nargs; i++ ) {
-			args[ i ] = arguments[ i ];
+			args.push(arguments[ i ]);
```
Comment (kgryte) [inline lib/node_modules/@stdlib/utils/async/if-then/lib/main.js]:
```suggestion
			args.push( arguments[ i ] );
```

**Review by kgryte — APPROVED** [review]
LGTM after clean-up.

**Review by kgryte — APPROVED** [review]
