### PR TITLE
docs: fix C lint errors

### LINKED ISSUE #3236: Fix C lint errors in `@stdlib/stats/base/snanmax`
-   File: `lib/node_modules/@stdlib/stats/base/snanmax/examples/c/example.c`
-   Line: 25

### Current Code

```c
float x[] = { 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 0.0/0.0, 0.0/0.0 };
```

### Description

```plaintext
style: Variable 'x' can be declared as const array [constVariable]
```

### LINKED ISSUE #3237: Fix C lint errors in `@stdlib/stats/base/scumax`
-   File: `lib/node_modules/@stdlib/stats/base/scumax/examples/c/example.c`
-   Line: 26

### Code 

```c
float x[] = { 1.0, 2.0, -3.0, 4.0, -5.0, 6.0, 7.0, 8.0 };
```

### Lint Error

```plaintext
style: Variable 'x' can be declared as const array [constVariable]
```

Workflow Run: [2861/job/33171676944](https://github.com/stdlib-js/stdlib/actions/runs/11903872861/job/33171676944)

### LINKED ISSUE #3238: Fix C lint errors in `@stdlib/stats/base/sstdevch`
## C Linting Failures

Linting failures were detected in the automated lint workflow run.

### Workflow Details
-   Run: https://github.com/stdlib-js/stdlib/actions/runs/11848047055/job/33018906858
-   Type: C Linting
-   Date: 2024-11-24 00:00:36 UTC

### Error Details
```
lib/node_modules/@stdlib/stats/base/sstdevch/examples/c/example.c:25:8: style: Variable 'x' can be declared as const array [constVariable]
 float x[] = { 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0 };
```

### PR DESCRIPTION
**Pull request by Neerajpathak07**
Progresses #3235 

## Description

> What is the purpose of this pull request?

This pull request:

-   Resolves C lint errors in `@stdlib/stats/base/snanmax`
-  Resolves C lint errors in `@stdlib/stats/base/scumax`
-  Resolves C lint errors in `@stdlib/stats/base/scumax`

## Related Issues

> Does this pull request have any related issues?

This pull request:

- resolves #3236 
- resolves #3237
- resolves #3238 

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-  [x] Read, understood, and followed the [contributing guidelines](https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md)

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

### CODE REVIEW

File: lib/node_modules/@stdlib/stats/base/scumax/examples/c/example.c [hunk 1]
```diff
@@ -23,7 +23,7 @@
 
 int main( void ) {
 	// Create strided arrays:
-	float x[] = { 1.0, 2.0, -3.0, 4.0, -5.0, 6.0, 7.0, 8.0 };
+	const x[] = { 1.0f, 2.0f, -3.0f, 4.0f, -5.0f, 6.0f, 7.0f, 8.0f };
```
Comment (kgryte) [inline lib/node_modules/@stdlib/stats/base/scumax/examples/c/example.c]:
```suggestion
	const float x[] = { 1.0f, 2.0f, -3.0f, 4.0f, -5.0f, 6.0f, 7.0f, 8.0f };
```

**Review by kgryte — APPROVED** [review]
LGTM. Thanks, @Neerajpathak07.
