### PR TITLE
chore: fix C lint errors (issue #7554)

### LINKED ISSUE #7554: Fix C lint errors
## C Linting Failures

Linting failures were detected in the automated lint workflow run.

### Workflow Details

-   Run: https://github.com/stdlib-js/stdlib/actions/runs/16062770798
-   Type: C Linting
-   Date: 2025-07-04 00:16:50 UTC

### Error Details

```
lib/node_modules/@stdlib/ndarray/base/nonsingleton-dimensions/src/main.c:38:73: style: Parameter 'shape' can be declared as pointer to const [constParameterPointer]
int64_t stdlib_ndarray_nonsingleton_dimensions( int64_t ndims, int64_t *shape ) {
                                                                        ^
```

### Pull Request Instructions

-   Please use the following PR title format:
"chore: fix C lint errors (issue #<ISSUE_NUMBER>)".
-   Reference this issue in the "Related Issues" section of the PR body as "resolves #<ISSUE_NUMBER>".

### PR DESCRIPTION
**Pull request by GeoDaoyu**
Resolves #7554.

## Description

> What is the purpose of this pull request?

This pull request:

-   fix C lint errors

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves #7554 

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

### CODE REVIEW

File: lib/node_modules/@stdlib/ndarray/base/nonsingleton-dimensions/src/main.c [hunk 1]
```diff
@@ -35,7 +35,7 @@
 * int64_t n = stdlib_ndarray_nonsingleton_dimensions( ndims, shape );
 * // returns 1
 */
-int64_t stdlib_ndarray_nonsingleton_dimensions( int64_t ndims, int64_t *shape ) {
+int64_t stdlib_ndarray_nonsingleton_dimensions( int64_t ndims, const int64_t *shape ) {
```
Comment (kgryte) [inline lib/node_modules/@stdlib/ndarray/base/nonsingleton-dimensions/src/main.c]:
```suggestion
int64_t stdlib_ndarray_nonsingleton_dimensions( const int64_t ndims, const int64_t *shape ) {
```

**Review by kgryte — CHANGES_REQUESTED** [review]
@GeoDaoyu Can you also update the header file, as well, to match the updated signature? https://github.com/stdlib-js/stdlib/blob/develop/lib/node_modules/%40stdlib/ndarray/base/nonsingleton-dimensions/include/stdlib/ndarray/base/nonsingleton_dimensions.h

Thanks!

**Comment by GeoDaoyu** [comment]
do you mean this? I updated nonsingleton_dimensions.h

**Review by kgryte — APPROVED** [review]
LGTM. Thanks, @GeoDaoyu.

**Comment by kgryte** [comment]
> do you mean this? I updated nonsingleton_dimensions.h

Yes, I meant the associated header. The signatures for the `src` file and the corresponding forward declaration in the header file should be the same. So if we make a change to one, we need to make a change to the other.

**Comment by GeoDaoyu** [comment]
> > do you mean this? I updated nonsingleton_dimensions.h
> 
> Yes, I meant the associated header. The signatures for the `src` file and the corresponding forward declaration in the header file should be the same. So if we make a change to one, we need to make a change to the other.

OK, I see. Signature should be the same.
