### PR TITLE
chore: fix C lint errors (issue #7626)

### LINKED ISSUE #7626: Fix C lint errors
## C Linting Failures

Linting failures were detected in the automated lint workflow run.

### Workflow Details

-   Run: https://github.com/stdlib-js/stdlib/actions/runs/16231941293
-   Type: C Linting
-   Date: 2025-07-12 00:14:22 UTC

### Error Details

```
lib/node_modules/@stdlib/ndarray/base/minmax-view-buffer-index/src/main.c:50:73: style: Parameter 'shape' can be declared as pointer to const [constParameterPointer]
int8_t stdlib_ndarray_minmax_view_buffer_index( int64_t ndims, int64_t *shape, int64_t *strides, int64_t offset, int64_t *out ) {
                                                                        ^
lib/node_modules/@stdlib/ndarray/base/minmax-view-buffer-index/src/main.c:50:89: style: Parameter 'strides' can be declared as pointer to const [constParameterPointer]
int8_t stdlib_ndarray_minmax_view_buffer_index( int64_t ndims, int64_t *shape, int64_t *strides, int64_t offset, int64_t *out ) {
                                                                                        ^
```

### Pull Request Instructions

-   Please use the following PR title format:
"chore: fix C lint errors (issue #<ISSUE_NUMBER>)".
-   Reference this issue in the "Related Issues" section of the PR body as "resolves #<ISSUE_NUMBER>".

### PR DESCRIPTION
**Pull request by GeoDaoyu**
Resolves #7626.

## Description

> What is the purpose of this pull request?

This pull request:

-   fix C lint errors

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves #7626 

## Questions

> Any questions for reviewers of this pull request?

Should I add const or 
  add // cppcheck-suppress constVariablePointer?

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

### CODE REVIEW

File: lib/node_modules/@stdlib/ndarray/base/minmax-view-buffer-index/include/stdlib/ndarray/base/minmax_view_buffer_index.h [hunk 1]
```diff
@@ -31,7 +31,7 @@ extern "C" {
 /**
 * Computes the minimum and maximum linear indices (in bytes) in an underlying data buffer accessible to an array view.
 */
-int8_t stdlib_ndarray_minmax_view_buffer_index( int64_t ndims, int64_t *shape, int64_t *strides, int64_t offset, int64_t *out );
+int8_t stdlib_ndarray_minmax_view_buffer_index( int64_t ndims, const int64_t *shape, const int64_t *strides, int64_t offset, int64_t *out );
```
Comment (kgryte) [inline lib/node_modules/@stdlib/ndarray/base/minmax-view-buffer-index/include/stdlib/ndarray/base/minmax_view_buffer_index.h]:
```suggestion
int8_t stdlib_ndarray_minmax_view_buffer_index( const int64_t ndims, const int64_t *shape, const int64_t *strides, const int64_t offset, int64_t *out );
```

File: lib/node_modules/@stdlib/ndarray/base/minmax-view-buffer-index/src/main.c [hunk 2]
```diff
@@ -47,7 +47,7 @@
 * int64_t max = out[ 1 ];
 * // returns 99
 */
-int8_t stdlib_ndarray_minmax_view_buffer_index( int64_t ndims, int64_t *shape, int64_t *strides, int64_t offset, int64_t *out ) {
+int8_t stdlib_ndarray_minmax_view_buffer_index( int64_t ndims, const int64_t *shape, const int64_t *strides, int64_t offset, int64_t *out ) {
```
Comment (kgryte) [inline lib/node_modules/@stdlib/ndarray/base/minmax-view-buffer-index/src/main.c]:
```suggestion
int8_t stdlib_ndarray_minmax_view_buffer_index( const int64_t ndims, const int64_t *shape, const int64_t *strides, const int64_t offset, int64_t *out ) {
```

**Review by kgryte — APPROVED** [review]
LGTM
