### PR TITLE
chore: fix JavaScript lint errors

### LINKED ISSUE #7019: Fix JavaScript lint errors
## JavaScript Linting Failures

  Linting failures were detected in the automated JavaScript lint workflow run.

  ### Workflow Details

  - Run: https://github.com/stdlib-js/stdlib/actions/runs/15079445154
  - Type: JavaScript Linting
  - Date: 2025-05-17 00:08:00 UTC

  ### Error Details
  ```
  make[1]: Entering directory '/home/runner/work/stdlib/stdlib'

Linting file: lib/node_modules/@stdlib/constants/float64/fourth-root-eps/lib/index.js

Linting file: lib/node_modules/@stdlib/random/array/laplace/lib/main.js

Linting file: lib/node_modules/@stdlib/stats/base/meanpw/lib/meanpw.js

Linting file: lib/node_modules/@stdlib/math/base/assert/is-prime/lib/index.js

Linting file: lib/node_modules/@stdlib/_tools/eslint/rules/jsdoc-doctest-decimal-point/lib/index.js

Linting file: lib/node_modules/@stdlib/stats/base/snanmskmax/lib/snanmskmax.js

Linting file: lib/node_modules/@stdlib/utils/async/none-by-right/lib/main.js

Linting file: lib/node_modules/@stdlib/math/base/special/erfinv/lib/rational_p5q5.js

Linting file: lib/node_modules/@stdlib/math/strided/special/sinv/lib/ndarray.js

Linting file: lib/node_modules/@stdlib/stats/strided/dmskmin/lib/dmskmin.native.js

Linting file: lib/node_modules/@stdlib/iter/push/lib/main.js

Linting file: lib/node_modules/@stdlib/plot/components/svg/marks/lib/main.js

/home/runner/work/stdlib/stdlib/lib/node_modules/@stdlib/plot/components/svg/marks/lib/main.js
  114:10  error  Using the `new Array()` constructor is not allowed; use an array literal with push instead  stdlib/no-new-array

✖ 1 problem (1 error, 0 warnings)

Linting failed.

Linting file: lib/node_modules/@stdlib/array/base/fliplr2d/lib/main.js

Linting file: lib/node_modules/@stdlib/math/base/special/atanh/lib/index.js

Linting file: lib/node_modules/@stdlib/stats/incr/nanmeanabs/lib/main.js
make[1]: *** [/home/runner/work/stdlib/stdlib/tools/make/lib/lint/javascript/eslint.mk:255: eslint-files] Error 1
make[1]: Leaving directory '/home/runner/work/stdlib/stdlib'
make: *** [/home/runner/work/stdlib/stdlib/tools/make/lib/lint/javascript/Makefile:158: lint-javascript-files] Error 2
  ```

  ### Pull Request Instructions

  -   Please use the following PR title format:
  "chore: fix JavaScript lint errors (issue #<ISSUE_NUMBER>)".
  -   Reference this issue in the "Related Issues" section of the PR body as "resolves #<ISSUE_NUMBER>".

### PR DESCRIPTION
**Pull request by rajanarahul93**
Resolves #7019.

## Description

> What is the purpose of this pull request?

This pull request:

-   fixes JavaScript lint errors by replacing `new Array()` constructor with array literal syntax to comply with the `stdlib/no-new-array` ESLint rule in the svg marks component

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves #7019 

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

**Technical Details:**
- **File changed:** `lib/node_modules/@stdlib/plot/components/svg/marks/lib/main.js`
- **Line 114:** Replaced `args = new Array( arguments.length+1 );` with `args = []; args.length = arguments.length + 1;`
- **ESLint rule:** `stdlib/no-new-array`
- **Functionality:** Maintains identical behavior while following stdlib coding standards
- **Testing:** Verified with `make lint-javascript-files` command

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

### CODE REVIEW

File: lib/node_modules/@stdlib/plot/components/svg/marks/lib/main.js [hunk 1]
```diff
@@ -111,7 +111,8 @@ function Marks( options ) {
 		var args;
 		var i;
 		debug( 'Received a render event. Re-emitting...' );
-		args = new Array( arguments.length+1 );
+		args = [];
+		args.length = arguments.length + 1;
```
Comment (kgryte) [inline lib/node_modules/@stdlib/plot/components/svg/marks/lib/main.js]: This isn't quite the fix we want. You need to refactor to use `#.push`. Explicitly setting the length does exactly what we are trying to avoid. Namely, initializes a sparse array.

**Review by kgryte — APPROVED** [review]

**Comment by kgryte** [comment]
As the CI failure does not appear to stem from changes introduced in this PR, I'll go ahead and merge.
