### PR TITLE
chore: fix JavaScript lint errors (issue #9334)

### LINKED ISSUE #9334: Fix JavaScript lint errors
## JavaScript Linting Failures

  Linting failures were detected in the automated JavaScript lint workflow run.

  ### Workflow Details

  - Run: https://github.com/stdlib-js/stdlib/actions/runs/20474384237
  - Type: JavaScript Linting
  - Date: 2025-12-24 00:18:28 UTC

  ### Error Details
  ```
  make[1]: Entering directory '/home/runner/work/stdlib/stdlib'

Linting file: lib/node_modules/@stdlib/plot/components/svg/axis/lib/props/tick-padding/set.js

Linting file: lib/node_modules/@stdlib/stats/mediansorted/lib/index.js

Linting file: lib/node_modules/@stdlib/array/ones-like/lib/index.js

Linting file: lib/node_modules/@stdlib/math/strided/special/abs2/lib/ndarray.native.js

Linting file: lib/node_modules/@stdlib/blas/base/wasm/sdsdot/lib/binary.js

Linting file: lib/node_modules/@stdlib/datasets/img-locomotion-nude-male/lib/index.js

Linting file: lib/node_modules/@stdlib/_tools/makie/plugins/makie-lint-r/lib/index.js

Linting file: lib/node_modules/@stdlib/stats/strided/dmaxabs/lib/index.js

Linting file: lib/node_modules/@stdlib/stats/incr/covariance/lib/index.js

Linting file: lib/node_modules/@stdlib/_tools/lint/header-filenames/lib/index.js

/home/runner/work/stdlib/stdlib/lib/node_modules/@stdlib/_tools/lint/header-filenames/lib/index.js
  21:1  error  Displayed return value is `[...]`, but expected `[]` instead  stdlib/jsdoc-doctest

✖ 1 problem (1 error, 0 warnings)
  1 error and 0 warnings potentially fixable with the `--fix` option.

Linting failed.

Linting file: lib/node_modules/@stdlib/array/nans-like/lib/index.js

Linting file: lib/node_modules/@stdlib/stats/strided/dnanmax/lib/ndarray.native.js

Linting file: lib/node_modules/@stdlib/stats/base/dists/laplace/logcdf/lib/factory.js

Linting file: lib/node_modules/@stdlib/number/float16/base/to-binary-string/lib/main.js

Linting file: lib/node_modules/@stdlib/stats/base/dists/gamma/kurtosis/lib/main.js

Linting file: lib/node_modules/@stdlib/math/base/special/rising-factorial/lib/main.js

Linting file: lib/node_modules/@stdlib/stats/strided/ztest2/lib/main.js

Linting file: lib/node_modules/@stdlib/stats/strided/smeanpn/lib/ndarray.js

Linting file: lib/node_modules/@stdlib/blas/base/ssymv/lib/main.js

Linting file: lib/node_modules/@stdlib/math/base/special/trunc2/lib/index.js

Linting file: lib/node_modules/@stdlib/stats/base/dists/gumbel/mgf/lib/index.js
make[1]: *** [/home/runner/work/stdlib/stdlib/tools/make/lib/lint/javascript/eslint.mk:261: eslint-files] Error 1
make[1]: Leaving directory '/home/runner/work/stdlib/stdlib'
make: *** [/home/runner/work/stdlib/stdlib/tools/make/lib/lint/javascript/Makefile:158: lint-javascript-files] Error 2
make[1]: Entering directory '/home/runner/work/stdlib/stdlib'

Linting file: lib/node_modules/@stdlib/iter/while-each/examples/index.js

Linting file: lib/node_modules/@stdlib/constants/float32/ninf/examples/index.js

/home/runner/work/stdlib/stdlib/lib/node_modules/@stdlib/constants/float32/ninf/examples/index.js
  22:1  error  Displayed return value is `-infinity`, but expected `-Infinity` instead  stdlib/doctest

✖ 1 problem (1 error, 0 warnings)
  1 error and 0 warnings potentially fixable with the `--fix` option.

Linting failed.

Linting file: lib/node_modules/@stdlib/assert/tools/array-like-function/examples/index.js

/home/runner/work/stdlib/stdlib/lib/node_modules/@stdlib/assert/tools/array-like-function/examples/index.js
  30:8  error  Using the `new Array()` constructor is not allowed; use an array literal with push instead  stdlib/no-new-array
  35:8  error  Using the `new Array()` constructor is not allowed; use an array literal with push instead  stdlib/no-new-array

✖ 2 problems (2 errors, 0 warnings)

Linting failed.

Linting file: lib/node_modules/@stdlib/stats/iter/examples/index.js

Linting file: lib/node_modules/@stdlib/_tools/pkgs/clis/examples/index.js

Linting file: lib/node_modules/@stdlib/math/base/special/cceilf/examples/index.js

Linting file: lib/node_modules/@stdlib/stats/fligner-test/examples/index.js
make[1]: *** [/home/runner/work/stdlib/stdlib/tools/make/lib/lint/javascript/eslint.mk:261: eslint-files] Error 1
make[1]: Leaving directory '/home/runner/work/stdlib/stdlib'
make: *** [/home/runner/work/stdlib/stdlib/tools/make/lib/lint/javascript/Makefile:158: lint-javascript-files] Error 2
make[1]: Entering directory '/home/runner/work/stdlib/stdlib'

Linting file: lib/node_modules/@stdlib/stats/strided/snanmskrange/test/test.js

Linting file: lib/node_modules/@stdlib/assert/is-negative-number-array/test/test.js

Linting file: lib/node_modules/@stdlib/stats/incr/mmse/test/test.js

Linting file: lib/node_modules/@stdlib/array/base/cunone-by/test/test.js

Linting file: lib/node_modules/@stdlib/random/iter/uniform/test/test.js

Linting file: lib/node_modules/@stdlib/_tools/eslint/rules/no-bench-string-concat/test/fixtures/valid.js

Linting file: lib/node_modules/@stdlib/math/strided/special/atan-by/test/test.main.js

/home/runner/work/stdlib/stdlib/lib/node_modules/@stdlib/math/strided/special/atan-by/test/test.main.js
  77:6  error  Using the `new Array()` constructor is not allowed; use an array literal with push instead  stdlib/no-new-array
  85:6  error  Using the `new Array()` constructor is not allowed; use an array literal with push instead  stdlib/no-new-array

✖ 2 problems (2 errors, 0 warnings)

Linting failed.

Linting file: lib/node_modules/@stdlib/blas/ext/base/scusum/test/test.ndarray.js

Linting file: lib/node_modules/@stdlib/stats/base/dists/kumaraswamy/stdev/test/test.native.js

Linting file: lib/node_modules/@stdlib/assert/is-little-endian/test/test.js

Linting file: lib/node_modules/@stdlib/blas/ext/base/ssum/test/test.ssum.js

Linting file: lib/node_modules/@stdlib/constants/complex64/nan/test/test.js
make[1]: *** [/home/runner/work/stdlib/stdlib/tools/make/lib/lint/javascript/eslint.mk:261: eslint-files] Error 1
make[1]: Leaving directory '/home/runner/work/stdlib/stdlib'
make: *** [/home/runner/work/stdlib/stdlib/tools/make/lib/lint/javascript/Makefile:158: lint-javascript-files] Error 2
  ```

  ### Pull Request Instructions

  -   Please use the following PR title format:
  "chore: fix JavaScript lint errors (issue #<ISSUE_NUMBER>)".
  -   Reference this issue in the "Related Issues" section of the PR body as "resolves #<ISSUE_NUMBER>".

### PR DESCRIPTION
**Pull request by DivitJain26**
---
type: pre_commit_static_analysis_report
description: Results of running static analysis checks when committing changes. report:
  - task: lint_filenames status: passed
  - task: lint_editorconfig status: passed
  - task: lint_markdown status: na
  - task: lint_package_json status: na
  - task: lint_repl_help status: na
  - task: lint_javascript_src status: passed
  - task: lint_javascript_cli status: na
  - task: lint_javascript_examples status: passed
  - task: lint_javascript_tests status: passed
  - task: lint_javascript_benchmarks status: na
  - task: lint_python status: na
  - task: lint_r status: na
  - task: lint_c_src status: na
  - task: lint_c_examples status: na
  - task: lint_c_benchmarks status: na
  - task: lint_c_tests_fixtures status: na
  - task: lint_shell status: na
  - task: lint_typescript_declarations status: passed
  - task: lint_typescript_tests status: na
  - task: lint_license_headers status: passed ---

Resolves #9334.

## Description

> What is the purpose of this pull request?

This pull request:

This PR fixes JavaScript linting errors reported by the automated lint workflow.
The changes are limited to mechanical lint fixes and do **not** modify runtime behavior, public APIs, or test logic.

### Summary of fixes
- Replaced disallowed `new Array()` usage with array literals while preserving sparse array semantics
- Corrected doctest output placeholders (`[...]` to `[]`)
- Fixed incorrect doctest literal casing (`-infinity` to `-Infinity`)

## Related Issues

> Does this pull request have any related issues?

This pull request has the following related issues:

- Resolves #9334  
- Progresses #5377

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

### AI Assistance

> When authoring the changes proposed in this PR, did you use any kind of AI assistance?

-   [ ] Yes
-   [x] No

If you answered "yes" above, how did you use AI assistance?

-   [ ] Code generation (e.g., when writing an implementation or fixing a bug)
-   [ ] Test/benchmark generation
-   [ ] Documentation (including examples)
-   [ ] Research and understanding

#### Disclosure

> If you answered "yes" to using AI assistance, please provide a short disclosure indicating how you used AI assistance. This helps reviewers determine how much scrutiny to apply when reviewing your contribution. Example disclosures: "This PR was written primarily by Claude Code." or "I consulted ChatGPT to understand the codebase, but the proposed changes were fully authored manually by myself.".

{{TODO: add disclosure if applicable}}

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

### CODE REVIEW

File: lib/node_modules/@stdlib/assert/tools/array-like-function/examples/index.js [hunk 1]
```diff
@@ -27,12 +27,14 @@ var bool;
 var f;
 var i;
 
-arr1 = new Array( 25 );
+arr1 = [];
+arr1.length = 25;
 for ( i = 0; i < arr1.length; i++ ) {
 	arr1[ i ] = i;
```
Comment (GeoDaoyu) [inline lib/node_modules/@stdlib/assert/tools/array-like-function/examples/index.js]: use an array literal with push instead

**Review by GeoDaoyu — COMMENTED** [review]
use an array literal with push instead

File: lib/node_modules/@stdlib/assert/tools/array-like-function/examples/index.js (hunk 1 above)
Comment (DivitJain26) [reply lib/node_modules/@stdlib/assert/tools/array-like-function/examples/index.js]: Thanks for the suggestion.

File: lib/node_modules/@stdlib/_tools/lint/header-filenames/lib/index.js [hunk 2]
```diff
@@ -39,7 +39,7 @@
 * var lint = require( '@stdlib/_tools/lint/header-filenames' );
 *
 * var errs = lint.sync();
-* // returns [...]
+* // returns []
```
Comment (kgryte) [inline lib/node_modules/@stdlib/_tools/lint/header-filenames/lib/index.js]:
```suggestion
* // e.g., returns [...]
```

**Review by kgryte — APPROVED** [review]
LGTM
