### PR TITLE
chore: fix JavaScript and EditorConfig lint errors (issues #10944, #10943)

### LINKED ISSUE #10944: Fix JavaScript lint errors
## JavaScript Linting Failures

  Linting failures were detected in the automated JavaScript lint workflow run.

  ### Workflow Details

  - Run: https://github.com/stdlib-js/stdlib/actions/runs/23099301419
  - Type: JavaScript Linting
  - Date: 2026-03-15 00:16:35 UTC

  ### Error Details
  ```
  make[1]: Entering directory '/home/runner/work/stdlib/stdlib'

Linting file: lib/node_modules/@stdlib/stats/base/dists/negative-binomial/examples/index.js

Linting file: lib/node_modules/@stdlib/stats/wilcoxon/examples/index.js

/home/runner/work/stdlib/stdlib/lib/node_modules/@stdlib/stats/wilcoxon/examples/index.js
  32:7  error  Using the `new Array()` constructor is not allowed; use an array literal with push instead  stdlib/no-new-array

✖ 1 problem (1 error, 0 warnings)

Linting failed.

Linting file: lib/node_modules/@stdlib/math/strided/special/acos-by/examples/index.js

Linting file: lib/node_modules/@stdlib/stats/strided/dvariancepn/examples/index.js

Linting file: lib/node_modules/@stdlib/math/strided/special/smskabs2/examples/index.js
make[1]: *** [/home/runner/work/stdlib/stdlib/tools/make/lib/lint/javascript/eslint.mk:261: eslint-files] Error 1
make[1]: Leaving directory '/home/runner/work/stdlib/stdlib'
make: *** [/home/runner/work/stdlib/stdlib/tools/make/lib/lint/javascript/Makefile:158: lint-javascript-files] Error 2
  ```

  ### Pull Request Instructions

  -   Please use the following PR title format:
  "chore: fix JavaScript lint errors (issue #<ISSUE_NUMBER>)".
  -   Reference this issue in the "Related Issues" section of the PR body as "resolves #<ISSUE_NUMBER>".

### PR DESCRIPTION
**Pull request by Sumithraju**
Resolves #10944 and #10943.

## Description

> What is the purpose of this pull request?

This pull request fixes lint errors in the wilcoxon examples file:
-   Replace `new Array()` constructor with array literal `[]` and `.push()` method (issue #10944)
-   Fix indentation in comment blocks from spaces to tabs (issue #10943)

## Related Issues

> Does this pull request have any related issues?

This pull request has the following related issues:
-   #10944 (Fix JavaScript lint errors)
-   #10943 (Fix EditorConfig lint errors)

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

### AI Assistance

> When authoring the changes proposed in this PR, did you use any kind of AI assistance?

-   [x] Yes
-   [ ] No

If you answered "yes" above, how did you use AI assistance?

-   [] Code generation (e.g., when writing an implementation or fixing a bug)
-   [ ] Test/benchmark generation
-   [x] Documentation (including examples)
-   [x] Research and understanding

#### Disclosure

> If you answered "yes" to using AI assistance, please provide a short disclosure indicating how you used AI assistance.

This PR was authored with gpt assistance. identified the lint errors, applied the fixes, and created the commit following stdlib guidelines.

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

### CODE REVIEW

File: lib/node_modules/@stdlib/stats/wilcoxon/examples/index.js [hunk 1]
```diff
@@ -29,23 +29,23 @@ var i;
...
+for ( i = 0; i < 100; i++ ) {
+	arr.push( runif() );
 }
 
 // Test whether distribution is symmetric around zero:
 out = wilcoxon( arr );
 console.log( out.print() );
 /* e.g., =>
-    One-Sample Wilcoxon signed rank test
+	One-Sample Wilcoxon signed rank test
```
Comment (kgryte) [inline lib/node_modules/@stdlib/stats/wilcoxon/examples/index.js:41]: I am not sure we actually want this indentation change.

**Review by kgryte — APPROVED** [review]
