### PR TITLE
chore: fix JavaScript lint errors (issue #9965)

### LINKED ISSUE #9965: Fix JavaScript lint errors
## JavaScript Linting Failures

  Linting failures were detected in the automated JavaScript lint workflow run.

  ### Workflow Details

  - Run: https://github.com/stdlib-js/stdlib/actions/runs/21460203200
  - Type: JavaScript Linting
  - Date: 2026-01-29 00:16:02 UTC

  ### Error Details
  ```
  make[1]: Entering directory '/home/runner/work/stdlib/stdlib'

Linting file: lib/node_modules/@stdlib/array/base/flatten-by/lib/assign.js

Linting file: lib/node_modules/@stdlib/blas/ext/base/scusumkbn2/lib/main.js

Linting file: lib/node_modules/@stdlib/namespace/lib/namespace/base/strided/n.js

Linting file: lib/node_modules/@stdlib/plot/ctor/lib/props/is-defined/get.js

Linting file: lib/node_modules/@stdlib/math/base/special/pow/lib/native.js

Linting file: lib/node_modules/@stdlib/assert/is-browser/lib/index.js

Linting file: lib/node_modules/@stdlib/ndarray/base/for-each/lib/4d.js
0
0
0
0
0
0

Linting file: lib/node_modules/@stdlib/stats/base/dists/normal/variance/lib/main.js

Linting file: lib/node_modules/@stdlib/math/iter/special/erf/lib/index.js

Linting file: lib/node_modules/@stdlib/math/base/special/gammaincinv/lib/rational_ak1bk1.js

Linting file: lib/node_modules/@stdlib/nlp/expand-contractions/lib/index.js

/home/runner/work/stdlib/stdlib/lib/node_modules/@stdlib/nlp/expand-contractions/lib/index.js
  21:1  error  Encountered an error while running code: Unexpected identifier 't'  stdlib/jsdoc-doctest

✖ 1 problem (1 error, 0 warnings)

Linting failed.

Linting file: lib/node_modules/@stdlib/math/strided/special/floor/lib/ndarray.js

Linting file: lib/node_modules/@stdlib/lapack/base/dlacpy/lib/dlacpy.js

Linting file: lib/node_modules/@stdlib/repl/presentation/lib/commands/blank.js

/home/runner/work/stdlib/stdlib/lib/node_modules/@stdlib/repl/presentation/lib/commands/blank.js
  55:3  error  Function 'onDrain' should be moved to outer function scope  stdlib/no-unnecessary-nested-functions

✖ 1 problem (1 error, 0 warnings)

Linting failed.

Linting file: lib/node_modules/@stdlib/ndarray/base/unary-reduce-strided1d/lib/increment_offsets.js

Linting file: lib/node_modules/@stdlib/stats/strided/dnanmskmax/lib/native.js

Linting file: lib/node_modules/@stdlib/stats/base/dists/frechet/ctor/lib/main.js

Linting file: lib/node_modules/@stdlib/time/now/lib/detect.js

Linting file: lib/node_modules/@stdlib/blas/base/zswap/lib/index.js
make[1]: *** [/home/runner/work/stdlib/stdlib/tools/make/lib/lint/javascript/eslint.mk:261: eslint-files] Error 1
make[1]: Leaving directory '/home/runner/work/stdlib/stdlib'
make: *** [/home/runner/work/stdlib/stdlib/tools/make/lib/lint/javascript/Makefile:158: lint-javascript-files] Error 2
  ```

  ### Pull Request Instructions

  -   Please use the following PR title format:
  "chore: fix JavaScript lint errors (issue #<ISSUE_NUMBER>)".
  -   Reference this issue in the "Related Issues" section of the PR body as "resolves #<ISSUE_NUMBER>".

### PR DESCRIPTION
**Pull request by SuYaSh-PaThAk04**
Resolves #resolves #9965.

## Description

> What is the purpose of this pull request?

This pull request:

-   refractered the string to pass eslint and refractered the function for unnecesary  nesting

## Related Issues

> Does this pull request have any related issues?

This pull request has the following related issues:

-   resolves #c

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

### AI Assistance

> When authoring the changes proposed in this PR, did you use any kind of AI assistance?

-   [ ] Yes
-   [x] No

If you answered "yes" above, how did you use AI assistance?

-   [ ] Code generation (e.g., when writing an implementation or fixing a bug)
-   [ ] Test/benchmark generation
-   [ ] Documentation (including examples)
-   [ ] Research and understanding

#### Disclosure

> If you answered "yes" to using AI assistance, please provide a short disclosure indicating how you used AI assistance. This helps reviewers determine how much scrutiny to apply when reviewing your contribution. Example disclosures: "This PR was written primarily by Claude Code." or "I consulted ChatGPT to understand the codebase, but the proposed changes were fully authored manually by myself.".

{{TODO: add disclosure if applicable}}

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

### CODE REVIEW

File: lib/node_modules/@stdlib/nlp/expand-contractions/lib/index.js [hunk 1]
```diff
@@ -26,7 +26,7 @@
 * @example
 * var expandContractions = require( '@stdlib/nlp/expand-contractions' );
 *
-* var str = 'I won\'t be able to get y\'all out of this one.';
+* var str = "I won't be able to get y'all out of this one.";
```
Comment (kgryte) [inline lib/node_modules/@stdlib/nlp/expand-contractions/lib/index.js]:
```suggestion
* var str = 'I won\\'t be able to get y\\'all out of this one.';
```

Let's see what happens if we use a double slash.

File: lib/node_modules/@stdlib/repl/presentation/lib/commands/blank.js [hunk 2]
```diff
@@ -46,25 +46,24 @@ function command( pres ) {
 		var str = repeat( pres._opts.newline, pres.height+1 );
 		pres._repl._ostream.write( str );
 		pres._repl.once( 'drain', onDrain );
-
-		/**
-		* Callback invoked upon a `drain` event.
+	}
+	/**
```
Comment (kgryte) [inline lib/node_modules/@stdlib/repl/presentation/lib/commands/blank.js:51]:
```suggestion

	/**
```

**Review by kgryte — DISMISSED** [review]

File: lib/node_modules/@stdlib/nlp/expand-contractions/lib/index.js [hunk 3]
```diff
@@ -26,7 +26,7 @@
 * @example
 * var expandContractions = require( '@stdlib/nlp/expand-contractions' );
 *
-* var str = 'I won\'t be able to get y\'all out of this one.';
+* var str = 'I won\\'t be able to get y\\'all out of this one.';
```
Comment (kgryte) [inline lib/node_modules/@stdlib/nlp/expand-contractions/lib/index.js]:
```suggestion
* var str = 'I won\\\'t be able to get y\\\'all out of this one.';
```

File: lib/node_modules/@stdlib/nlp/expand-contractions/lib/index.js [hunk 4]
```diff
@@ -26,7 +26,7 @@
 * @example
 * var expandContractions = require( '@stdlib/nlp/expand-contractions' );
 *
-* var str = 'I won\'t be able to get y\'all out of this one.';
+* var str = 'I won\\\'t be able to get y\\\'all out of this one.';
```
Comment (kgryte) [inline lib/node_modules/@stdlib/nlp/expand-contractions/lib/index.js]:
```suggestion
* var str = "I won't be able to get y'all out of this one.";
```

**Comment by SuYaSh-PaThAk04** [comment]
@kgryte  can we do something like 
var str = "I'm ready.";
var out = expandContractions( str );
// returns 'I am ready.'

**Review by kgryte — APPROVED** [review]

**Comment by kgryte** [comment]
@SuYaSh-PaThAk04 You were updating the wrong example.

**Comment by kgryte** [comment]
As the CI failure is not due to changes introduced in this PR, I'll go ahead and merge.
