### PR TITLE
fix: change strides parameter to be pointer to const

### LINKED ISSUE #6604: Fix C lint errors
## C Linting Failures

Linting failures were detected in the automated lint workflow run.

### Workflow Details

-   Run: https://github.com/stdlib-js/stdlib/actions/runs/14321937802
-   Type: C Linting
-   Date: 2025-04-08 00:12:23 UTC

### Error Details

```
lib/node_modules/@stdlib/ndarray/base/assert/is-column-major/src/main.c:43:64: style: Parameter 'strides' can be declared as pointer to const [constParameterPointer]
int8_t stdlib_ndarray_is_column_major( int64_t ndims, int64_t *strides ) {
                                                               ^
```

### Pull Request Instructions

-   Please use the following PR title format:
"chore: fix C lint errors (issue #<ISSUE_NUMBER>)".
-   Reference this issue in the "Related Issues" section of the PR body as "resolves #<ISSUE_NUMBER>".

### PR DESCRIPTION
**Pull request by PraveshKunwar**
---
type: pre_commit_static_analysis_report
description: Results of running static analysis checks when committing changes. report:
  - task: lint_filenames status: passed
  - task: lint_editorconfig status: passed
  - task: lint_markdown status: na
  - task: lint_package_json status: na
  - task: lint_repl_help status: na
  - task: lint_javascript_src status: na
  - task: lint_javascript_cli status: na
  - task: lint_javascript_examples status: na
  - task: lint_javascript_tests status: na
  - task: lint_javascript_benchmarks status: na
  - task: lint_python status: na
  - task: lint_r status: na
  - task: lint_c_src status: missing_dependencies
  - task: lint_c_examples status: na
  - task: lint_c_benchmarks status: na
  - task: lint_c_tests_fixtures status: na
  - task: lint_shell status: na
  - task: lint_typescript_declarations status: na
  - task: lint_typescript_tests status: na
  - task: lint_license_headers status: passed ---

Resolves #6604 

## Description

> What is the purpose of this pull request?

This pull request:

-   Changes parameter (strides) to be declared as pointer to const.

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves #6604 

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

### CODE REVIEW

File: lib/node_modules/@stdlib/ndarray/base/assert/is-column-major/src/main.c [hunk 1]
```diff
@@ -40,7 +40,7 @@
 * int8_t b = stdlib_ndarray_is_column_major( ndims, strides );
 * // returns 1
 */
-int8_t stdlib_ndarray_is_column_major( int64_t ndims, int64_t *strides ) {
+int8_t stdlib_ndarray_is_column_major( int64_t ndims, const int64_t *strides ) {
```
Comment (kgryte) [inline lib/node_modules/@stdlib/ndarray/base/assert/is-column-major/src/main.c]:
```suggestion
int8_t stdlib_ndarray_is_column_major( const int64_t ndims, const int64_t *strides ) {
```

**Comment by kgryte** [comment]
@PraveshKunwar Would you also mind updating the corresponding header file in the same package to match the updated signature?

**Comment by PraveshKunwar** [comment]
@kgryte Yep, just fixed it!

File: lib/node_modules/@stdlib/ndarray/base/assert/is-column-major/src/main.c [hunk 2]
```diff
@@ -40,7 +40,7 @@
 * int8_t b = stdlib_ndarray_is_column_major( ndims, strides );
 * // returns 1
 */
-int8_t stdlib_ndarray_is_column_major( int64_t ndims, int64_t *strides ) {
+int8_t stdlib_ndarray_is_column_major(const int64_t ndims, const int64_t *strides ) {
```
Comment (kgryte) [inline lib/node_modules/@stdlib/ndarray/base/assert/is-column-major/src/main.c]:
```suggestion
int8_t stdlib_ndarray_is_column_major( const int64_t ndims, const int64_t *strides ) {
```

**Comment by kgryte** [comment]
> Would you also mind updating the corresponding header file in the same package to match the updated signature?

@PraveshKunwar This still needs to be done. This PR should contain changes to two files: 1) the source file and 2) the associated header file, which can be found in the same package in the `include` directory.

**Comment by PraveshKunwar** [comment]
@kgryte ok, I believe everything should be ok now

**Review by kgryte — APPROVED** [review]
LGTM
