### PR TITLE
chore: fix JavaScript lint errors (issue #7060)

### LINKED ISSUE #7060: Fix JavaScript lint errors
## JavaScript Linting Failures

  Linting failures were detected in the automated JavaScript lint workflow run.

  ### Workflow Details

  - Run: https://github.com/stdlib-js/stdlib/actions/runs/15174953604
  - Type: JavaScript Linting
  - Date: 2025-05-22 00:08:28 UTC

  ### Error Details
  ```
  make[1]: Entering directory '/home/runner/work/stdlib/stdlib'

Linting file: lib/node_modules/@stdlib/strided/base/function-object/lib/index.js

Linting file: lib/node_modules/@stdlib/math/base/special/besselj0/scripts/evalrational.js

/home/runner/work/stdlib/stdlib/lib/node_modules/@stdlib/math/base/special/besselj0/scripts/evalrational.js
  180:53  warning  Unknown word: "pcqc"  @cspell/spellchecker
  184:53  warning  Unknown word: "psqs"  @cspell/spellchecker

✖ 2 problems (0 errors, 2 warnings)


Linting file: lib/node_modules/@stdlib/stats/base/dists/bernoulli/entropy/lib/main.js

Linting file: lib/node_modules/@stdlib/blas/base/idamax/lib/idamax.native.js

Linting file: lib/node_modules/@stdlib/regexp/semver/lib/regexp.js

Linting file: lib/node_modules/@stdlib/blas/base/wasm/zdrot/lib/index.js

Linting file: lib/node_modules/@stdlib/array/base/broadcasted-quaternary5d/lib/index.js

Linting file: lib/node_modules/@stdlib/array/mskput/lib/defaults.js

Linting file: lib/node_modules/@stdlib/ndarray/base/unary-reduce-subarray/lib/offsets.js

Linting file: lib/node_modules/@stdlib/utils/unzip/lib/main.js

/home/runner/work/stdlib/stdlib/lib/node_modules/@stdlib/utils/unzip/lib/main.js
  86:9  error  Using the `new Array()` constructor is not allowed; use an array literal with push instead  stdlib/no-new-array
  91:8  error  Using the `new Array()` constructor is not allowed; use an array literal with push instead  stdlib/no-new-array
  93:9  error  Using the `new Array()` constructor is not allowed; use an array literal with push instead  stdlib/no-new-array

✖ 3 problems (3 errors, 0 warnings)

Linting failed.

Linting file: lib/node_modules/@stdlib/utils/group-in/lib/main.js

Linting file: lib/node_modules/@stdlib/ndarray/base/map/lib/3d_accessors.js

Linting file: lib/node_modules/@stdlib/stats/base/dists/invgamma/pdf/lib/main.js

Linting file: lib/node_modules/@stdlib/slice/base/str2multislice/lib/index.js

Linting file: lib/node_modules/@stdlib/math/iter/tools/map3/lib/main.js

Linting file: lib/node_modules/@stdlib/stats/base/dists/binomial/quantile/lib/factory.js

Linting file: lib/node_modules/@stdlib/ndarray/base/assert/is-single-segment-compatible/lib/main.js

Linting file: lib/node_modules/@stdlib/utils/parallel/lib/node/worker/children.js

Linting file: lib/node_modules/@stdlib/stats/base/svariancewd/lib/ndarray.native.js

Linting file: lib/node_modules/@stdlib/lapack/base/claset/lib/base.js

Linting file: lib/node_modules/@stdlib/array/base/group-entries-by/lib/main.js

Linting file: lib/node_modules/@stdlib/assert/is-typed-array-length/lib/main.js

Linting file: lib/node_modules/@stdlib/random/base/logistic/lib/factory.js

Linting file: lib/node_modules/@stdlib/blas/base/diagonal-type-enum2str/lib/index.js

Linting file: lib/node_modules/@stdlib/ndarray/base/unary-reduce-strided1d/lib/5d_accessors.js

Linting file: lib/node_modules/@stdlib/math/strided/special/dmskrsqrt/lib/ndarray.js

Linting file: lib/node_modules/@stdlib/_tools/lint/license-header-glob/lib/validate.js

Linting file: lib/node_modules/@stdlib/assert/is-negative-zero/lib/main.js
make[1]: *** [/home/runner/work/stdlib/stdlib/tools/make/lib/lint/javascript/eslint.mk:255: eslint-files] Error 1
make[1]: Leaving directory '/home/runner/work/stdlib/stdlib'
make: *** [/home/runner/work/stdlib/stdlib/tools/make/lib/lint/javascript/Makefile:158: lint-javascript-files] Error 2
  ```

  ### Pull Request Instructions

  -   Please use the following PR title format:
  "chore: fix JavaScript lint errors (issue #<ISSUE_NUMBER>)".
  -   Reference this issue in the "Related Issues" section of the PR body as "resolves #<ISSUE_NUMBER>".

### PR DESCRIPTION
**Pull request by udaykakade25**
Resolves #7060 

## Description

> What is the purpose of this pull request?

This pull request:

-   Replaces new Array() with an array literal with push

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves #7060 

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

### CODE REVIEW

File: lib/node_modules/@stdlib/utils/unzip/lib/main.js [hunk 1]
```diff
@@ -83,19 +83,19 @@ function unzip( arr, idx ) {
 		}
 		numVals = idx.length;
 	} else {
-		idx = new Array( numVals );
+		idx = [];
 		for ( i = 0; i < numVals; i++ ) {
-			idx[ i ] = i;
+			idx.push(i);
```
Comment (Planeshifter) [inline lib/node_modules/@stdlib/utils/unzip/lib/main.js]:
```suggestion
			idx.push( i );
```

File: lib/node_modules/@stdlib/utils/unzip/lib/main.js [hunk 2]
```diff
@@ -83,19 +83,19 @@ function unzip( arr, idx ) {
...
 	for ( j = 0; j < numVals; j++ ) {
-		tmp = new Array( len );
+		tmp = [];
 		k = idx[ j ];
 		for ( i = 0; i < len; i++ ) {
-			tmp[ i ] = arr[ i ][ k ];
+			tmp.push(arr[ i ][ k ]);
 		}
-		out[ j ] = tmp;
+		out.push(tmp);
```
Comment (Planeshifter) [inline lib/node_modules/@stdlib/utils/unzip/lib/main.js]:
```suggestion
		out.push( tmp );
```

File: lib/node_modules/@stdlib/utils/unzip/lib/main.js [hunk 3]
```diff
@@ -83,19 +83,19 @@ function unzip( arr, idx ) {
...
 	}
-	out = new Array( numVals );
+	out = [];
 	for ( j = 0; j < numVals; j++ ) {
-		tmp = new Array( len );
+		tmp = [];
 		k = idx[ j ];
 		for ( i = 0; i < len; i++ ) {
-			tmp[ i ] = arr[ i ][ k ];
+			tmp.push(arr[ i ][ k ]);
```
Comment (Planeshifter) [inline lib/node_modules/@stdlib/utils/unzip/lib/main.js]:
```suggestion
			tmp.push( arr[ i ][ k ] );
```

**Review by Planeshifter — APPROVED** [review]
Thanks!
