### PR TITLE
refactor: address unnecessary casting and fix docs

### LINKED ISSUE #5072: Address commit comments (commit a6ba17c)
This issue was created automatically to address commit comments tagging @stdlib-bot.

**Commit:** [a6ba17cee3a41741a04312d78ddde029470bf338](https://github.com/stdlib-js/stdlib/commit/a6ba17cee3a41741a04312d78ddde029470bf338)

This commit has **8** comment(s) from core contributors that require attention.

### PR DESCRIPTION
**Pull request by saurabhraghuvanshii**
---
type: pre_commit_static_analysis_report
description: Results of running static analysis checks when committing changes. report:
  - task: lint_filenames status: passed
  - task: lint_editorconfig status: passed
  - task: lint_markdown status: passed
  - task: lint_package_json status: na
  - task: lint_repl_help status: na
  - task: lint_javascript_src status: na
  - task: lint_javascript_cli status: na
  - task: lint_javascript_examples status: na
  - task: lint_javascript_tests status: na
  - task: lint_javascript_benchmarks status: na
  - task: lint_python status: na
  - task: lint_r status: na
  - task: lint_c_src status: passed
  - task: lint_c_examples status: na
  - task: lint_c_benchmarks status: na
  - task: lint_c_tests_fixtures status: na
  - task: lint_shell status: na
  - task: lint_typescript_declarations status: na
  - task: lint_typescript_tests status: na
  - task: lint_license_headers status: passed ---

Resolves #5072 .

## Description

> What is the purpose of this pull request?

This pull request:

-   change according to commit comments to fix typos.

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves #5072

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

### CODE REVIEW

File: lib/node_modules/@stdlib/blas/ext/base/dsorthp/src/main.c [hunk 1]
```diff
@@ -81,17 +80,17 @@ void API_SUFFIX(stdlib_strided_dsorthp_ndarray)( const CBLAS_INT N, const double
...
+	} else {
 		sx = strideX;
 		ox = offsetX;
 	}
 	// Set the initial heap size:
 	n = N;
 
 	// Specify an initial "parent" index for building the heap:
-	parent = stdlib_base_floor( N / 2 );
+	parent = ( N / 2 );
```
Comment (kgryte) [inline lib/node_modules/@stdlib/blas/ext/base/dsorthp/src/main.c]:
```suggestion
	parent = N / 2;
```

**Review by kgryte — APPROVED** [review]
LGTM
