### PR TITLE
chore: fix JavaScript lint errors (issue #10447)

### LINKED ISSUE #10447: Fix JavaScript lint errors
## JavaScript Linting Failures

  Linting failures were detected in the automated JavaScript lint workflow run.

  ### Workflow Details

  - Run: https://github.com/stdlib-js/stdlib/actions/runs/22330395305
  - Type: JavaScript Linting
  - Date: 2026-02-24 00:17:44 UTC

  ### Error Details
  ```
  make[1]: Entering directory '/home/runner/work/stdlib/stdlib'

Linting file: lib/node_modules/@stdlib/blas/base/operation-side-str2enum/lib/index.js

Linting file: lib/node_modules/@stdlib/slice/base/lib/index.js

Linting file: lib/node_modules/@stdlib/_tools/makie/plugins/makie-view-cov/lib/main.js

/home/runner/work/stdlib/stdlib/lib/node_modules/@stdlib/_tools/makie/plugins/makie-view-cov/lib/main.js
  92:9  error  Using the `new Array()` constructor is not allowed; use an array literal with push instead  stdlib/no-new-array

✖ 1 problem (1 error, 0 warnings)

Linting failed.

Linting file: lib/node_modules/@stdlib/blas/base/wasm/ccopy/lib/binary.js

Linting file: lib/node_modules/@stdlib/stats/strided/nanmin/lib/accessors.js

Linting file: lib/node_modules/@stdlib/stats/strided/dnanvariancetk/lib/index.js

Linting file: lib/node_modules/@stdlib/number/float16/ctor/lib/valueof.js

Linting file: lib/node_modules/@stdlib/stats/strided/dstdevyc/lib/dstdevyc.native.js

Linting file: lib/node_modules/@stdlib/math/base/special/csignumf/lib/index.js

Linting file: lib/node_modules/@stdlib/utils/keys/lib/is_constructor_prototype_wrapper.js

Linting file: lib/node_modules/@stdlib/string/base/trim/lib/has_builtin.js

Linting file: lib/node_modules/@stdlib/blas/base/gger/lib/main.js

Linting file: lib/node_modules/@stdlib/string/base/replace-after/lib/index.js

Linting file: lib/node_modules/@stdlib/math/strided/special/sramp/lib/ndarray.native.js

Linting file: lib/node_modules/@stdlib/stats/base/ztest/one-sample/results/float64/lib/main.js

Linting file: lib/node_modules/@stdlib/_tools/eslint/rules/jsdoc-maximum-line-length/lib/main.js

/home/runner/work/stdlib/stdlib/lib/node_modules/@stdlib/_tools/eslint/rules/jsdoc-maximum-line-length/lib/main.js
  125:2  error  Function 'copyLocationInfo' should be moved to module scope  stdlib/no-unnecessary-nested-functions

✖ 1 problem (1 error, 0 warnings)

Linting failed.

Linting file: lib/node_modules/@stdlib/math/base/special/kernel-betaincinv/lib/upper_gamma_fraction.js

Linting file: lib/node_modules/@stdlib/stats/strided/snanmaxabs/lib/ndarray.native.js

Linting file: lib/node_modules/@stdlib/iter/union/lib/main.js

Linting file: lib/node_modules/@stdlib/math/base/napi/quinary/lib/index.js

Linting file: lib/node_modules/@stdlib/stats/array/max-by/lib/index.js

Linting file: lib/node_modules/@stdlib/stats/base/snanstdevpn/lib/index.js

Linting file: lib/node_modules/@stdlib/repl/lib/commands/delete_workspace.js

Linting file: lib/node_modules/@stdlib/string/remove-punctuation/lib/main.js

Linting file: lib/node_modules/@stdlib/math/base/special/kernel-log1p/lib/index.js
make[1]: *** [/home/runner/work/stdlib/stdlib/tools/make/lib/lint/javascript/eslint.mk:261: eslint-files] Error 1
make[1]: Leaving directory '/home/runner/work/stdlib/stdlib'
make: *** [/home/runner/work/stdlib/stdlib/tools/make/lib/lint/javascript/Makefile:158: lint-javascript-files] Error 2
  ```

  ### Pull Request Instructions

  -   Please use the following PR title format:
  "chore: fix JavaScript lint errors (issue #<ISSUE_NUMBER>)".
  -   Reference this issue in the "Related Issues" section of the PR body as "resolves #<ISSUE_NUMBER>".

### PR DESCRIPTION
**Pull request by parthodas23**
---
type: pre_commit_static_analysis_report
description: Results of running static analysis checks when committing changes. report:
  - task: lint_filenames status: passed
  - task: lint_editorconfig status: passed
  - task: lint_markdown status: na
  - task: lint_package_json status: na
  - task: lint_repl_help status: na
  - task: lint_javascript_src status: passed
  - task: lint_javascript_cli status: na
  - task: lint_javascript_examples status: na
  - task: lint_javascript_tests status: na
  - task: lint_javascript_benchmarks status: na
  - task: lint_python status: na
  - task: lint_r status: na
  - task: lint_c_src status: na
  - task: lint_c_examples status: na
  - task: lint_c_benchmarks status: na
  - task: lint_c_tests_fixtures status: na
  - task: lint_shell status: na
  - task: lint_typescript_declarations status: passed
  - task: lint_typescript_tests status: na
  - task: lint_license_headers status: passed ---

Resolves #10447.

## Description

> What is the purpose of this pull request?

This pull request:
- Fixes a `stdlib/no-new-array` linting error in `@stdlib/_tools/makie/plugins/makie-view-cov` by replacing the `Array` constructor with an array literal.
- Fixes a `stdlib/no-unnecessary-nested-functions` linting error in `@stdlib/_tools/eslint/rules/jsdoc-maximum-line-length` by moving the `copyLocationInfo` function to the module scope and adjusting indentation/spacing.

## Related Issues

> Does this pull request have any related issues?

This pull request has the following related issues:

-   #10447

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

The fixes were verified locally using the following commands:

npx eslint lib/node_modules/@stdlib/_tools/makie/plugins/makie-view-cov/lib/main.js
npx eslint lib/node_modules/@stdlib/_tools/eslint/rules/jsdoc-maximum-line-length/lib/main.js

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

### AI Assistance

> When authoring the changes proposed in this PR, did you use any kind of AI assistance?

-   [x] Yes
-   [ ] No

If you answered "yes" above, how did you use AI assistance?

-   [ ] Code generation (e.g., when writing an implementation or fixing a bug)
-   [ ] Test/benchmark generation
-   [ ] Documentation (including examples)
-   [x] Research and understanding

#### Disclosure

> If you answered "yes" to using AI assistance, please provide a short disclosure indicating how you used AI assistance. This helps reviewers determine how much scrutiny to apply when reviewing your contribution. Example disclosures: "This PR was written primarily by Claude Code." or "I consulted ChatGPT to understand the codebase, but the proposed changes were fully authored manually by myself.".

I consulted Gemini to understand the specific stdlib linting rules and to ensure the function relocation followed the project's architectural patterns, but the final implementation was manually reviewed and verified locally via npx eslint.

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

### CODE REVIEW

File: lib/node_modules/@stdlib/_tools/eslint/rules/jsdoc-maximum-line-length/lib/main.js [hunk 1]
```diff
@@ -151,6 +131,26 @@ function main( context ) {
...
 }
 
+/**
+* Copies AST node location info.
+*
+* @private
+* @param {Object} loc - AST node location
+* @returns {Object} copied location info
+*/
+function copyLocationInfo( loc ) { // <--- No extra spaces before "function"
```
Comment (Planeshifter) [inline lib/node_modules/@stdlib/_tools/eslint/rules/jsdoc-maximum-line-length/lib/main.js]:
```suggestion
function copyLocationInfo( loc ) {
```

**Review by Planeshifter — APPROVED** [review]
