### PR TITLE
chore: fix JavaScript lint errors (issue #8670)

### LINKED ISSUE #8670: Fix JavaScript lint errors
## JavaScript Linting Failures

  Linting failures were detected in the automated JavaScript lint workflow run.

  ### Workflow Details

  - Run: https://github.com/stdlib-js/stdlib/actions/runs/19806864536
  - Type: JavaScript Linting
  - Date: 2025-12-01 00:16:22 UTC

  ### Error Details
  ```
  make[1]: Entering directory '/home/runner/work/stdlib/stdlib'

Linting file: lib/node_modules/@stdlib/ndarray/base/unary-reduce-strided1d/lib/7d_accessors.js

Linting file: lib/node_modules/@stdlib/stats/array/variancech/lib/main.js

Linting file: lib/node_modules/@stdlib/dstructs/struct/lib/has_properties.js

Linting file: lib/node_modules/@stdlib/stats/strided/smediansorted/lib/main.js

Linting file: lib/node_modules/@stdlib/complex/float32/reim/lib/index.js

Linting file: lib/node_modules/@stdlib/blas/ext/base/sapxsumors/lib/sapxsumors.js

Linting file: lib/node_modules/@stdlib/ndarray/base/some/lib/5d.js

Linting file: lib/node_modules/@stdlib/utils/timeit/lib/main.js

/home/runner/work/stdlib/stdlib/lib/node_modules/@stdlib/utils/timeit/lib/main.js
  103:12  error  Using the `new Array()` constructor is not allowed; use an array literal with push instead  stdlib/no-new-array

✖ 1 problem (1 error, 0 warnings)

Linting failed.

Linting file: lib/node_modules/@stdlib/_tools/modules/import-require/lib/index.js

Linting file: lib/node_modules/@stdlib/plot/sparklines/unicode/lib/props/infinities/get.js

Linting file: lib/node_modules/@stdlib/ndarray/base/some/lib/10d_blocked_accessors.js

Linting file: lib/node_modules/@stdlib/blas/ext/base/dsnansum/lib/dsnansum.js

Linting file: lib/node_modules/@stdlib/math/iter/special/ceil/lib/index.js

Linting file: lib/node_modules/@stdlib/repl/lib/commands/assignfrom.js

Linting file: lib/node_modules/@stdlib/math/iter/special/floor2/lib/main.js

Linting file: lib/node_modules/@stdlib/wasm/base/dtype2wasm/lib/main.js

Linting file: lib/node_modules/@stdlib/array/base/take2d/lib/index.js

Linting file: lib/node_modules/@stdlib/ndarray/base/unary-reduce-strided1d-by/lib/main.js

Linting file: lib/node_modules/@stdlib/blas/ext/base/dsumpw/lib/dsumpw.native.js

Linting file: lib/node_modules/@stdlib/ndarray/base/assert/is-buffer-length-compatible/lib/main.js

Linting file: lib/node_modules/@stdlib/repl/presentation/lib/commands/last_fragment.js

/home/runner/work/stdlib/stdlib/lib/node_modules/@stdlib/repl/presentation/lib/commands/last_fragment.js
  46:3  error  Function 'onDrain' should be moved to outer function scope  stdlib/no-unnecessary-nested-functions

✖ 1 problem (1 error, 0 warnings)

Linting failed.

Linting file: lib/node_modules/@stdlib/assert/is-complex64ndarray-like/lib/main.js

Linting file: lib/node_modules/@stdlib/stats/incr/minabs/lib/main.js

Linting file: lib/node_modules/@stdlib/_tools/eslint/rules/jsdoc-list-item-bullet-indent/lib/main.js

/home/runner/work/stdlib/stdlib/lib/node_modules/@stdlib/_tools/eslint/rules/jsdoc-list-item-bullet-indent/lib/main.js
  122:2  error  Function 'copyLocationInfo' should be moved to module scope  stdlib/no-unnecessary-nested-functions

✖ 1 problem (1 error, 0 warnings)

Linting failed.

Linting file: lib/node_modules/@stdlib/stats/strided/dnanmean/lib/dnanmean.js

Linting file: lib/node_modules/@stdlib/complex/float64/reviver/lib/index.js

Linting file: lib/node_modules/@stdlib/math/strided/special/deg2rad/lib/deg2rad.js

Linting file: lib/node_modules/@stdlib/utils/until/lib/index.js
make[1]: *** [/home/runner/work/stdlib/stdlib/tools/make/lib/lint/javascript/eslint.mk:261: eslint-files] Error 1
make[1]: Leaving directory '/home/runner/work/stdlib/stdlib'
make: *** [/home/runner/work/stdlib/stdlib/tools/make/lib/lint/javascript/Makefile:158: lint-javascript-files] Error 2
  ```

  ### Pull Request Instructions

  -   Please use the following PR title format:
  "chore: fix JavaScript lint errors (issue #<ISSUE_NUMBER>)".
  -   Reference this issue in the "Related Issues" section of the PR body as "resolves #<ISSUE_NUMBER>".

### PR DESCRIPTION
**Pull request by JavaTypedScript**
Resolves #8670 .

## Description

> What is the purpose of this pull request?

This pull request:

-   Resolves the linting error in lib/node_modules/@stdlib/utils/timeit/lib/main.js by replay new Array( ) by [ ]    and push to initialize, lib/node_modules/@stdlib/_tools/eslint/rules/jsdoc-list-item-bullet-indent/lib/main.js to bring copyLocationInfo( ) into a module scope and lib/node_modules/@stdlib/repl/presentation/lib/commands/last_fragment.js to bring onDrain() to function scope ( ).

## Related Issues

> Does this pull request have any related issues?

This pull request has the following related issues:

-   resolves #8670.

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

### AI Assistance

> When authoring the changes proposed in this PR, did you use any kind of AI assistance?

-   [ ] Yes
-   [x] No

If you answered "yes" above, how did you use AI assistance?

-   [ ] Code generation (e.g., when writing an implementation or fixing a bug)
-   [ ] Test/benchmark generation
-   [ ] Documentation (including examples)
-   [ ] Research and understanding

#### Disclosure

> If you answered "yes" to using AI assistance, please provide a short disclosure indicating how you used AI assistance. This helps reviewers determine how much scrutiny to apply when reviewing your contribution. Example disclosures: "This PR was written primarily by Claude Code." or "I consulted ChatGPT to understand the codebase, but the proposed changes were fully authored manually by myself.".

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

### CODE REVIEW

File: lib/node_modules/@stdlib/utils/timeit/lib/main.js [hunk 1]
```diff
@@ -35,7 +35,7 @@ var transform = require( './transform.js' );
 
 // VARIABLES //
 
-var FILENAME = 'timeit.js';
+var FILENAME = 'timeit.js'; // filename
```
Comment (kgryte) [inline lib/node_modules/@stdlib/utils/timeit/lib/main.js]:
```suggestion
var FILENAME = 'timeit.js';
```

**Review by kgryte — APPROVED** [review]
LGTM after some clean-up.

**Comment by kgryte** [comment]
The CI failure is not due to changes introduced in this PR, so I'll go ahead and merge.
