### PR TITLE
chore: fix JavaScript lint errors (issue #6577)

### LINKED ISSUE #6577: Fix JavaScript lint errors
## JavaScript Linting Failures

  Linting failures were detected in the automated JavaScript lint workflow run.

  ### Workflow Details

  - Run: https://github.com/stdlib-js/stdlib/actions/runs/14286982974
  - Type: JavaScript Linting
  - Date: 2025-04-06 00:40:56 UTC

  ### Error Details
  ```
  make[1]: Entering directory '/home/runner/work/stdlib/stdlib'

Linting file: lib/node_modules/@stdlib/number/float64/base/get-low-word/lib/native.js

Linting file: lib/node_modules/@stdlib/stats/strided/dcumax/lib/native.js

Linting file: lib/node_modules/@stdlib/math/base/tools/normhermitepoly/lib/index.js

Linting file: lib/node_modules/@stdlib/blas/base/wasm/srot/scripts/build.js

Linting file: lib/node_modules/@stdlib/math/base/special/maxabsf/lib/main.js

Linting file: lib/node_modules/@stdlib/math/iter/special/gamma1pm1/lib/index.js

Linting file: lib/node_modules/@stdlib/ndarray/base/ind/lib/index.js

Linting file: lib/node_modules/@stdlib/iter/to-array-view-right/lib/main.js

Linting file: lib/node_modules/@stdlib/stats/base/dists/pareto-type1/skewness/lib/index.js

Linting file: lib/node_modules/@stdlib/math/base/special/gammaincinv/lib/chepolsum.js

Linting file: lib/node_modules/@stdlib/stats/base/dists/t/mean/lib/main.js

Linting file: lib/node_modules/@stdlib/math/base/napi/ternary/lib/native.js

Linting file: lib/node_modules/@stdlib/ndarray/base/every/lib/8d.js

Linting file: lib/node_modules/@stdlib/datasets/sotu/scripts/build.js

/home/runner/work/stdlib/stdlib/lib/node_modules/@stdlib/datasets/sotu/scripts/build.js
   43:22  warning  Unknown word: "sotu"                                                                        @cspell/spellchecker
  495:1   warning  File has too many lines (361). Maximum allowed is 300                                       max-lines
  524:8   error    Using the `new Array()` constructor is not allowed; use an array literal with push instead  stdlib/no-new-array

✖ 3 problems (1 error, 2 warnings)

Linting failed.

Linting file: lib/node_modules/@stdlib/repl/lib/settings_names.js

Linting file: lib/node_modules/@stdlib/array/base/ones4d/lib/index.js

Linting file: lib/node_modules/@stdlib/math/strided/special/inv/lib/inv.js

Linting file: lib/node_modules/@stdlib/stats/base/dists/frechet/cdf/lib/index.js

/home/runner/work/stdlib/stdlib/lib/node_modules/@stdlib/stats/base/dists/frechet/cdf/lib/index.js
  22:5  warning  Unknown word: "échet"  @cspell/spellchecker

✖ 1 problem (0 errors, 1 warning)


Linting file: lib/node_modules/@stdlib/blas/ext/base/ssortsh/lib/ndarray.js

Linting file: lib/node_modules/@stdlib/math/strided/special/deg2rad/lib/ndarray.native.js

Linting file: lib/node_modules/@stdlib/blas/base/sdsdot/lib/sdsdot.native.js

Linting file: lib/node_modules/@stdlib/_tools/github/rank-users/lib/index.js

Linting file: lib/node_modules/@stdlib/assert/is-reference-error/lib/index.js

Linting file: lib/node_modules/@stdlib/blas/base/sgemm/lib/ndarray.js

Linting file: lib/node_modules/@stdlib/math/base/special/kernel-betaincinv/lib/polyval_co13.js
make[1]: *** [/home/runner/work/stdlib/stdlib/tools/make/lib/lint/javascript/eslint.mk:255: eslint-files] Error 1
make[1]: Leaving directory '/home/runner/work/stdlib/stdlib'
make: *** [/home/runner/work/stdlib/stdlib/tools/make/lib/lint/javascript/Makefile:158: lint-javascript-files] Error 2
  ```

  ### Pull Request Instructions

  -   Please use the following PR title format:
  "chore: fix JavaScript lint errors (issue #<ISSUE_NUMBER>)".
  -   Reference this issue in the "Related Issues" section of the PR body as "resolves #<ISSUE_NUMBER>".

### PR DESCRIPTION
**Pull request by Swapnil-2502**
Resolves #6577.

## Description

> What is the purpose of this pull request?

This pull request:

-   Fixes JavaScript lint errors in Linting file: Linting file: lib/node_modules/@stdlib/datasets/sotu/scripts/build.js
-   524:8   error    Using the `new Array()` constructor is not allowed; use an array literal with push instead  stdlib/no-new-array

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves #6577

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

### CODE REVIEW

File: lib/node_modules/@stdlib/datasets/sotu/scripts/build.js [hunk 1]
```diff
@@ -544,7 +544,7 @@ function datapackage( files ) {
 			obj.format = 'json';
 			obj.mediatype = 'application/json';
 		}
-		arr[ i ] = obj;
+		arr.push(obj);
```
Comment (Planeshifter) [inline lib/node_modules/@stdlib/datasets/sotu/scripts/build.js]:
```suggestion
		arr.push( obj );
```

**Review by Planeshifter — APPROVED** [review]
Thank you!
