### PR TITLE
chore: fix lint errors (#8183)

### LINKED ISSUE #8183: Fix JavaScript lint errors
## JavaScript Linting Failures

  Linting failures were detected in the automated JavaScript lint workflow run.

  ### Workflow Details

  - Run: https://github.com/stdlib-js/stdlib/actions/runs/18179081842
  - Type: JavaScript Linting
  - Date: 2025-10-02 00:16:12 UTC

  ### Error Details
  ```
  make[1]: Entering directory '/home/runner/work/stdlib/stdlib'

Linting file: lib/node_modules/@stdlib/stats/base/dists/chisquare/variance/lib/index.js

Linting file: lib/node_modules/@stdlib/lapack/base/dlarf1f/lib/index.js

Linting file: lib/node_modules/@stdlib/blas/ext/base/dsortins/lib/native.js

Linting file: lib/node_modules/@stdlib/ndarray/base/count-falsy/lib/4d_complex.js

Linting file: lib/node_modules/@stdlib/blas/base/ddot/lib/ndarray.js

Linting file: lib/node_modules/@stdlib/stats/strided/dmeanpw/lib/native.js

Linting file: lib/node_modules/@stdlib/number/float32/base/to-binary-string/lib/index.js

Linting file: lib/node_modules/@stdlib/ndarray/base/dtype-resolve-str/lib/main.js

Linting file: lib/node_modules/@stdlib/blas/ext/base/ssort2hp/lib/ndarray.native.js

Linting file: lib/node_modules/@stdlib/stats/strided/mskrange/lib/main.js

Linting file: lib/node_modules/@stdlib/math/base/special/nanmax/lib/index.js

Linting file: lib/node_modules/@stdlib/_tools/static-analysis/js/program-summary/lib/whitespace.js

Linting file: lib/node_modules/@stdlib/stats/strided/mediansorted/lib/accessors.js

Linting file: lib/node_modules/@stdlib/stats/strided/dsemch/lib/dsemch.native.js

Linting file: lib/node_modules/@stdlib/stats/base/snanvariancech/lib/index.js

Linting file: lib/node_modules/@stdlib/ndarray/base/binary/lib/3d_blocked.js

Linting file: lib/node_modules/@stdlib/string/tools/grapheme-cluster-break/lib/index.js

Linting file: lib/node_modules/@stdlib/napi/argv-strided-uint16array/lib/main.js

Linting file: lib/node_modules/@stdlib/utils/nonenumerable-properties-in/lib/main.js

/home/runner/work/stdlib/stdlib/lib/node_modules/@stdlib/utils/nonenumerable-properties-in/lib/main.js
  54:8  error  Object is used without loading it beforehand via require()  stdlib/require-globals

✖ 1 problem (1 error, 0 warnings)

Linting failed.

Linting file: lib/node_modules/@stdlib/constants/float32/max-safe-nth-factorial/lib/index.js

Linting file: lib/node_modules/@stdlib/blas/base/dsdot/lib/ndarray.js

Linting file: lib/node_modules/@stdlib/random/streams/exponential/lib/factory.js

Linting file: lib/node_modules/@stdlib/_tools/github/delete-token/lib/request.js

Linting file: lib/node_modules/@stdlib/blas/ext/base/gapxsumkbn/lib/main.js

Linting file: lib/node_modules/@stdlib/stats/ttest2/lib/main.js
make[1]: *** [/home/runner/work/stdlib/stdlib/tools/make/lib/lint/javascript/eslint.mk:261: eslint-files] Error 1
make[1]: Leaving directory '/home/runner/work/stdlib/stdlib'
make: *** [/home/runner/work/stdlib/stdlib/tools/make/lib/lint/javascript/Makefile:158: lint-javascript-files] Error 2
make[1]: Entering directory '/home/runner/work/stdlib/stdlib'

Linting file: lib/node_modules/@stdlib/ndarray/base/loop-interchange-order/examples/index.js

Linting file: lib/node_modules/@stdlib/number/uint16/base/from-binary-string/examples/index.js

Linting file: lib/node_modules/@stdlib/stats/ztest/examples/index.js

/home/runner/work/stdlib/stdlib/lib/node_modules/@stdlib/stats/ztest/examples/index.js
  32:7  error  Using the `new Array()` constructor is not allowed; use an array literal with push instead  stdlib/no-new-array

✖ 1 problem (1 error, 0 warnings)

Linting failed.

Linting file: lib/node_modules/@stdlib/stats/base/dists/triangular/quantile/examples/index.js

Linting file: lib/node_modules/@stdlib/array/base/flatten3d-by/examples/index.js

Linting file: lib/node_modules/@stdlib/iter/cusome-by/examples/index.js
make[1]: *** [/home/runner/work/stdlib/stdlib/tools/make/lib/lint/javascript/eslint.mk:261: eslint-files] Error 1
make[1]: Leaving directory '/home/runner/work/stdlib/stdlib'
make: *** [/home/runner/work/stdlib/stdlib/tools/make/lib/lint/javascript/Makefile:158: lint-javascript-files] Error 2
  ```

  ### Pull Request Instructions

  -   Please use the following PR title format:
  "chore: fix JavaScript lint errors (issue #<ISSUE_NUMBER>)".
  -   Reference this issue in the "Related Issues" section of the PR body as "resolves #<ISSUE_NUMBER>".

### PR DESCRIPTION
**Pull request by Payal-Goswami**
Resolves #8183.

## Description

This pull request fixes:

- File: lib/node_modules/@stdlib/utils/nonenumerable-properties-in/lib/main.js

Added a missing require statement for Object to satisfy the stdlib/require-globals lint rule.

- File: lib/node_modules/@stdlib/stats/ztest/examples/index.js

Replaced the prohibited new Array() constructor with an array literal and loop push.

## Related Issues

This pull request:

-   resolves #8183

## Questions

No.

## Other

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

### CODE REVIEW

File: lib/node_modules/@stdlib/stats/ztest/examples/index.js
Comment (kgryte) [inline lib/node_modules/@stdlib/stats/ztest/examples/index.js:1]: @Payal-Goswami Would you mind making this same change to the corresponding README? The example is duplicated there.

Comment (Payal-Goswami) [reply lib/node_modules/@stdlib/stats/ztest/examples/index.js:1]: @kgryte Got it 👍, I’ll update the README accordingly.

Comment (Payal-Goswami) [reply lib/node_modules/@stdlib/stats/ztest/examples/index.js:1]: @kgryte Updated the README examples to match the latest index.js changes as suggested.

File: lib/node_modules/@stdlib/stats/ztest/examples/index.js [hunk 1]
```diff
@@ -18,24 +18,14 @@
...
-	arr[ i ] = rnorm();
-}
-
-// Test whether true mean is equal to zero:
-out = ztest( arr, 4.0 );
+// Test whether true mean is equal to 4.0:
+var out = ztest( arr, 4.0 );
 console.log( out.print() );
 
 // Test whether true mean is equal to five:
```
Comment (kgryte) [inline lib/node_modules/@stdlib/stats/ztest/examples/index.js]:
```suggestion
// Test whether true mean is equal to 5.0:
```

File: lib/node_modules/@stdlib/stats/ztest/README.md [hunk 2]
```diff
@@ -35,24 +35,18 @@ var ztest = require( '@stdlib/stats/ztest' );
...
-
-var arr = new Array( 300 );
-var i;
-for ( i = 0; i < arr.length; i++ ) {
-    arr[ i ] = rnorm();
-}
+// Create an array of random numbers:
+var arr = normal( 300, 0.0, 2.0 );
 
+// Test whether true mean is equal to 2.0:
```
Comment (kgryte) [inline lib/node_modules/@stdlib/stats/ztest/README.md]:
```suggestion
// Test whether true mean is equal to 0.0:
```

**Review by kgryte — APPROVED** [review]

**Comment by Payal-Goswami** [comment]
Thanks for merging! 🙌 I appreciate the adjustments you made - I’ll take note of them when working on future contributions.
