### PR TITLE
chore: fix JavaScript lint errors (issue #8050)

### LINKED ISSUE #8050: Fix JavaScript lint errors
## JavaScript Linting Failures

  Linting failures were detected in the automated JavaScript lint workflow run.

  ### Workflow Details

  - Run: https://github.com/stdlib-js/stdlib/actions/runs/17598839235
  - Type: JavaScript Linting
  - Date: 2025-09-10 00:12:49 UTC

  ### Error Details
  ```
  make[1]: Entering directory '/home/runner/work/stdlib/stdlib'

Linting file: lib/node_modules/@stdlib/blas/ext/base/wasm/dapxsumors/lib/binary.browser.js

Linting file: lib/node_modules/@stdlib/blas/ext/base/dcusumkbn/lib/dcusumkbn.native.js

Linting file: lib/node_modules/@stdlib/math/base/special/kernel-sin/lib/native.js

Linting file: lib/node_modules/@stdlib/stats/strided/nanmax-by/lib/main.js

Linting file: lib/node_modules/@stdlib/ndarray/to-fancy/lib/resolve_index.js

Linting file: lib/node_modules/@stdlib/complex/base/wrap-function/lib/index.js

Linting file: lib/node_modules/@stdlib/assert/is-enumerable-property/lib/native.js

/home/runner/work/stdlib/stdlib/lib/node_modules/@stdlib/assert/is-enumerable-property/lib/native.js
  23:1  error  Encountered an error while running code: `Cannot convert undefined or null to object`.Did you mean to include a `// throws <TypeError>` annotation instead of `// returns true`?   stdlib/jsdoc-doctest
  23:1  error  Encountered an error while running code: `Cannot convert undefined or null to object`.Did you mean to include a `// throws <TypeError>` annotation instead of `// returns false`?  stdlib/jsdoc-doctest

✖ 2 problems (2 errors, 0 warnings)
  2 errors and 0 warnings potentially fixable with the `--fix` option.

Linting failed.

Linting file: lib/node_modules/@stdlib/stats/strided/dvarm/lib/index.js

Linting file: lib/node_modules/@stdlib/_tools/doctest/create-annotation-value/lib/validate.js

Linting file: lib/node_modules/@stdlib/stats/base/dists/laplace/lib/index.js

Linting file: lib/node_modules/@stdlib/random/streams/frechet/lib/main.js

Linting file: lib/node_modules/@stdlib/blas/base/wasm/zswap/lib/binary.js

Linting file: lib/node_modules/@stdlib/assert/tools/typed-array-function/lib/index.js

Linting file: lib/node_modules/@stdlib/blas/base/matrix-orientation-enum2str/lib/index.js

Linting file: lib/node_modules/@stdlib/stats/base/dists/chi/ctor/lib/main.js

Linting file: lib/node_modules/@stdlib/stats/base/snanstdevwd/lib/snanstdevwd.js

Linting file: lib/node_modules/@stdlib/assert/has-bigint-support/lib/main.js

/home/runner/work/stdlib/stdlib/lib/node_modules/@stdlib/assert/has-bigint-support/lib/main.js
  47:10  error  Using the built-in global `BigInt` constructor is not allowed; use `@stdlib/bigint/ctor` instead  stdlib/no-builtin-big-int

✖ 1 problem (1 error, 0 warnings)

Linting failed.

Linting file: lib/node_modules/@stdlib/blas/base/ddot/lib/main.js

Linting file: lib/node_modules/@stdlib/ndarray/base/for-each/lib/3d_blocked.js
0
0
0
0
0
0

Linting file: lib/node_modules/@stdlib/math/base/utils/relative-difference/lib/minabs.js

Linting file: lib/node_modules/@stdlib/math/base/special/absgammalnf/lib/polyval_t2.js
make[1]: *** [/home/runner/work/stdlib/stdlib/tools/make/lib/lint/javascript/eslint.mk:261: eslint-files] Error 1
make[1]: Leaving directory '/home/runner/work/stdlib/stdlib'
make: *** [/home/runner/work/stdlib/stdlib/tools/make/lib/lint/javascript/Makefile:158: lint-javascript-files] Error 2
  ```

  ### Pull Request Instructions

  -   Please use the following PR title format:
  "chore: fix JavaScript lint errors (issue #<ISSUE_NUMBER>)".
  -   Reference this issue in the "Related Issues" section of the PR body as "resolves #<ISSUE_NUMBER>".

### PR DESCRIPTION
**Pull request by rajanarahul93**
Resolves #8050.

## Description

> What is the purpose of this pull request?

This pull request:

-   fixes two separate linting errors: a `jsdoc-doctest` error in `@stdlib/assert/is-enumerable-property` by adding missing JSDoc examples, and a `no-builtin-big-int` error in `@stdlib/assert/has-bigint-support` by refactoring to use the stdlib-approved `@stdlib/bigint/ctor`.

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves #8050

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

### CODE REVIEW

File: lib/node_modules/@stdlib/assert/has-bigint-support/lib/main.js [hunk 1]
```diff
@@ -20,12 +20,7 @@
 
 // MODULES //
 
-var getGlobal = require( '@stdlib/utils/global' );
```
Comment (kgryte) [inline lib/node_modules/@stdlib/assert/has-bigint-support/lib/main.js]: This is most definitely not the change we are looking for. You need to revert these changes. Instead, for L45 and L47, you simply need to add `stdlib/no-builtin-big-int` to the list of lint rules which are disabled. It is intentional for us to use the `BigInt` global in this file. Importing a module defeats that purpose.

**Review by kgryte — CHANGES_REQUESTED** [review]
Left initial comments.

**Comment by kgryte** [comment]
@rajanarahul93 Please do not force push and overwrite existing changes. In doing so, you reverted changes that I had made to fix your PR. Please consult our contributing guide for tips on how to work with Git after pushing changes to a remote origin.

**Review by kgryte — DISMISSED** [review]

**Review by kgryte — APPROVED** [review]

**Comment by rajanarahul93** [comment]
Understood, thank you for merging the PR. I’ll make sure not to force push or overwrite changes next time!!
