### PR TITLE
chore: fix C lint errors (issue #6272)

### LINKED ISSUE #6272: Fix C lint errors
## C Linting Failures

Linting failures were detected in the automated lint workflow run.

### Workflow Details

-   Run: https://github.com/stdlib-js/stdlib/actions/runs/14002968536
-   Type: C Linting
-   Date: 2025-03-22 00:12:42 UTC

### Error Details

```

lib/node_modules/@stdlib/strided/base/cmap/examples/c/example.c:34:16: style: Variable 'X' can be declared as const array [constVariable]
 float complex X[] = { 1.0+1.0*I, 2.0+2.0*I, 3.0+3.0*I, 4.0+4.0*I, 5.0+5.0*I, 6.0+6.0*I };
               ^
```

### Pull Request Instructions

-   Please use the following PR title format:
"chore: fix C lint errors (issue #<ISSUE_NUMBER>)".
-   Reference this issue in the "Related Issues" section of the PR body as "resolves #<ISSUE_NUMBER>".

### PR DESCRIPTION
**Pull request by AaryaBalwadkar**
Resolves #6272.

## Description

> What is the purpose of this pull request?

This pull request:

-   Fixes C lint error by making the float complex X[] and float complex Y[] array as constant.

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves #6272 

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

### CODE REVIEW

File: lib/node_modules/@stdlib/strided/base/cmap/examples/c/example.c [hunk 1]
```diff
@@ -31,10 +31,10 @@ static float complex scale( const float complex x ) {
 
 int main( void ) {
 	// Create an input strided array:
-	float complex X[] = { 1.0+1.0*I, 2.0+2.0*I, 3.0+3.0*I, 4.0+4.0*I, 5.0+5.0*I, 6.0+6.0*I };
+	const float complex X[] = { 1.0+1.0*I, 2.0+2.0*I, 3.0+3.0*I, 4.0+4.0*I, 5.0+5.0*I, 6.0+6.0*I };
 
 	// Create an output strided array:
-	float complex Y[] = { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 };
+	const float complex Y[] = { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 };
```
Comment (kgryte) [inline lib/node_modules/@stdlib/strided/base/cmap/examples/c/example.c]:
```suggestion
	float complex Y[] = { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 };
```

**Review by kgryte — APPROVED** [review]
