### PR TITLE
chore: fix JavaScript lint errors (issue #9687)

### LINKED ISSUE #9687: Fix JavaScript lint errors
## JavaScript Linting Failures

  Linting failures were detected in the automated JavaScript lint workflow run.

  ### Workflow Details

  - Run: https://github.com/stdlib-js/stdlib/actions/runs/20886404184
  - Type: JavaScript Linting
  - Date: 2026-01-11 00:15:22 UTC

  ### Error Details
  ```
  make[1]: Entering directory '/home/runner/work/stdlib/stdlib'

Linting file: lib/node_modules/@stdlib/math/base/special/cabs2/lib/native.js

Linting file: lib/node_modules/@stdlib/stats/base/ztest/two-sample/results/to-json/lib/main.js

Linting file: lib/node_modules/@stdlib/utils/async/do-while/lib/main.js

/home/runner/work/stdlib/stdlib/lib/node_modules/@stdlib/utils/async/do-while/lib/main.js
  94:11  error  Using the `new Array()` constructor is not allowed; use an array literal with push instead  stdlib/no-new-array

✖ 1 problem (1 error, 0 warnings)

Linting failed.

Linting file: lib/node_modules/@stdlib/ndarray/base/some/lib/8d.js

Linting file: lib/node_modules/@stdlib/fs/resolve-parent-paths/lib/index.js

Linting file: lib/node_modules/@stdlib/stats/base/dists/planck/cdf/lib/main.js

Linting file: lib/node_modules/@stdlib/stats/kstest/lib/smirnov.js

Linting file: lib/node_modules/@stdlib/constants/float32/num-exponent-bits/lib/index.js

Linting file: lib/node_modules/@stdlib/math/strided/special/smskfloor/lib/ndarray.js

Linting file: lib/node_modules/@stdlib/iter/datespace/lib/index.js

Linting file: lib/node_modules/@stdlib/blas/base/dgemv/lib/native.js

Linting file: lib/node_modules/@stdlib/ndarray/base/count-if/lib/6d_accessors.js

Linting file: lib/node_modules/@stdlib/_tools/eslint/rules/jsdoc-no-heading-content-indent/lib/index.js

Linting file: lib/node_modules/@stdlib/string/uppercase/lib/index.js

Linting file: lib/node_modules/@stdlib/math/strided/special/abs2/lib/abs2.native.js

Linting file: lib/node_modules/@stdlib/array/base/indices-complement/lib/main.js

Linting file: lib/node_modules/@stdlib/number/uint32/base/sub/lib/main.js

Linting file: lib/node_modules/@stdlib/assert/has-async-iterator-symbol-support/lib/main.js

Linting file: lib/node_modules/@stdlib/math/base/special/fresnelc/lib/rational_pcqc.js

Linting file: lib/node_modules/@stdlib/ndarray/base/reverse-dimension/lib/index.js

Linting file: lib/node_modules/@stdlib/blas/ext/base/gsortsh/lib/ndarray.js
make[1]: *** [/home/runner/work/stdlib/stdlib/tools/make/lib/lint/javascript/eslint.mk:261: eslint-files] Error 1
make[1]: Leaving directory '/home/runner/work/stdlib/stdlib'
make: *** [/home/runner/work/stdlib/stdlib/tools/make/lib/lint/javascript/Makefile:158: lint-javascript-files] Error 2
make[1]: Entering directory '/home/runner/work/stdlib/stdlib'

Linting file: lib/node_modules/@stdlib/stats/iter/sum/test/test.js

Linting file: lib/node_modules/@stdlib/_tools/eslint/rules/jsdoc-no-table-indentation/test/test.js

Linting file: lib/node_modules/@stdlib/ndarray/base/complement-shape/test/test.js

Linting file: lib/node_modules/@stdlib/random/iter/laplace/test/test.js

Linting file: lib/node_modules/@stdlib/object/test/test.js

Linting file: lib/node_modules/@stdlib/_tools/eslint/rules/jsdoc-no-duplicate-headings-in-section/test/fixtures/valid.js

Linting file: lib/node_modules/@stdlib/assert/is-prng-like/test/test.js

Linting file: lib/node_modules/@stdlib/_tools/lint/license-header-glob/test/fixtures/good/file.node.js

Linting file: lib/node_modules/@stdlib/assert/is-plain-object-array/test/test.js

Linting file: lib/node_modules/@stdlib/lapack/base/claswp/test/test.ndarray.js

/home/runner/work/stdlib/stdlib/lib/node_modules/@stdlib/lapack/base/claswp/test/test.ndarray.js
  51:1  error  Unexpected empty line between require statements  stdlib/no-empty-lines-between-requires

✖ 1 problem (1 error, 0 warnings)
  1 error and 0 warnings potentially fixable with the `--fix` option.

Linting failed.

Linting file: lib/node_modules/@stdlib/array/base/cunone-by/test/test.main.js

Linting file: lib/node_modules/@stdlib/stats/strided/wasm/dmeanwd/test/test.ndarray.js

Linting file: lib/node_modules/@stdlib/assert/napi/is-type/test/test.js

Linting file: lib/node_modules/@stdlib/random/streams/cauchy/test/test.cli.js
make[1]: *** [/home/runner/work/stdlib/stdlib/tools/make/lib/lint/javascript/eslint.mk:261: eslint-files] Error 1
make[1]: Leaving directory '/home/runner/work/stdlib/stdlib'
make: *** [/home/runner/work/stdlib/stdlib/tools/make/lib/lint/javascript/Makefile:158: lint-javascript-files] Error 2
  ```

  ### Pull Request Instructions

  -   Please use the following PR title format:
  "chore: fix JavaScript lint errors (issue #<ISSUE_NUMBER>)".
  -   Reference this issue in the "Related Issues" section of the PR body as "resolves #<ISSUE_NUMBER>".

### PR DESCRIPTION
**Pull request by DivyanshuVortex**
---
type: pre_commit_static_analysis_report
description: Results of running static analysis checks when committing changes. report:
  - task: lint_filenames status: passed
  - task: lint_editorconfig status: passed
  - task: lint_markdown status: na
  - task: lint_package_json status: na
  - task: lint_repl_help status: na
  - task: lint_javascript_src status: passed
  - task: lint_javascript_cli status: na
  - task: lint_javascript_examples status: na
  - task: lint_javascript_tests status: passed
  - task: lint_javascript_benchmarks status: na
  - task: lint_python status: na
  - task: lint_r status: na
  - task: lint_c_src status: na
  - task: lint_c_examples status: na
  - task: lint_c_benchmarks status: na
  - task: lint_c_tests_fixtures status: na
  - task: lint_shell status: na
  - task: lint_typescript_declarations status: passed
  - task: lint_typescript_tests status: na
  - task: lint_license_headers status: passed ---

Resolves #9687
## Description

> What is the purpose of this pull request?

This pull request:

-   solve the lint errors

## Related Issues

> Does this pull request have any related issues?

This pull request has the following related issues:

-   #5377

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

### AI Assistance

> When authoring the changes proposed in this PR, did you use any kind of AI assistance?

-   [ ] Yes
-   [x] No

If you answered "yes" above, how did you use AI assistance?

-   [ ] Code generation (e.g., when writing an implementation or fixing a bug)
-   [ ] Test/benchmark generation
-   [ ] Documentation (including examples)
-   [ ] Research and understanding

#### Disclosure

> If you answered "yes" to using AI assistance, please provide a short disclosure indicating how you used AI assistance. This helps reviewers determine how much scrutiny to apply when reviewing your contribution. Example disclosures: "This PR was written primarily by Claude Code." or "I consulted ChatGPT to understand the codebase, but the proposed changes were fully authored manually by myself.".

{{TODO: add disclosure if applicable}}

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

### CODE REVIEW

**Review by Planeshifter — APPROVED** [review]

File: lib/node_modules/@stdlib/utils/async/do-while/lib/main.js [hunk 1]
```diff
@@ -91,7 +91,7 @@ function doWhileAsync( fcn, predicate, done, thisArg ) {
 
 		// Cache the most recent results...
 		if ( arguments.length > 1 ) {
-			args = new Array( arguments.length-1 );
+			args = new Array( arguments.length-1 ); // eslint-disable-line stdlib/no-new-array
```
Comment (kgryte) [inline lib/node_modules/@stdlib/utils/async/do-while/lib/main.js:94]: This is not the correct change. This should have been converted to `[]` and then use `#.push` in the loop.

File: lib/node_modules/@stdlib/lapack/base/claswp/test/test.ndarray.js [hunk 2]
```diff
@@ -48,7 +48,6 @@ var COL_MAJOR_REV_PIVOTS = require( './fixtures/column_major_reverse_pivots.json
 var COL_MAJOR_REV_PIVOTS_IPIV_STRIDE = require( './fixtures/column_major_reverse_pivots_ipiv_stride.json' ); // eslint-disable-line id-length
 var COL_MAJOR_REV_PIVOTS_IPIV_OFFSET = require( './fixtures/column_major_reverse_pivots_ipiv_offset.json' ); // eslint-disable-line id-length
 var COL_MAJOR_K1 = require( './fixtures/column_major_k1.json' );
-
```
Comment (kgryte) [inline lib/node_modules/@stdlib/lapack/base/claswp/test/test.ndarray.js:51]: This also isn't the desired change. Here we actually want the empty line in order to visually group related fixtures. The lint rule should have been disabled here.
