### PR TITLE
chore: fix EditorConfig lint errors (issue #7694)

### LINKED ISSUE #7694: Fix EditorConfig lint errors
## EditorConfig Linting Failures

Linting failures were detected in the automated EditorConfig lint workflow run.

### Workflow Details

- Run: https://github.com/stdlib-js/stdlib/actions/runs/16382593802
- Type: EditorConfig Linting
- Date: 2025-07-19 00:04:11 UTC

### Error Details

```
Linting files for basic formatting errors...
Downloading v3.3.0
lib/node_modules/@stdlib/utils/merge/examples/index.js:
	56-72: Wrong indentation type(spaces instead of tabs)

1 errors found
make: *** [/home/runner/work/stdlib/stdlib/tools/make/lib/lint/editorconfig.mk:90: lint-editorconfig-files] Error 1
```

### Pull Request Instructions

-   Please use the following PR title format:
"chore: fix EditorConfig lint errors (issue #<ISSUE_NUMBER>)".
-   Reference this issue in the "Related Issues" section of the PR body as "resolves #<ISSUE_NUMBER>".

### PR DESCRIPTION
**Pull request by satyajeetch1991**
Resolves #7694

## Description

This pull request fixes an EditorConfig linting error in the file:
`lib/node_modules/@stdlib/utils/merge/examples/index.js`

It replaces space-based indentation with tabs on lines 56–72, following the `.editorconfig` settings used across the stdlib codebase.

## Related Issues

- resolves #7694

## Questions

No questions.

## Other

N/A

## Checklist

- [x] Read, understood, and followed the [contributing guidelines][contributing].

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

### CODE REVIEW

File: lib/node_modules/@stdlib/utils/merge/examples/index.js [hunk 1]
```diff
@@ -53,21 +53,22 @@ var out = merge( {}, target, source );
...
-                'c3b': 5,
-                'c3c': 'bop'
-            },
-            'c4': 1337,
-            'c5': <Date>
-        },
-        'd': [ 4, 5, 6 ],
-        'e': true
-    }
+   {
```
Comment (kgryte) [inline lib/node_modules/@stdlib/utils/merge/examples/index.js]:
```suggestion
	{
```

File: lib/node_modules/@stdlib/utils/merge/examples/index.js [hunk 2]
```diff
@@ -53,21 +53,22 @@ var out = merge( {}, target, source );
...
+			'c3b': 5,
+			'c3c': 'bop'
+		},
+		'c4': 1337,
+		'c5': <Date>
+	},
+	'd': [ 4, 5, 6 ],
+	'e': true
+}
+
```
Comment (kgryte) [inline lib/node_modules/@stdlib/utils/merge/examples/index.js]:
```suggestion
```

File: etc/npm/deps.txt
Comment (kgryte) [inline etc/npm/deps.txt:1]: This file should not have been deleted.

Comment (kgryte) [reply etc/npm/deps.txt:1]: In order for this PR to move forward, this file will need to be restored.

**Review by kgryte — APPROVED** [review]
LGTM. Thank you for your contribution!

**Comment by kgryte** [comment]
As the test failure is unrelated to the changes introduced in this PR, I'll go ahead and merge.
