### PR TITLE
chore: fix Javascript lint errors (issue #10264)

### LINKED ISSUE #10264: Fix JavaScript lint errors
## JavaScript Linting Failures

  Linting failures were detected in the automated JavaScript lint workflow run.

  ### Workflow Details

  - Run: https://github.com/stdlib-js/stdlib/actions/runs/22007111944
  - Type: JavaScript Linting
  - Date: 2026-02-14 00:31:04 UTC

  ### Error Details
  ```
  make[1]: Entering directory '/home/runner/work/stdlib/stdlib'

Linting file: lib/node_modules/@stdlib/blas/base/ndarray/gdot/lib/index.js

Linting file: lib/node_modules/@stdlib/plot/ctor/lib/props/y/get.js

Linting file: lib/node_modules/@stdlib/blas/ext/base/wasm/dapx/lib/binary.js

Linting file: lib/node_modules/@stdlib/namespace/pkg2related/lib/index.js

Linting file: lib/node_modules/@stdlib/math/base/special/gammaincinv/lib/rational_ak5bk5.js

Linting file: lib/node_modules/@stdlib/stats/strided/scovarmtk/lib/main.js

Linting file: lib/node_modules/@stdlib/blas/base/wasm/srot/lib/main.js

Linting file: lib/node_modules/@stdlib/math/base/special/exp/lib/main.js

Linting file: lib/node_modules/@stdlib/math/strided/special/aversin-by/lib/index.js

Linting file: lib/node_modules/@stdlib/math/strided/ops/add/lib/data.js

Linting file: lib/node_modules/@stdlib/stats/base/dists/binomial/entropy/lib/main.js

Linting file: lib/node_modules/@stdlib/stats/strided/svariancetk/lib/main.js

Linting file: lib/node_modules/@stdlib/math/base/special/fast/uint32-log2/lib/native.js

Linting file: lib/node_modules/@stdlib/_tools/doctest/compare-values/lib/index.js

Linting file: lib/node_modules/@stdlib/stats/base/dists/triangular/quantile/lib/main.js

Linting file: lib/node_modules/@stdlib/stats/base/dists/beta/stdev/lib/index.js

Linting file: lib/node_modules/@stdlib/_tools/github/fetch-file/lib/factory.js

/home/runner/work/stdlib/stdlib/lib/node_modules/@stdlib/_tools/github/fetch-file/lib/factory.js
  75:3  error  Function 'done' should be moved to outer function scope  stdlib/no-unnecessary-nested-functions

✖ 1 problem (1 error, 0 warnings)

Linting failed.

Linting file: lib/node_modules/@stdlib/stats/base/dists/discrete-uniform/quantile/lib/main.js

Linting file: lib/node_modules/@stdlib/array/base/rekey/lib/main.js

Linting file: lib/node_modules/@stdlib/random/strided/arcsine/lib/main.js

Linting file: lib/node_modules/@stdlib/assert/is-same-type/lib/index.js

Linting file: lib/node_modules/@stdlib/ndarray/base/binary/lib/2d_blocked.js

Linting file: lib/node_modules/@stdlib/assert/is-unity-probability-array/lib/main.js

Linting file: lib/node_modules/@stdlib/ndarray/base/unary-by/lib/4d_blocked_accessors.js
make[1]: *** [/home/runner/work/stdlib/stdlib/tools/make/lib/lint/javascript/eslint.mk:261: eslint-files] Error 1
make[1]: Leaving directory '/home/runner/work/stdlib/stdlib'
make: *** [/home/runner/work/stdlib/stdlib/tools/make/lib/lint/javascript/Makefile:158: lint-javascript-files] Error 2
  ```

  ### Pull Request Instructions

  -   Please use the following PR title format:
  "chore: fix JavaScript lint errors (issue #<ISSUE_NUMBER>)".
  -   Reference this issue in the "Related Issues" section of the PR body as "resolves #<ISSUE_NUMBER>".

### PR DESCRIPTION
**Pull request by bhargava-d16**
---
type: pre_commit_static_analysis_report
description: Results of running static analysis checks when committing changes. report:
  - task: lint_filenames status: passed
  - task: lint_editorconfig status: passed
  - task: lint_markdown status: na
  - task: lint_package_json status: na
  - task: lint_repl_help status: na
  - task: lint_javascript_src status: passed
  - task: lint_javascript_cli status: na
  - task: lint_javascript_examples status: na
  - task: lint_javascript_tests status: na
  - task: lint_javascript_benchmarks status: na
  - task: lint_python status: na
  - task: lint_r status: na
  - task: lint_c_src status: na
  - task: lint_c_examples status: na
  - task: lint_c_benchmarks status: na
  - task: lint_c_tests_fixtures status: na
  - task: lint_shell status: na
  - task: lint_typescript_declarations status: passed
  - task: lint_typescript_tests status: na
  - task: lint_license_headers status: passed ---

Resolves #10264 

## Description

> What is the purpose of this pull request?

This pull request:

-   Fixes JavaScript lint errors by moving function `done` to outer function scope

## Related Issues

> Does this pull request have any related issues?

This pull request has the following related issues:

-   #10264 

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

### AI Assistance

> When authoring the changes proposed in this PR, did you use any kind of AI assistance?

-   [ ] Yes
-   [x] No

If you answered "yes" above, how did you use AI assistance?

-   [ ] Code generation (e.g., when writing an implementation or fixing a bug)
-   [ ] Test/benchmark generation
-   [ ] Documentation (including examples)
-   [ ] Research and understanding

#### Disclosure

> If you answered "yes" to using AI assistance, please provide a short disclosure indicating how you used AI assistance. This helps reviewers determine how much scrutiny to apply when reviewing your contribution. Example disclosures: "This PR was written primarily by Claude Code." or "I consulted ChatGPT to understand the codebase, but the proposed changes were fully authored manually by myself.".

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

### CODE REVIEW

File: lib/node_modules/@stdlib/_tools/github/fetch-file/lib/factory.js [hunk 1]
```diff
@@ -57,27 +57,28 @@ function factory( filepath, repos, clbk ) {
...
-	function fetchFile() {
-		resolve( filepath, repos, opts, done );
-		/**
 		* Callback invoked after query completion.
 		*
 		* @private
 		* @param {(Error|null)} error - error object
 		* @param {Object} results - query results
 		* @returns {void}
 		*/
```
Comment (Planeshifter) [inline lib/node_modules/@stdlib/_tools/github/fetch-file/lib/factory.js]: The JSDoc comment body for `done` still has the old two-tab indentation from when it was nested inside `fetchFile`. Now that it's been hoisted to the outer scope, the comment lines should use single-tab indentation to match `fetchFile`'s JSDoc right below it.

```suggestion
	/**
	* Callback invoked after query completion.
	*
	* @private
	* @param {(Error|null)} error - error object
	* @param {Object} results - query results
	* @returns {void}
	*/
```

**Comment by Planeshifter** [comment]
Thanks for the contribution! The functional change looks correct -- hoisting `done` to the outer `factory` scope fixes the `stdlib/no-unnecessary-nested-functions` lint error.

Two things to address:

1. **JSDoc indentation**: The JSDoc comment for `done` still uses the old double-tab indentation from when it was nested inside `fetchFile`. Since `done` is now at the same scope level as `fetchFile`, its JSDoc should use single-tab indentation to match. See the inline comment for a suggestion.

2. **PR title / commit message**: The issue instructions specify `"chore: fix JavaScript lint errors (issue #)"` but the title uses "Javascript" (lowercase 's'). Please update to "JavaScript" (capital 'S') to match the proper name of the language.

**Comment by bhargava-d16** [comment]
@Planeshifter I have made the requested changes. Please let me know if there are any further changes to be made

**Review by Planeshifter — APPROVED** [review]
