### PR TITLE
chore: fix C lint errors (issue #8156)

### LINKED ISSUE #8156: Fix C lint errors
## C Linting Failures

Linting failures were detected in the automated lint workflow run.

### Workflow Details

-   Run: https://github.com/stdlib-js/stdlib/actions/runs/18081635227
-   Type: C Linting
-   Date: 2025-09-29 00:21:37 UTC

### Error Details

```
lib/node_modules/@stdlib/ndarray/base/assert/is-single-segment-compatible/src/main.c:52:126: style: Parameter 'strides' can be declared as pointer to const [constParameterPointer]
int8_t stdlib_ndarray_is_single_segment_compatible( enum STDLIB_NDARRAY_DTYPE dtype, int64_t ndims, int64_t *shape, int64_t *strides, int64_t offset ) {
                                                                                                                             ^
```

### Pull Request Instructions

-   Please use the following PR title format:
"chore: fix C lint errors (issue #<ISSUE_NUMBER>)".
-   Reference this issue in the "Related Issues" section of the PR body as "resolves #<ISSUE_NUMBER>".

### PR DESCRIPTION
**Pull request by GeoDaoyu**
Resolves #8156.

## Description

> What is the purpose of this pull request?

This pull request:

-   fix C lint errors

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves #8156

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

### CODE REVIEW

File: lib/node_modules/@stdlib/ndarray/base/assert/is-single-segment-compatible/src/main.c [hunk 1]
```diff
@@ -49,7 +49,7 @@
 * int8_t b = stdlib_ndarray_is_single_segment_compatible( STDLIB_NDARRAY_UINT8, ndims, shape, strides, offset );
 * // returns 1
 */
-int8_t stdlib_ndarray_is_single_segment_compatible( enum STDLIB_NDARRAY_DTYPE dtype, int64_t ndims, int64_t *shape, int64_t *strides, int64_t offset ) {
+int8_t stdlib_ndarray_is_single_segment_compatible( enum STDLIB_NDARRAY_DTYPE dtype, int64_t ndims, int64_t *shape, const int64_t *strides, int64_t offset ) {
```
Comment (kgryte) [inline lib/node_modules/@stdlib/ndarray/base/assert/is-single-segment-compatible/src/main.c]: @GeoDaoyu In general, for changes such as this, you also need to update the header file and the README (if the function signature is documented there).

**Review by kgryte — APPROVED** [review]
LGTM after making some more general changes.
