### PR TITLE
chore: fix C lint errors (issue #7676)

### LINKED ISSUE #7676: Fix C lint errors
## C Linting Failures

Linting failures were detected in the automated lint workflow run.

### Workflow Details

-   Run: https://github.com/stdlib-js/stdlib/actions/runs/16306961195
-   Type: C Linting
-   Date: 2025-07-16 00:15:15 UTC

### Error Details

```

lib/node_modules/@stdlib/stats/base/snanstdevyc/examples/c/example.c:25:8: style: Variable 'x' can be declared as const array [constVariable]
 float x[] = { 1.0, 2.0, 0.0/0.0, 3.0, 0.0/0.0, 4.0, 5.0, 6.0, 0.0/0.0, 7.0, 8.0, 0.0/0.0 };
       ^
```

### Pull Request Instructions

-   Please use the following PR title format:
"chore: fix C lint errors (issue #<ISSUE_NUMBER>)".
-   Reference this issue in the "Related Issues" section of the PR body as "resolves #<ISSUE_NUMBER>".

### PR DESCRIPTION
**Pull request by GeoDaoyu**
Resolves #7676.

## Description

> What is the purpose of this pull request?

This pull request:

-   fix C lint errors

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves #7676

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

### CODE REVIEW

File: lib/node_modules/@stdlib/stats/base/snanstdevyc/examples/c/example.c [hunk 1]
```diff
@@ -22,7 +22,7 @@
 
 int main( void ) {
 	// Create a strided array:
-	float x[] = { 1.0, 2.0, 0.0/0.0, 3.0, 0.0/0.0, 4.0, 5.0, 6.0, 0.0/0.0, 7.0, 8.0, 0.0/0.0 };
+	const float x[] = { 1.0, 2.0, 0.0/0.0, 3.0, 0.0/0.0, 4.0, 5.0, 6.0, 0.0/0.0, 7.0, 8.0, 0.0/0.0 };
```
Comment (kgryte) [inline lib/node_modules/@stdlib/stats/base/snanstdevyc/examples/c/example.c]: @GeoDaoyu Would you mind also making this change in the README where it is also applicable?

Comment (kgryte) [inline lib/node_modules/@stdlib/stats/base/snanstdevyc/examples/c/example.c]:
```suggestion
	const float x[] = { 1.0f, 2.0f, 0.0f/0.0f, 3.0f, 0.0f/0.0f, 4.0f, 5.0f, 6.0f, 0.0f/0.0f, 7.0f, 8.0f, 0.0f/0.0f };
```

Comment (GeoDaoyu) [reply lib/node_modules/@stdlib/stats/base/snanstdevyc/examples/c/example.c]: Do you mean lib/node_modules/@stdlib/stats/base/snanstdevyc/README.md ?
There are javascript code, using `var`.
I dont know how to fix, could you tell me?
add 'f' to every Float32Array, like this?
``` js
- var x = new Float32Array( [ 2.0, 1.0, 2.0, -2.0, -2.0, 2.0, 3.0, 4.0 ] );
+ var x = new Float32Array( [ 2.0f, 1.0f, 2.0f, -2.0f, -2.0f, 2.0f, 3.0f, 4.0f ] );
```

Comment (kgryte) [reply lib/node_modules/@stdlib/stats/base/snanstdevyc/examples/c/example.c]: Ah, nevermind. I see that the C APIs are missing from the documentation. This PR is good as is.

**Review by kgryte — APPROVED** [review]
