### PR TITLE
chore: fix JavaScript lint errors

### LINKED ISSUE #5502: Fix JavaScript lint errors
## JavaScript Linting Failures

Linting failures were detected in the automated JavaScript lint workflow run.

### Workflow Details

- Run: https://github.com/stdlib-js/stdlib/actions/runs/13578266709
- Type: JavaScript Linting
- Date: 2025-02-28 00:09:11 UTC

### Error Details
```
make[1]: Entering directory '/home/runner/work/stdlib/stdlib'

Linting file: lib/node_modules/@stdlib/stats/base/dists/beta/mean/lib/main.js

Linting file: lib/node_modules/@stdlib/math/base/special/cabs2f/lib/main.js

Linting file: lib/node_modules/@stdlib/assert/is-node-duplex-stream-like/lib/main.js

Linting file: lib/node_modules/@stdlib/ndarray/base/unary-accumulate/lib/9d.js

Linting file: lib/node_modules/@stdlib/math/base/special/trigamma/lib/rational_p12q12.js

Linting file: lib/node_modules/@stdlib/_tools/github/get/lib/cache.js

/home/runner/work/stdlib/stdlib/lib/node_modules/@stdlib/_tools/github/get/lib/cache.js
  31:9  error  Using the `new Array()` constructor is not allowed; use an array literal with push instead  stdlib/no-new-array

✖ 1 problem (1 error, 0 warnings)

Linting failed.

Linting file: lib/node_modules/@stdlib/assert/is-undefined-or-null/lib/main.js

Linting file: lib/node_modules/@stdlib/blas/base/ssymv/lib/index.js

Linting file: lib/node_modules/@stdlib/blas/base/sspr/lib/native.js

Linting file: lib/node_modules/@stdlib/lapack/base/dlacpy/lib/index.js

Linting file: lib/node_modules/@stdlib/stats/strided/dminabs/lib/main.js

Linting file: lib/node_modules/@stdlib/random/base/binomial/lib/validate.js

Linting file: lib/node_modules/@stdlib/ndarray/base/assert/is-safe-data-type-cast/lib/main.js

Linting file: lib/node_modules/@stdlib/repl/lib/set_aliases.js

Linting file: lib/node_modules/@stdlib/stats/base/dsvariance/lib/main.js

Linting file: lib/node_modules/@stdlib/stats/base/dists/truncated-normal/lib/index.js

Linting file: lib/node_modules/@stdlib/_tools/pkgs/browser-entry-points/lib/sync.js

/home/runner/work/stdlib/stdlib/lib/node_modules/@stdlib/_tools/pkgs/browser-entry-points/lib/sync.js
  42:1  error  Encountered an error while running code: `Cannot find module '/foo/bar/baz' from '/home/runner/work/stdlib/stdlib'`.Did you mean to include a `// throws <Error>` annotation instead of `// returns [{...}]`?  stdlib/jsdoc-doctest

✖ 1 problem (1 error, 0 warnings)
  1 error and 0 warnings potentially fixable with the `--fix` option.

Linting failed.

Linting file: lib/node_modules/@stdlib/utils/async/try-then/lib/index.js

Linting file: lib/node_modules/@stdlib/_tools/eslint/rules/uppercase-required-constants/lib/index.js

Linting file: lib/node_modules/@stdlib/strided/napi/cmap/lib/main.js

Linting file: lib/node_modules/@stdlib/stats/base/dnanmskrange/lib/main.js

Linting file: lib/node_modules/@stdlib/math/base/special/binomcoef/lib/index.js

Linting file: lib/node_modules/@stdlib/utils/group-own/lib/index.js
make[1]: *** [/home/runner/work/stdlib/stdlib/tools/make/lib/lint/javascript/eslint.mk:255: eslint-files] Error 1
make[1]: Leaving directory '/home/runner/work/stdlib/stdlib'
make: *** [/home/runner/work/stdlib/stdlib/tools/make/lib/lint/javascript/Makefile:158: lint-javascript-files] Error 2
```

### PR DESCRIPTION
**Pull request by jalajk3004**
Resolves  #5502 

## Description

> What is the purpose of this pull request?

This pull request:

-   This PR make sure that it avoids the javascript linting errors

1. It doesn't use the constructor `new Array()`
2. Fix JSDoc doctest linting issue in sync.js

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves #5502 

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

### CODE REVIEW

**Comment by jalajk3004** [comment]
@stdlib-bot please review this PR

File: lib/node_modules/@stdlib/_tools/github/get/lib/cache.js [hunk 1]
```diff
@@ -28,10 +28,13 @@
 * @returns {Array} cache
 */
 function create( size ) {
-	return new Array( size );
+	const cache = [];
```
Comment (kgryte) [inline lib/node_modules/@stdlib/_tools/github/get/lib/cache.js]: a) We use ES5. b) Initialize with `null`. c) Use TAB indentation.

File: lib/node_modules/@stdlib/_tools/github/get/lib/cache.js [hunk 2]
```diff
@@ -28,10 +28,13 @@
...
+    for (let i = 0; i < size; i++) {
+        cache.push(undefined);
+    }
+    return cache;
 }
 
-
```
Comment (kgryte) [inline lib/node_modules/@stdlib/_tools/github/get/lib/cache.js:34]: Revert this change.

File: lib/node_modules/@stdlib/_tools/pkgs/browser-entry-points/lib/sync.js [hunk 3]
```diff
@@ -55,7 +55,7 @@ var debug = logger( 'browser-entry-points:sync' );
 * var pkgs = [ '/foo/bar/baz' ];
 *
 * var entries = entryPoints( pkgs );
-* // returns [{...}]
+* // throws <Error>
```
Comment (kgryte) [inline lib/node_modules/@stdlib/_tools/pkgs/browser-entry-points/lib/sync.js]: This isn't what we want. Instead, do `// e.g., returns [{...}]`

**Review by Planeshifter — APPROVED** [review]
