### PR TITLE
chore: fix JavaScript lint errors (issue #11123)

### LINKED ISSUE #11123: Fix JavaScript lint errors
## JavaScript Linting Failures

  Linting failures were detected in the automated JavaScript lint workflow run.

  ### Workflow Details

  - Run: https://github.com/stdlib-js/stdlib/actions/runs/23518257863
  - Type: JavaScript Linting
  - Date: 2026-03-25 00:16:25 UTC

  ### Error Details
  ```
  make[1]: Entering directory '/home/runner/work/stdlib/stdlib'

Linting file: lib/node_modules/@stdlib/stats/base/ndarray/snanmidrange/lib/main.js

Linting file: lib/node_modules/@stdlib/ndarray/base/remove-singleton-dimensions/lib/index.js

Linting file: lib/node_modules/@stdlib/stats/nanminabs/lib/index.js

Linting file: lib/node_modules/@stdlib/_tools/eslint/rules/jsdoc-markdown-remark/lib/main.js

Linting file: lib/node_modules/@stdlib/ndarray/base/unary-accumulate/lib/8d_accessors.js

Linting file: lib/node_modules/@stdlib/ndarray/base/clamp-index/lib/index.js

Linting file: lib/node_modules/@stdlib/math/iter/special/hacovercos/lib/main.js

Linting file: lib/node_modules/@stdlib/random/base/negative-binomial/lib/validate.js

Linting file: lib/node_modules/@stdlib/utils/global/lib/browser.js

Linting file: lib/node_modules/@stdlib/utils/async/function-sequence/lib/main.js

/home/runner/work/stdlib/stdlib/lib/node_modules/@stdlib/utils/async/function-sequence/lib/main.js
   79:6   error  Using the `new Array()` constructor is not allowed; use an array literal with push instead  stdlib/no-new-array
  104:10  error  Using the `new Array()` constructor is not allowed; use an array literal with push instead  stdlib/no-new-array

✖ 2 problems (2 errors, 0 warnings)

Linting failed.

Linting file: lib/node_modules/@stdlib/stats/strided/mskmidrange/lib/main.js

Linting file: lib/node_modules/@stdlib/_tools/markdown/img-svg-equation/lib/validate.js

Linting file: lib/node_modules/@stdlib/blas/base/gswap/lib/ndarray.js

Linting file: lib/node_modules/@stdlib/math/iter/tools/map2/lib/index.js

Linting file: lib/node_modules/@stdlib/stats/incr/mda/lib/index.js

Linting file: lib/node_modules/@stdlib/datasets/berndt-cps-wages-1985/lib/browser.js

Linting file: lib/node_modules/@stdlib/stats/strided/dnanmax/lib/main.js

Linting file: lib/node_modules/@stdlib/ndarray/base/flatten-shape-from/lib/index.js

Linting file: lib/node_modules/@stdlib/strided/napi/mskunary/lib/native.js

Linting file: lib/node_modules/@stdlib/blas/ext/base/zfill/lib/index.js

Linting file: lib/node_modules/@stdlib/math/iter/sequences/positive-even-integers/lib/main.js

Linting file: lib/node_modules/@stdlib/repl/lib/settings_validators.js

Linting file: lib/node_modules/@stdlib/plot/components/svg/path/lib/render/utils/style.js
make[1]: *** [/home/runner/work/stdlib/stdlib/tools/make/lib/lint/javascript/eslint.mk:261: eslint-files] Error 1
make[1]: Leaving directory '/home/runner/work/stdlib/stdlib'
make: *** [/home/runner/work/stdlib/stdlib/tools/make/lib/lint/javascript/Makefile:158: lint-javascript-files] Error 2
  ```

  ### Pull Request Instructions

  -   Please use the following PR title format:
  "chore: fix JavaScript lint errors (issue #<ISSUE_NUMBER>)".
  -   Reference this issue in the "Related Issues" section of the PR body as "resolves #<ISSUE_NUMBER>".

### PR DESCRIPTION
**Pull request by Sran012**
Resolves #11123 

## Description

> What is the purpose of this pull request?

This pull request:

-   Fixes JavaScript lint errors by replacing `new Array()` usage with array literals.  

## Related Issues

> Does this pull request have any related issues?

This pull request has the following related issues:

-   #11123 

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

### AI Assistance

> When authoring the changes proposed in this PR, did you use any kind of AI assistance?

-   [ ] Yes
-   [x] No

If you answered "yes" above, how did you use AI assistance?

-   [ ] Code generation (e.g., when writing an implementation or fixing a bug)
-   [ ] Test/benchmark generation
-   [ ] Documentation (including examples)
-   [ ] Research and understanding

#### Disclosure

> If you answered "yes" to using AI assistance, please provide a short disclosure indicating how you used AI assistance. This helps reviewers determine how much scrutiny to apply when reviewing your contribution. Example disclosures: "This PR was written primarily by Claude Code." or "I consulted ChatGPT to understand the codebase, but the proposed changes were fully authored manually by myself.".

{{TODO: add disclosure if applicable}}

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

### CODE REVIEW

**Review by kgryte — DISMISSED** [review]

File: lib/node_modules/@stdlib/utils/async/function-sequence/lib/main.js [hunk 1]
```diff
@@ -72,13 +72,14 @@ function funseqAsync() {
 	var nFuncs;
 	var f;
 	var i;
+
```
Comment (kgryte) [inline lib/node_modules/@stdlib/utils/async/function-sequence/lib/main.js]:
```suggestion

```

**Review by kgryte — APPROVED** [review]
