### PR TITLE
chore: fix JavaScript lint errors (issue #7031)

### LINKED ISSUE #7031: Fix JavaScript lint errors
## JavaScript Linting Failures

  Linting failures were detected in the automated JavaScript lint workflow run.

  ### Workflow Details

  - Run: https://github.com/stdlib-js/stdlib/actions/runs/15101367358
  - Type: JavaScript Linting
  - Date: 2025-05-19 00:09:13 UTC

  ### Error Details
  ```
  make[1]: Entering directory '/home/runner/work/stdlib/stdlib'

Linting file: lib/node_modules/@stdlib/ndarray/ctor/lib/set.js

Linting file: lib/node_modules/@stdlib/math/base/special/gammainc/lib/finite_gamma_q.js

Linting file: lib/node_modules/@stdlib/regexp/filename/lib/index.js

Linting file: lib/node_modules/@stdlib/stats/strided/smax/lib/native.js

Linting file: lib/node_modules/@stdlib/math/base/special/lucasf/lib/native.js

Linting file: lib/node_modules/@stdlib/namespace/lib/namespace/base/strided/q.js

Linting file: lib/node_modules/@stdlib/_tools/makie/plugins/makie-list-pkgs/lib/index.js

/home/runner/work/stdlib/stdlib/lib/node_modules/@stdlib/_tools/makie/plugins/makie-list-pkgs/lib/index.js
  21:1   error    Example code of main export should require itself last, i.e. contain `require( '@stdlib/_tools/makie/plugins/makie-list-pkgs' )` as the last `require` call  stdlib/jsdoc-main-export
  24:26  warning  Unknown word: "makie"                                                                                                                                        @cspell/spellchecker
  24:40  warning  Unknown word: "makie"                                                                                                                                        @cspell/spellchecker

✖ 3 problems (1 error, 2 warnings)

Linting failed.

Linting file: lib/node_modules/@stdlib/plot/components/svg/path/lib/props/opacity/get.js

Linting file: lib/node_modules/@stdlib/fs/close/lib/main.js

Linting file: lib/node_modules/@stdlib/blas/ext/base/srev/lib/ndarray.js

Linting file: lib/node_modules/@stdlib/_tools/markdown/inline-svg-equation/lib/index.js

/home/runner/work/stdlib/stdlib/lib/node_modules/@stdlib/_tools/markdown/inline-svg-equation/lib/index.js
  32:84  warning  Unknown word: "mathrm"  @cspell/spellchecker

✖ 1 problem (0 errors, 1 warning)


Linting file: lib/node_modules/@stdlib/array/base/zeros5d/lib/main.js

Linting file: lib/node_modules/@stdlib/stats/strided/dminsorted/lib/index.js

Linting file: lib/node_modules/@stdlib/_tools/eslint/rules/jsdoc-no-missing-blank-lines/lib/index.js

Linting file: lib/node_modules/@stdlib/number/float64/base/get-low-word/lib/low.js

Linting file: lib/node_modules/@stdlib/plot/components/svg/graph/lib/props/auto-render/get.js

Linting file: lib/node_modules/@stdlib/math/base/special/dirac-delta/lib/index.js

Linting file: lib/node_modules/@stdlib/datasets/month-names-en/lib/main.js

Linting file: lib/node_modules/@stdlib/math/base/special/hyp2f1/lib/hys2f1.js

Linting file: lib/node_modules/@stdlib/ml/incr/lib/index.js
make[1]: *** [/home/runner/work/stdlib/stdlib/tools/make/lib/lint/javascript/eslint.mk:255: eslint-files] Error 1
make[1]: Leaving directory '/home/runner/work/stdlib/stdlib'
make: *** [/home/runner/work/stdlib/stdlib/tools/make/lib/lint/javascript/Makefile:158: lint-javascript-files] Error 2
  ```

  ### Pull Request Instructions

  -   Please use the following PR title format:
  "chore: fix JavaScript lint errors (issue #<ISSUE_NUMBER>)".
  -   Reference this issue in the "Related Issues" section of the PR body as "resolves #<ISSUE_NUMBER>".

### PR DESCRIPTION
**Pull request by schnrj**
Resolves #7031.

## Description

> What is the purpose of this pull request?

This pull request:

-   Fixes JavaScript lint errors in lib/node_modules/@stdlib/_tools/makie/plugins/makie-list-pkgs/lib/index.js by:

                Correcting the order of require statements in the JSDoc example to comply with the stdlib/jsdoc-main-export rule.

                Adding project-specific words ("makie" and "mathrm") to the spellchecker allowlist to resolve related warnings.

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves #7031

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

### CODE REVIEW

**Comment by schnrj** [comment]
@Planeshifter All checks have passed. This PR is ready for review. Thank you!

File: lib/node_modules/@stdlib/_tools/makie/plugins/makie-list-pkgs/lib/index.js [hunk 1]
```diff
@@ -36,6 +36,7 @@
 * makie( '/home/stdlib-js/stdlib', opts, 'benchmark' );
 */
 
+
```
Comment (kgryte) [inline lib/node_modules/@stdlib/_tools/makie/plugins/makie-list-pkgs/lib/index.js]:
```suggestion
```

File: lib/node_modules/@stdlib/_tools/makie/plugins/makie-list-pkgs/lib/index.js [hunk 2]
```diff
@@ -24,8 +24,8 @@
 * @module @stdlib/_tools/makie/plugins/makie-list-pkgs
 *
 * @example
-* var plugin = require( '@stdlib/_tools/makie/plugins/makie-list-pkgs' );
 * var makie = require( '@stdlib/_tools/makie' );
+* var plugin = require( '@stdlib/_tools/makie/plugins/makie-list-pkgs' );
```
Comment (kgryte) [inline lib/node_modules/@stdlib/_tools/makie/plugins/makie-list-pkgs/lib/index.js:28]:
```suggestion
* var plugin = require( '@stdlib/_tools/makie/plugins/makie-list-pkgs' );
*
```

**Review by kgryte — APPROVED** [review]
LGTM after clean-up.

**Comment by schnrj** [comment]
@kgryte  Thanks for reviewing and merging it. Looking forward to contributing more.
