### PR TITLE
fix: `example` command hanging in REPL when executing multi-line code

### LINKED ISSUE #2273: `example` command hanging in REPL when executing multi-line code
### Description

Encountered an error when trying to run `example( <alias> )` in the REPL, which runs the example code from the respective package's `repl.txt` file. The error seems to occur when the example code spans multiple lines.

### Related Issues

None.

### Questions

No.

### Demo

_No response_

### Reproduction

```shell
- `make repl` to start the REPL from the top-level directory
- `example( ttest )` to run the example code for the Student's t test
```

### Expected Results

```shell
All example code in https://github.com/stdlib-js/stdlib/blob/develop/lib/node_modules/%40stdlib/stats/ttest/docs/repl.txt should be printed.
```

### Actual Results

```shell
In [1]: example(ttest)

In [2]: var rnorm = base.random.normal.factory( 0.0, 2.0, { 'seed': 5776 } );

In [3]: var x = new Array( 100 );

In [4]: for ( var i = 0; i < x.length; i++ ) {
```

### Version

0.2.0

### Environments

Node.js

### Browser Version

_No response_

### Node.js / npm Version

_No response_

### Platform

_No response_

### Checklist

- [X] Read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.

### PR DESCRIPTION
**Pull request by Snehil-Shah**
Resolves #2273.

## Description

> What is the purpose of this pull request?

This pull request:

-   fixes `example` command hanging with multiline code blocks. The command was waiting for `drain` events after every line, instead it should be waiting for events after every *command block*

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves #2273 

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

The example code is also not syntactically highlighted. I will fix this in a separate PR.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

### CODE REVIEW

File: lib/node_modules/@stdlib/repl/lib/commands/example.js [hunk 1]
```diff
@@ -149,13 +151,28 @@ function command( repl, cmds ) {
...
 				// Forward the next line to the REPL readline interface in order to mimic user input...
 				if ( out[ i ] ) {
-					repl._rli.write( out[ i ]+'\n' );
+					lines.push( out[ i ] );
+
+					// If line is part of a multi-line input, wait for the next line...
+					if ( repl._multilineHandler.isMultilineInput( lines.join( '\n' ) ) ) {
+						return next();
+					}
+					// repl._multilineHandler.enablePasting();
```
Comment (kgryte) [inline lib/node_modules/@stdlib/repl/lib/commands/example.js]: @Snehil-Shah Should this line be here?

Comment (Snehil-Shah) [reply lib/node_modules/@stdlib/repl/lib/commands/example.js]: It shouldn't. Thanks for catching it!

**Review by Planeshifter — APPROVED** [review]
Looks fine and seems to work as expected. Thanks @Snehil-Shah!
