### PR TITLE
chore: fix EditorConfig lint errors (issue #8168)

### LINKED ISSUE #8168: Fix EditorConfig lint errors
## EditorConfig Linting Failures

Linting failures were detected in the automated EditorConfig lint workflow run.

### Workflow Details

- Run: https://github.com/stdlib-js/stdlib/actions/runs/18146741745
- Type: EditorConfig Linting
- Date: 2025-10-01 00:04:31 UTC

### Error Details

```
Linting files for basic formatting errors...
Downloading v3.4.0
lib/node_modules/@stdlib/stats/base/dists/cosine/mode/src/main.c:
	34: Trailing whitespace

1 errors found
make: *** [/home/runner/work/stdlib/stdlib/tools/make/lib/lint/editorconfig.mk:90: lint-editorconfig-files] Error 1
```

### Pull Request Instructions

-   Please use the following PR title format:
"chore: fix EditorConfig lint errors (issue #<ISSUE_NUMBER>)".
-   Reference this issue in the "Related Issues" section of the PR body as "resolves #<ISSUE_NUMBER>".

### PR DESCRIPTION
**Pull request by navyansh007**
resolves #8168

-   [x] Read, understood, and followed the [contributing guidelines](https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md)

### CODE REVIEW

File: tools/snippets/test/fixtures/julia/runner.jl [hunk 1]
```diff
@@ -19,7 +19,7 @@
 import JSON
 
 """
-    gen( x, name )
+	gen( x, name )
```
Comment (Planeshifter) [inline tools/snippets/test/fixtures/julia/runner.jl]: let's revert this change unrelated to the addressed issue.

```suggestion
    gen( x, name )
```

**Review by Planeshifter — APPROVED** [review]
Thanks for your first contribution to the project!
