### PR TITLE
chore: fix C lint errors (issue #8136)

### LINKED ISSUE #8136: Fix C lint errors
## C Linting Failures

Linting failures were detected in the automated lint workflow run.

### Workflow Details

-   Run: https://github.com/stdlib-js/stdlib/actions/runs/17962160131
-   Type: C Linting
-   Date: 2025-09-24 00:17:38 UTC

### Error Details

```

lib/node_modules/@stdlib/number/float32/base/significand/examples/c/example.c:25:8: style: Variable 'x' can be declared as const array [constVariable]
 float x[] = { 4.0f, 0.0f, -0.0f, 1.0f, -1.0f, 3.14f, -3.14f, 1.0e38f, -1.0e38f, 1.0f/0.0f, -1.0f/0.0f, 0.0f/0.0f };
       ^
```

### Pull Request Instructions

-   Please use the following PR title format:
"chore: fix C lint errors (issue #<ISSUE_NUMBER>)".
-   Reference this issue in the "Related Issues" section of the PR body as "resolves #<ISSUE_NUMBER>".

### PR DESCRIPTION
**Pull request by GeoDaoyu**
Resolves #8136.

## Description

> What is the purpose of this pull request?

This pull request:

-   fix C lint errors

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves #8136

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

### CODE REVIEW

File: lib/node_modules/@stdlib/number/float32/base/significand/examples/c/example.c [hunk 1]
```diff
@@ -22,7 +22,7 @@
 #include <inttypes.h>
 
 int main( void ) {
-	float x[] = { 4.0f, 0.0f, -0.0f, 1.0f, -1.0f, 3.14f, -3.14f, 1.0e38f, -1.0e38f, 1.0f/0.0f, -1.0f/0.0f, 0.0f/0.0f };
+	const float x[] = { 4.0f, 0.0f, -0.0f, 1.0f, -1.0f, 3.14f, -3.14f, 1.0e38f, -1.0e38f, 1.0f/0.0f, -1.0f/0.0f, 0.0f/0.0f };
```
Comment (kgryte) [inline lib/node_modules/@stdlib/number/float32/base/significand/examples/c/example.c:25]: @GeoDaoyu Would you mind also making this change in the README where this example can also be found? Cheers!

Comment (GeoDaoyu) [reply lib/node_modules/@stdlib/number/float32/base/significand/examples/c/example.c:25]: Sure, I has fixed it in README.

**Review by kgryte — APPROVED** [review]
