### PR TITLE
chore: fix C lint errors (issue #11462)

### LINKED ISSUE #11462: Fix C lint errors
## C Linting Failures

Linting failures were detected in the automated lint workflow run.

### Workflow Details

-   Run: https://github.com/stdlib-js/stdlib/actions/runs/24429471817
-   Type: C Linting
-   Date: 2026-04-15 00:39:05 UTC

### Error Details

```
lib/node_modules/@stdlib/strided/common/src/quinary.c:108:58: style: Parameter 'shape' can be declared as pointer to const [constParameterPointer]
void stdlib_strided_ddddd_d( uint8_t *arrays[], int64_t *shape, int64_t *strides, void *fcn ) {
                                                         ^
lib/node_modules/@stdlib/strided/common/src/quinary.c:108:74: style: Parameter 'strides' can be declared as pointer to const [constParameterPointer]
void stdlib_strided_ddddd_d( uint8_t *arrays[], int64_t *shape, int64_t *strides, void *fcn ) {
                                                                         ^
lib/node_modules/@stdlib/strided/common/src/quinary.c:150:58: style: Parameter 'shape' can be declared as pointer to const [constParameterPointer]
void stdlib_strided_fffff_f( uint8_t *arrays[], int64_t *shape, int64_t *strides, void *fcn ) {
                                                         ^
lib/node_modules/@stdlib/strided/common/src/quinary.c:150:74: style: Parameter 'strides' can be declared as pointer to const [constParameterPointer]
void stdlib_strided_fffff_f( uint8_t *arrays[], int64_t *shape, int64_t *strides, void *fcn ) {
                                                                         ^
lib/node_modules/@stdlib/strided/common/src/quinary.c:192:69: style: Parameter 'shape' can be declared as pointer to const [constParameterPointer]
void stdlib_strided_fffff_f_as_ddddd_d( uint8_t *arrays[], int64_t *shape, int64_t *strides, void *fcn ) {
                                                                    ^
lib/node_modules/@stdlib/strided/common/src/quinary.c:192:85: style: Parameter 'strides' can be declared as pointer to const [constParameterPointer]
void stdlib_strided_fffff_f_as_ddddd_d( uint8_t *arrays[], int64_t *shape, int64_t *strides, void *fcn ) {
                                                                                    ^
lib/node_modules/@stdlib/strided/common/src/quinary.c:234:58: style: Parameter 'shape' can be declared as pointer to const [constParameterPointer]
void stdlib_strided_IIIII_I( uint8_t *arrays[], int64_t *shape, int64_t *strides, void *fcn ) {
                                                         ^
lib/node_modules/@stdlib/strided/common/src/quinary.c:234:74: style: Parameter 'strides' can be declared as pointer to const [constParameterPointer]
void stdlib_strided_IIIII_I( uint8_t *arrays[], int64_t *shape, int64_t *strides, void *fcn ) {
                                                                         ^
lib/node_modules/@stdlib/strided/common/src/quinary.c:276:58: style: Parameter 'shape' can be declared as pointer to const [constParameterPointer]
void stdlib_strided_iiiii_i( uint8_t *arrays[], int64_t *shape, int64_t *strides, void *fcn ) {
                                                         ^
lib/node_modules/@stdlib/strided/common/src/quinary.c:276:74: style: Parameter 'strides' can be declared as pointer to const [constParameterPointer]
void stdlib_strided_iiiii_i( uint8_t *arrays[], int64_t *shape, int64_t *strides, void *fcn ) {
                                                                         ^
lib/node_modules/@stdlib/strided/common/src/quinary.c:318:58: style: Parameter 'shape' can be declared as pointer to const [constParameterPointer]
void stdlib_strided_HHHHH_H( uint8_t *arrays[], int64_t *shape, int64_t *strides, void *fcn ) {
                                                         ^
lib/node_modules/@stdlib/strided/common/src/quinary.c:318:74: style: Parameter 'strides' can be declared as pointer to const [constParameterPointer]
void stdlib_strided_HHHHH_H( uint8_t *arrays[], int64_t *shape, int64_t *strides, void *fcn ) {
                                                                         ^
lib/node_modules/@stdlib/strided/common/src/quinary.c:360:58: style: Parameter 'shape' can be declared as pointer to const [constParameterPointer]
void stdlib_strided_hhhhh_h( uint8_t *arrays[], int64_t *shape, int64_t *strides, void *fcn ) {
                                                         ^
lib/node_modules/@stdlib/strided/common/src/quinary.c:360:74: style: Parameter 'strides' can be declared as pointer to const [constParameterPointer]
void stdlib_strided_hhhhh_h( uint8_t *arrays[], int64_t *shape, int64_t *strides, void *fcn ) {
                                                                         ^
lib/node_modules/@stdlib/strided/common/src/quinary.c:402:58: style: Parameter 'shape' can be declared as pointer to const [constParameterPointer]
void stdlib_strided_BBBBB_B( uint8_t *arrays[], int64_t *shape, int64_t *strides, void *fcn ) {
                                                         ^
lib/node_modules/@stdlib/strided/common/src/quinary.c:402:74: style: Parameter 'strides' can be declared as pointer to const [constParameterPointer]
void stdlib_strided_BBBBB_B( uint8_t *arrays[], int64_t *shape, int64_t *strides, void *fcn ) {
                                                                         ^
lib/node_modules/@stdlib/strided/common/src/quinary.c:444:58: style: Parameter 'shape' can be declared as pointer to const [constParameterPointer]
void stdlib_strided_bbbbb_b( uint8_t *arrays[], int64_t *shape, int64_t *strides, void *fcn ) {
                                                         ^
lib/node_modules/@stdlib/strided/common/src/quinary.c:444:74: style: Parameter 'strides' can be declared as pointer to const [constParameterPointer]
void stdlib_strided_bbbbb_b( uint8_t *arrays[], int64_t *shape, int64_t *strides, void *fcn ) {
                                                                         ^
```

### Pull Request Instructions

-   Please use the following PR title format:
"chore: fix C lint errors (issue #<ISSUE_NUMBER>)".
-   Reference this issue in the "Related Issues" section of the PR body as "resolves #<ISSUE_NUMBER>".

### PR DESCRIPTION
**Pull request by GeoDaoyu**
Resolves #11462.

## Description

> What is the purpose of this pull request?

This pull request:

-   fix C lint errors

## Related Issues

> Does this pull request have any related issues?

This pull request has the following related issues:

-   #11462

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

### AI Assistance

> When authoring the changes proposed in this PR, did you use any kind of AI assistance?

-   [ ] Yes
-   [x] No

If you answered "yes" above, how did you use AI assistance?

-   [ ] Code generation (e.g., when writing an implementation or fixing a bug)
-   [ ] Test/benchmark generation
-   [ ] Documentation (including examples)
-   [ ] Research and understanding

#### Disclosure

> If you answered "yes" to using AI assistance, please provide a short disclosure indicating how you used AI assistance. This helps reviewers determine how much scrutiny to apply when reviewing your contribution. Example disclosures: "This PR was written primarily by Claude Code." or "I consulted ChatGPT to understand the codebase, but the proposed changes were fully authored manually by myself.".

{{TODO: add disclosure if applicable}}

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

### CODE REVIEW

File: lib/node_modules/@stdlib/strided/common/src/quinary.c [hunk 1]
```diff
@@ -105,7 +105,7 @@
 * // Apply the callback:
 * stdlib_strided_ddddd_d( arrays, shape, strides, (void *)add5 );
 */
-void stdlib_strided_ddddd_d( uint8_t *arrays[], int64_t *shape, int64_t *strides, void *fcn ) {
+void stdlib_strided_ddddd_d( uint8_t *arrays[], const int64_6 *shape, const int64_t *strides, void *fcn ) {
```
Comment (kgryte) [inline lib/node_modules/@stdlib/strided/common/src/quinary.c]:
```suggestion
void stdlib_strided_ddddd_d( uint8_t *arrays[], const int64_t *shape, const int64_t *strides, void *fcn ) {
```

File: lib/node_modules/@stdlib/strided/common/src/quinary.c [hunk 2]
```diff
@@ -147,7 +147,7 @@ void stdlib_strided_ddddd_d( uint8_t *arrays[], int64_t *shape, int64_t *strides
 * // Apply the callback:
 * stdlib_strided_fffff_f( arrays, shape, strides, (void *)add5 );
 */
-void stdlib_strided_fffff_f( uint8_t *arrays[], int64_t *shape, int64_t *strides, void *fcn ) {
+void stdlib_strided_fffff_f( uint8_t *arrays[], const int64_6 *shape, const int64_t *strides, void *fcn ) {
```
Comment (kgryte) [inline lib/node_modules/@stdlib/strided/common/src/quinary.c]:
```suggestion
void stdlib_strided_fffff_f( uint8_t *arrays[], const int64_t *shape, const int64_t *strides, void *fcn ) {
```

File: lib/node_modules/@stdlib/strided/common/src/quinary.c [hunk 3]
```diff
@@ -189,7 +189,7 @@ void stdlib_strided_fffff_f( uint8_t *arrays[], int64_t *shape, int64_t *strides
 * // Apply the callback:
 * stdlib_strided_fffff_f_as_ddddd_d( arrays, shape, strides, (void *)add5 );
 */
-void stdlib_strided_fffff_f_as_ddddd_d( uint8_t *arrays[], int64_t *shape, int64_t *strides, void *fcn ) {
+void stdlib_strided_fffff_f_as_ddddd_d( uint8_t *arrays[], const int64_6 *shape, const int64_t *strides, void *fcn ) {
```
Comment (kgryte) [inline lib/node_modules/@stdlib/strided/common/src/quinary.c]:
```suggestion
void stdlib_strided_fffff_f_as_ddddd_d( uint8_t *arrays[], const int64_t *shape, const int64_t *strides, void *fcn ) {
```

File: lib/node_modules/@stdlib/strided/common/src/quinary.c [hunk 4]
```diff
@@ -231,7 +231,7 @@ void stdlib_strided_fffff_f_as_ddddd_d( uint8_t *arrays[], int64_t *shape, int64
 * // Apply the callback:
 * stdlib_strided_IIIII_I( arrays, shape, strides, (void *)add5 );
 */
-void stdlib_strided_IIIII_I( uint8_t *arrays[], int64_t *shape, int64_t *strides, void *fcn ) {
+void stdlib_strided_IIIII_I( uint8_t *arrays[], const int64_6 *shape, const int64_t *strides, void *fcn ) {
```
Comment (kgryte) [inline lib/node_modules/@stdlib/strided/common/src/quinary.c]:
```suggestion
void stdlib_strided_IIIII_I( uint8_t *arrays[], const int64_t *shape, const int64_t *strides, void *fcn ) {
```

File: lib/node_modules/@stdlib/strided/common/src/quinary.c [hunk 5]
```diff
@@ -273,7 +273,7 @@ void stdlib_strided_IIIII_I( uint8_t *arrays[], int64_t *shape, int64_t *strides
 * // Apply the callback:
 * stdlib_strided_iiiii_i( arrays, shape, strides, (void *)add5 );
 */
-void stdlib_strided_iiiii_i( uint8_t *arrays[], int64_t *shape, int64_t *strides, void *fcn ) {
+void stdlib_strided_iiiii_i( uint8_t *arrays[], const int64_6 *shape, const int64_t *strides, void *fcn ) {
```
Comment (kgryte) [inline lib/node_modules/@stdlib/strided/common/src/quinary.c]:
```suggestion
void stdlib_strided_iiiii_i( uint8_t *arrays[], const int64_t *shape, const int64_t *strides, void *fcn ) {
```

File: lib/node_modules/@stdlib/strided/common/src/quinary.c [hunk 6]
```diff
@@ -315,7 +315,7 @@ void stdlib_strided_iiiii_i( uint8_t *arrays[], int64_t *shape, int64_t *strides
 * // Apply the callback:
 * stdlib_strided_HHHHH_H( arrays, shape, strides, (void *)add5 );
 */
-void stdlib_strided_HHHHH_H( uint8_t *arrays[], int64_t *shape, int64_t *strides, void *fcn ) {
+void stdlib_strided_HHHHH_H( uint8_t *arrays[], const int64_6 *shape, const int64_t *strides, void *fcn ) {
```
Comment (kgryte) [inline lib/node_modules/@stdlib/strided/common/src/quinary.c]:
```suggestion
void stdlib_strided_HHHHH_H( uint8_t *arrays[], const int64_t *shape, const int64_t *strides, void *fcn ) {
```

File: lib/node_modules/@stdlib/strided/common/src/quinary.c [hunk 7]
```diff
@@ -357,7 +357,7 @@ void stdlib_strided_HHHHH_H( uint8_t *arrays[], int64_t *shape, int64_t *strides
 * // Apply the callback:
 * stdlib_strided_hhhhh_h( arrays, shape, strides, (void *)add5 );
 */
-void stdlib_strided_hhhhh_h( uint8_t *arrays[], int64_t *shape, int64_t *strides, void *fcn ) {
+void stdlib_strided_hhhhh_h( uint8_t *arrays[], const int64_6 *shape, const int64_t *strides, void *fcn ) {
```
Comment (kgryte) [inline lib/node_modules/@stdlib/strided/common/src/quinary.c]:
```suggestion
void stdlib_strided_hhhhh_h( uint8_t *arrays[], const int64_t *shape, const int64_t *strides, void *fcn ) {
```

File: lib/node_modules/@stdlib/strided/common/src/quinary.c [hunk 8]
```diff
@@ -399,7 +399,7 @@ void stdlib_strided_hhhhh_h( uint8_t *arrays[], int64_t *shape, int64_t *strides
 * // Apply the callback:
 * stdlib_strided_BBBBB_B( arrays, shape, strides, (void *)add5 );
 */
-void stdlib_strided_BBBBB_B( uint8_t *arrays[], int64_t *shape, int64_t *strides, void *fcn ) {
+void stdlib_strided_BBBBB_B( uint8_t *arrays[], const int64_6 *shape, const int64_t *strides, void *fcn ) {
```
Comment (kgryte) [inline lib/node_modules/@stdlib/strided/common/src/quinary.c]:
```suggestion
void stdlib_strided_BBBBB_B( uint8_t *arrays[], const int64_t *shape, const int64_t *strides, void *fcn ) {
```

File: lib/node_modules/@stdlib/strided/common/src/quinary.c [hunk 9]
```diff
@@ -441,7 +441,7 @@ void stdlib_strided_BBBBB_B( uint8_t *arrays[], int64_t *shape, int64_t *strides
 * // Apply the callback:
 * stdlib_strided_bbbbb_b( arrays, shape, strides, (void *)add5 );
 */
-void stdlib_strided_bbbbb_b( uint8_t *arrays[], int64_t *shape, int64_t *strides, void *fcn ) {
+void stdlib_strided_bbbbb_b( uint8_t *arrays[], const int64_6 *shape, const int64_t *strides, void *fcn ) {
```
Comment (kgryte) [inline lib/node_modules/@stdlib/strided/common/src/quinary.c]:
```suggestion
void stdlib_strided_bbbbb_b( uint8_t *arrays[], const int64_t *shape, const int64_t *strides, void *fcn ) {
```

**Review by kgryte — CHANGES_REQUESTED** [review]
@GeoDaoyu I believe the header file also needs to be updated: https://github.com/stdlib-js/stdlib/blob/a503990551e29e0152560945aa621f05bff97af1/lib/node_modules/%40stdlib/strided/common/include/stdlib/strided/common/quinary.h

**Review by kgryte — APPROVED** [review]
LGTM. Thanks, @GeoDaoyu!
