### PR TITLE
chore: fix JavaScript lint errors (issue #11444)

### LINKED ISSUE #11444: Fix JavaScript lint errors
## JavaScript Linting Failures

  Linting failures were detected in the automated JavaScript lint workflow run.

  ### Workflow Details

  - Run: https://github.com/stdlib-js/stdlib/actions/runs/24373700625
  - Type: JavaScript Linting
  - Date: 2026-04-14 00:26:55 UTC

  ### Error Details
  ```
  make[1]: Entering directory '/home/runner/work/stdlib/stdlib'

Linting file: lib/node_modules/@stdlib/blas/base/dgemv/lib/native.js

Linting file: lib/node_modules/@stdlib/assert/is-browser/lib/browser.js

Linting file: lib/node_modules/@stdlib/ndarray/strides/lib/index.js

Linting file: lib/node_modules/@stdlib/stats/base/ndarray/dmeanpn/lib/index.js

Linting file: lib/node_modules/@stdlib/stats/cumax/lib/main.js

Linting file: lib/node_modules/@stdlib/stats/base/dists/weibull/logcdf/lib/main.js

Linting file: lib/node_modules/@stdlib/ndarray/base/unary-reduce-strided1d/lib/8d_blocked_accessors.js

Linting file: lib/node_modules/@stdlib/stats/base/dists/logistic/mgf/lib/factory.js

Linting file: lib/node_modules/@stdlib/_tools/docs/www/readme-fragment-file-tree/lib/validate.js

Linting file: lib/node_modules/@stdlib/utils/flatten-array/lib/validate.js

Linting file: lib/node_modules/@stdlib/utils/async/inmap/lib/factory.js

Oops! Something went wrong! :(

ESLint: 8.57.1

Error: ENOENT: no such file or directory, open './beep.js'
Linting failed.

Linting file: lib/node_modules/@stdlib/ndarray/from-scalar-like/lib/index.js

Linting file: lib/node_modules/@stdlib/blas/ext/base/slast-index-of/lib/index.js

Linting file: lib/node_modules/@stdlib/math/strided/special/rsqrt/lib/data.js

Linting file: lib/node_modules/@stdlib/utils/from-entries/lib/main.js

Linting file: lib/node_modules/@stdlib/stats/base/dists/normal/ctor/lib/index.js

Linting file: lib/node_modules/@stdlib/blas/ext/base/ndarray/gsumpw/lib/index.js

Linting file: lib/node_modules/@stdlib/ndarray/base/some-by/lib/8d_accessors.js

Linting file: lib/node_modules/@stdlib/_tools/remark/plugins/remark-lint-html-section-structure/lib/index.js

Linting file: lib/node_modules/@stdlib/stats/strided/sstdevpn/lib/native.js

Linting file: lib/node_modules/@stdlib/math/base/special/gcd/lib/binary_gcd.js

Linting file: lib/node_modules/@stdlib/number/float32/base/identity/lib/native.js

Linting file: lib/node_modules/@stdlib/ndarray/base/assert/is-integer-data-type/lib/main.js
make[1]: *** [/home/runner/work/stdlib/stdlib/tools/make/lib/lint/javascript/eslint.mk:261: eslint-files] Error 1
make[1]: Leaving directory '/home/runner/work/stdlib/stdlib'
make: *** [/home/runner/work/stdlib/stdlib/tools/make/lib/lint/javascript/Makefile:158: lint-javascript-files] Error 2
make[1]: Entering directory '/home/runner/work/stdlib/stdlib'

Linting file: lib/node_modules/@stdlib/ndarray/base/loop-interchange-order/benchmark/benchmark.js

Linting file: lib/node_modules/@stdlib/blas/ext/base/ssortins/benchmark/benchmark.rev_mostly_sorted_random.native.js

Linting file: lib/node_modules/@stdlib/array/zero-to-like/benchmark/benchmark.length.int8.js

Linting file: lib/node_modules/@stdlib/assert/is-readable-property-in/benchmark/benchmark.js

/home/runner/work/stdlib/stdlib/lib/node_modules/@stdlib/assert/is-readable-property-in/benchmark/benchmark.js
  36:8  error  Using the `new Array()` constructor is not allowed; use an array literal with push instead  stdlib/no-new-array

✖ 1 problem (1 error, 0 warnings)

Linting failed.

Linting file: lib/node_modules/@stdlib/math/strided/special/ahavercos-by/benchmark/benchmark.js

Linting file: lib/node_modules/@stdlib/random/bernoulli/benchmark/benchmark.3d.assign.js

Linting file: lib/node_modules/@stdlib/random/tools/binary/benchmark/benchmark.assign.js

Linting file: lib/node_modules/@stdlib/stats/strided/wasm/dmeanors/benchmark/benchmark.module.js

Linting file: lib/node_modules/@stdlib/blas/ext/base/wasm/dapxsum/benchmark/benchmark.ndarray.js

Linting file: lib/node_modules/@stdlib/blas/ext/base/dsortsh/benchmark/benchmark.sorted_few_uniques.ndarray.native.js
make[1]: *** [/home/runner/work/stdlib/stdlib/tools/make/lib/lint/javascript/eslint.mk:261: eslint-files] Error 1
make[1]: Leaving directory '/home/runner/work/stdlib/stdlib'
make: *** [/home/runner/work/stdlib/stdlib/tools/make/lib/lint/javascript/Makefile:158: lint-javascript-files] Error 2
  ```

  ### Pull Request Instructions

  -   Please use the following PR title format:
  "chore: fix JavaScript lint errors (issue #<ISSUE_NUMBER>)".
  -   Reference this issue in the "Related Issues" section of the PR body as "resolves #<ISSUE_NUMBER>".

### PR DESCRIPTION
**Pull request by bhumikasudarshani-cmd**
#### Related Issues

resolves #11444

#### Description

Fixed JavaScript lint error by replacing `new Array()` constructor with array literal in-

 `lib/node_modules/@stdlib/assert/is-readable-property-in/benchmark/benchmark.js`
-   [x] Read, understood, and followed the [contributing guidelines](https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md)

### CODE REVIEW

File: lib/node_modules/@stdlib/error/tools/msg2id/lib/index.js [hunk 1]
```diff
@@ -27,7 +27,7 @@
 * var msg2id = require( '@stdlib/error/tools/msg2id' );
 *
 * var v = msg2id( 'invalid option. `%s` option must be an array. Option: `%s`.' );
-* // returns '8t'
+* // returns '8Z'
```
Comment (kgryte) [inline lib/node_modules/@stdlib/error/tools/msg2id/lib/index.js]:
```suggestion
* // returns '8t'
```

File: lib/node_modules/@stdlib/math/base/special/roundb/test/test.js [hunk 2]
```diff
@@ -162,7 +162,7 @@ tape( 'the function supports rounding a numeric value to a desired number of dec
 tape( 'due to floating-point rounding error, rounding a numeric value can result in unexpected behavior', function test( t ) {
 	var x;
 
-	x = 0.2 + 0.1; // => 0.30000000000000004
+	x = 0.2 + 0.1; // returns 0.30000000000000004
```
Comment (kgryte) [inline lib/node_modules/@stdlib/math/base/special/roundb/test/test.js]:
```suggestion
	x = 0.2 + 0.1; // => 0.30000000000000004
```

File: lib/node_modules/@stdlib/assert/is-readable-property-in/benchmark/benchmark.js [hunk 3]
```diff
@@ -33,7 +33,8 @@ bench( pkg, function benchmark( b ) {
 	var arr;
 	var i;
 
-	arr = new Array( 100 );
+      	arr = [];
+	arr.length = 100;
```
Comment (kgryte) [inline lib/node_modules/@stdlib/assert/is-readable-property-in/benchmark/benchmark.js]:
```suggestion
    arr = new Array( 100 ); // eslint-disable-line stdlib/no-new-array
```

File: lib/node_modules/@stdlib/assert/is-readable-property-in/benchmark/benchmark.js [hunk 4]
```diff
@@ -33,7 +33,7 @@ bench( pkg, function benchmark( b ) {
 	var arr;
 	var i;
 
-	arr = new Array( 100 );
+    arr = new Array( 100 ); // eslint-disable-line stdlib/no-new-array
```
Comment (kgryte) [inline lib/node_modules/@stdlib/assert/is-readable-property-in/benchmark/benchmark.js]:
```suggestion
	arr = new Array( 100 ); // eslint-disable-line stdlib/no-new-array
```

**Review by kgryte — APPROVED** [review]
