### PR TITLE
fix: resolve JavaScript lint errors in #5961

### LINKED ISSUE #5961: Fix JavaScript lint errors
## JavaScript Linting Failures

Linting failures were detected in the automated JavaScript lint workflow run.

### Workflow Details

- Run: https://github.com/stdlib-js/stdlib/actions/runs/13777226596
- Type: JavaScript Linting
- Date: 2025-03-11 00:09:45 UTC

### Error Details
```
make[1]: Entering directory '/home/runner/work/stdlib/stdlib'

Linting file: lib/node_modules/@stdlib/blas/ext/base/dcusum/lib/dcusum.native.js

Linting file: lib/node_modules/@stdlib/stats/base/dists/erlang/cdf/lib/main.js

Linting file: lib/node_modules/@stdlib/_tools/github/set-topics/lib/options.js

Linting file: lib/node_modules/@stdlib/assert/is-complex128ndarray-like/lib/main.js

Linting file: lib/node_modules/@stdlib/math/iter/special/round10/lib/main.js

Linting file: lib/node_modules/@stdlib/array/ctors/lib/main.js

Linting file: lib/node_modules/@stdlib/math/base/special/cphase/lib/native.js

/home/runner/work/stdlib/stdlib/lib/node_modules/@stdlib/math/base/special/cphase/lib/native.js
  40:1  error  Missing empty line between require statement and code in JSDoc example  stdlib/jsdoc-example-require-spacing

✖ 1 problem (1 error, 0 warnings)

Linting failed.

Linting file: lib/node_modules/@stdlib/plot/sparklines/unicode/column/lib/props/y-min/get.js

Linting file: lib/node_modules/@stdlib/stats/strided/dmax/lib/ndarray.js

Linting file: lib/node_modules/@stdlib/strided/base/dtype-str2enum/lib/index.js

Linting file: lib/node_modules/@stdlib/random/streams/pareto-type1/lib/debug.js

Linting file: lib/node_modules/@stdlib/assert/is-number/lib/index.js

Linting file: lib/node_modules/@stdlib/math/base/napi/binary/lib/browser.js

Linting file: lib/node_modules/@stdlib/random/array/mt19937/lib/index.js

Linting file: lib/node_modules/@stdlib/random/streams/gamma/lib/debug.js

Linting file: lib/node_modules/@stdlib/stats/base/dsnanmeanwd/lib/dsnanmeanwd.native.js

Linting file: lib/node_modules/@stdlib/random/streams/mt19937/lib/index.js

Linting file: lib/node_modules/@stdlib/stats/base/smaxabssorted/lib/ndarray.js

Linting file: lib/node_modules/@stdlib/stats/base/smeanli/lib/ndarray.js

Linting file: lib/node_modules/@stdlib/stats/base/dists/erlang/ctor/lib/main.js

Linting file: lib/node_modules/@stdlib/types/lib/index.js

Linting file: lib/node_modules/@stdlib/_tools/github/rank-users/lib/index.js

Linting file: lib/node_modules/@stdlib/string/replace/lib/main.js

Linting file: lib/node_modules/@stdlib/math/base/special/ceil10/lib/main.js

Linting file: lib/node_modules/@stdlib/math/base/special/polygamma/lib/nearzero.js
make[1]: *** [/home/runner/work/stdlib/stdlib/tools/make/lib/lint/javascript/eslint.mk:255: eslint-files] Error 1
make[1]: Leaving directory '/home/runner/work/stdlib/stdlib'
make: *** [/home/runner/work/stdlib/stdlib/tools/make/lib/lint/javascript/Makefile:158: lint-javascript-files] Error 2
```

### PR DESCRIPTION
**Pull request by Krishna-Sharma-g**
Resolves #5961 

## Description

> What is the purpose of this pull request?

This pull request:

-  js lint 

## Related Issues

> #5377 

This pull request:

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

### CODE REVIEW

**Comment by Krishna-Sharma-g** [comment]
@Planeshifter fixed the linting error !!

**Comment by Krishna-Sharma-g** [comment]
@aayush0325 please review

File: lib/node_modules/@stdlib/math/base/special/cphase/lib/native.js [hunk 1]
```diff
@@ -34,6 +34,7 @@ var addon = require( './../src/addon.node' );
 *
 * @example
 * var Complex128 = require( '@stdlib/complex/float64/ctor' );
+
```
Comment (aayush0325) [inline lib/node_modules/@stdlib/math/base/special/cphase/lib/native.js]:
```suggestion
*
```

**Review by aayush0325 — CHANGES_REQUESTED** [review]

**Review by aayush0325 — APPROVED** [review]
