### PR TITLE
chore: fix C lint errors (issue #11347)

### LINKED ISSUE #11347: Fix C lint errors
## C Linting Failures

Linting failures were detected in the automated lint workflow run.

### Workflow Details

-   Run: https://github.com/stdlib-js/stdlib/actions/runs/24219592970
-   Type: C Linting
-   Date: 2026-04-10 00:25:22 UTC

### Error Details

```
lib/node_modules/@stdlib/ndarray/base/unary-accumulate/src/dispatch.c:235:11: style: Variable 's1' can be declared as pointer to const [constVariablePointer]
 int64_t *s1;
          ^
```

### Pull Request Instructions

-   Please use the following PR title format:
"chore: fix C lint errors (issue #<ISSUE_NUMBER>)".
-   Reference this issue in the "Related Issues" section of the PR body as "resolves #<ISSUE_NUMBER>".

### PR DESCRIPTION
**Pull request by GuneetGill**
Resolves #11347

## Description

> What is the purpose of this pull request?

This pull request:

-   Fixes a cppcheck `constVariablePointer` warning in `unary-accumulate` by declaring the strides pointer `s1` as `const int64_t *`, since it is only read after assignment from `stdlib_ndarray_strides`.
-   Updates `stdlib_ndarray_iteration_order` to take `const int64_t *strides` in the public header and implementation, matching read-only use of strides and keeping the `dispatch.c` call type-correct without casts.

## Checklist

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

### AI Assistance
-   [ ] Yes
-   [x] No

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

### CODE REVIEW

File: lib/node_modules/@stdlib/ndarray/base/iteration-order/include/stdlib/ndarray/base/iteration_order.h [hunk 1]
```diff
@@ -31,7 +31,7 @@ extern "C" {
 /**
 * Determines array iteration order, given a stride array.
 */
-int8_t stdlib_ndarray_iteration_order( const int64_t ndims, const int64_t *strides );
+int8_t stdlib_ndarray_iteration_order( int64_t ndims, const int64_t *strides );
```
Comment (GeoDaoyu) [inline lib/node_modules/@stdlib/ndarray/base/iteration-order/include/stdlib/ndarray/base/iteration_order.h]: Hi, I have found that this issue has been resolved in this PR, https://github.com/stdlib-js/stdlib/pull/11335, You haven't pulled the latest code? You can try pulling.

File: lib/node_modules/@stdlib/ndarray/base/iteration-order/src/main.c [hunk 2]
```diff
@@ -43,7 +43,7 @@
 * int8_t o = stdlib_ndarray_iteration_order( ndims, strides );
 * // returns 1
 */
-int8_t stdlib_ndarray_iteration_order( const int64_t ndims, const int64_t *strides ) {
+int8_t stdlib_ndarray_iteration_order( int64_t ndims, const int64_t *strides ) {
```
Comment (GeoDaoyu) [inline lib/node_modules/@stdlib/ndarray/base/iteration-order/src/main.c]: The same

**Review by GeoDaoyu — COMMENTED** [review]
It seems that the code is not up-to-date.

File: lib/node_modules/@stdlib/ndarray/base/iteration-order/include/stdlib/ndarray/base/iteration_order.h (hunk 1 above)
Comment (kgryte) [inline lib/node_modules/@stdlib/ndarray/base/iteration-order/include/stdlib/ndarray/base/iteration_order.h]:
```suggestion
int8_t stdlib_ndarray_iteration_order( int64_t ndims, int64_t *strides );
```

File: lib/node_modules/@stdlib/ndarray/base/iteration-order/src/main.c (hunk 2 above)
Comment (kgryte) [inline lib/node_modules/@stdlib/ndarray/base/iteration-order/src/main.c]:
```suggestion
int8_t stdlib_ndarray_iteration_order( int64_t ndims, int64_t *strides ) {
```

File: lib/node_modules/@stdlib/ndarray/base/unary-accumulate/src/dispatch.c [hunk 3]
```diff
@@ -232,7 +232,7 @@ int8_t stdlib_ndarray_unary_accumulate_dispatch( const struct ndarrayUnaryAccumu
 	int64_t ndims;
 	int64_t mab1;
 	int64_t mib1;
-	int64_t *s1;
+	const int64_t *s1;
```
Comment (kgryte) [inline lib/node_modules/@stdlib/ndarray/base/unary-accumulate/src/dispatch.c:231]:
```suggestion
	const int64_t *sh1;
	struct ndarray *x1;
	struct ndarray *x2;
	struct ndarray *x3;
	const int64_t *s1;
	int8_t status;
	int64_t ndims;
	int64_t mab1;
	int64_t mib1;
```

**Review by kgryte — APPROVED** [review]

**Comment by kgryte** [comment]
Thank you for your contribution and congratulations on your first PR!
