### PR TITLE
chore: fix JavaScript lint errors (issue #8043)

### LINKED ISSUE #8043: Fix JavaScript lint errors
## JavaScript Linting Failures

  Linting failures were detected in the automated JavaScript lint workflow run.

  ### Workflow Details

  - Run: https://github.com/stdlib-js/stdlib/actions/runs/17567482780
  - Type: JavaScript Linting
  - Date: 2025-09-09 00:13:55 UTC

  ### Error Details
  ```
  make[1]: Entering directory '/home/runner/work/stdlib/stdlib'

Linting file: lib/node_modules/@stdlib/blas/ext/base/ssort2sh/lib/ssort2sh.js

Linting file: lib/node_modules/@stdlib/ndarray/vector/uint16/lib/main.js

Linting file: lib/node_modules/@stdlib/_tools/eslint/rules/jsdoc-ordered-list-marker-style/lib/index.js

Linting file: lib/node_modules/@stdlib/blas/base/ggemv/lib/index.js

Linting file: lib/node_modules/@stdlib/math/base/special/ellipk/lib/poly_p8.js

Linting file: lib/node_modules/@stdlib/random/base/normal/lib/index.js

Linting file: lib/node_modules/@stdlib/stats/strided/dnanvarianceyc/lib/main.js

Linting file: lib/node_modules/@stdlib/repl/lib/find_unique_entry.js

Linting file: lib/node_modules/@stdlib/utils/property-symbols/lib/index.js

Linting file: lib/node_modules/@stdlib/stats/strided/minsorted/lib/accessors.js

Linting file: lib/node_modules/@stdlib/ndarray/base/nullary/lib/2d.js

Linting file: lib/node_modules/@stdlib/array/base/group-indices/lib/main.js

Linting file: lib/node_modules/@stdlib/ndarray/base/includes/lib/nd_complex.js

Linting file: lib/node_modules/@stdlib/utils/timeit/lib/browser.js

Linting file: lib/node_modules/@stdlib/assert/is-startcase/lib/main.js

Linting file: lib/node_modules/@stdlib/cli/ctor/lib/index.js

/home/runner/work/stdlib/stdlib/lib/node_modules/@stdlib/cli/ctor/lib/index.js
  21:1  error  Encountered an error while running code: Cannot find module '/home/runner/work/stdlib/stdlib/lib/node_modules/@stdlib/cli/ctor/lib/path/to/package.json'
Require stack:
- /home/runner/work/stdlib/stdlib/node_modules/eslint-plugin-stdlib/index.js
- /home/runner/work/stdlib/stdlib/node_modules/@eslint/eslintrc/dist/eslintrc.cjs  stdlib/jsdoc-doctest
  21:1  error  Example code of main export should require itself last, i.e. contain `require( '@stdlib/cli/ctor' )` as the last `require` call                                                                                                                                                                                                         stdlib/jsdoc-main-export

✖ 2 problems (2 errors, 0 warnings)

Linting failed.

Linting file: lib/node_modules/@stdlib/assert/is-blank-string/lib/main.js

/home/runner/work/stdlib/stdlib/lib/node_modules/@stdlib/assert/is-blank-string/lib/main.js
  28:10  error  Unexpected control character(s) in regular expression: \x09, \x0a, \x0b, \x0c, \x0d  no-control-regex

✖ 1 problem (1 error, 0 warnings)

Linting failed.

Linting file: lib/node_modules/@stdlib/utils/async/for-each/lib/index.js

Oops! Something went wrong! :(

ESLint: 8.57.1

Error: unable to read file: ./beep.js
    at ReadFileContext.onFile [as callback] (evalmachine.<anonymous>:24:21)
    at FSReqCallback.readFileAfterOpen [as oncomplete] (node:fs:300:13)
Linting failed.

Linting file: lib/node_modules/@stdlib/regexp/semver/lib/index.js

Linting file: lib/node_modules/@stdlib/ndarray/base/map/lib/3d.js

Linting file: lib/node_modules/@stdlib/utils/zip/lib/main.js

/home/runner/work/stdlib/stdlib/lib/node_modules/@stdlib/utils/zip/lib/main.js
  158:8  error  Using the `new Array()` constructor is not allowed; use an array literal with push instead  stdlib/no-new-array
  161:9  error  Using the `new Array()` constructor is not allowed; use an array literal with push instead  stdlib/no-new-array

✖ 2 problems (2 errors, 0 warnings)

Linting failed.

Linting file: lib/node_modules/@stdlib/stats/base/dists/lognormal/entropy/lib/index.js

Linting file: lib/node_modules/@stdlib/_tools/github/set-topics/lib/query.js

Linting file: lib/node_modules/@stdlib/ndarray/base/unary-reduce-strided1d/lib/nd_accessors.js

Linting file: lib/node_modules/@stdlib/ml/incr/sgd-regression/lib/loss/epsilon_insensitive.js

Linting file: lib/node_modules/@stdlib/stats/base/dists/gumbel/mode/lib/index.js

Linting file: lib/node_modules/@stdlib/blas/ext/base/ndarray/dcusum/lib/main.js

Linting file: lib/node_modules/@stdlib/utils/index-of/lib/index.js

Linting file: lib/node_modules/@stdlib/_tools/github/create-issue/lib/ratelimit.js

Linting file: lib/node_modules/@stdlib/ndarray/base/ind2sub/lib/index.js
make[1]: *** [/home/runner/work/stdlib/stdlib/tools/make/lib/lint/javascript/eslint.mk:261: eslint-files] Error 1
make[1]: Leaving directory '/home/runner/work/stdlib/stdlib'
make: *** [/home/runner/work/stdlib/stdlib/tools/make/lib/lint/javascript/Makefile:158: lint-javascript-files] Error 2
  ```

  ### Pull Request Instructions

  -   Please use the following PR title format:
  "chore: fix JavaScript lint errors (issue #<ISSUE_NUMBER>)".
  -   Reference this issue in the "Related Issues" section of the PR body as "resolves #<ISSUE_NUMBER>".

### PR DESCRIPTION
**Pull request by rajanarahul93**
Resolves #8043.

## Description

> What is the purpose of this pull request?

This pull request:

-   fixes several distinct linting errors across three packages: a `jsdoc-doctest` error in `@stdlib/cli/ctor`, a `no-control-regex` error in `@stdlib/assert/is-blank-string`, and two `no-new-array` errors in `@stdlib/utils/zip`.

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves #8043

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

### CODE REVIEW

File: lib/node_modules/@stdlib/cli/ctor/lib/index.js [hunk 1]
```diff
@@ -24,20 +24,23 @@
...
-*     'help': 'Usage: beep [options] <boop>',
-*     'title': 'foo',
-*     'updates': true,
-*     'options': {
-*         'boolean': [
-*             'help',
-*             'version'
-*         ]
-*     }
+* 'pkg': {
```
Comment (kgryte) [inline lib/node_modules/@stdlib/cli/ctor/lib/index.js]: This is not the desired change.

File: lib/node_modules/@stdlib/utils/zip/lib/main.js [hunk 2]
```diff
@@ -155,10 +155,10 @@ function zip() {
 			}
 		}
 	}
-	out = new Array( len );
+	out = [];
```
Comment (kgryte) [inline lib/node_modules/@stdlib/utils/zip/lib/main.js:158]: See the lint error again. It tells you want changes need to be made. Your proposed changes are incomplete.

File: lib/node_modules/@stdlib/assert/is-blank-string/lib/main.js [hunk 3]
```diff
@@ -25,7 +25,7 @@ var isString = require( '@stdlib/assert/is-string' ).isPrimitive;
 
 // VARIABLES //
 
-var RE = /^[\u0009\u000A\u000B\u000C\u000D\u0020\u0085\u00A0\u1680\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200A\u2028\u2029\u202F\u205F\u3000\uFEFF]*$/;
+var RE = /^[\t\n\v\f\r\u0020\u0085\u00A0\u1680\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200A\u2028\u2029\u202F\u205F\u3000\uFEFF]*$/;
```
Comment (kgryte) [inline lib/node_modules/@stdlib/assert/is-blank-string/lib/main.js]: This is not the desired change.

File: lib/node_modules/@stdlib/utils/zip/lib/main.js [hunk 4]
```diff
@@ -155,24 +155,25 @@ function zip() {
...
+				arr.push( fill );
 				continue;
 			}
-			arr[ i ] = arg[ j ];
+			arr.push( arg[ j ] );
 		}
-		out[ j ] = arr;
+		out.push( arr );
 	}
+
```
Comment (kgryte) [inline lib/node_modules/@stdlib/utils/zip/lib/main.js]:
```suggestion
```

File: lib/node_modules/@stdlib/cli/ctor/lib/index.js [hunk 5]
```diff
@@ -7,7 +7,7 @@
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
-*    http://www.apache.org/licenses/LICENSE-2.0
+* http://www.apache.org/licenses/LICENSE-2.0
```
Comment (kgryte) [inline lib/node_modules/@stdlib/cli/ctor/lib/index.js]:
```suggestion
*    http://www.apache.org/licenses/LICENSE-2.0
```

File: lib/node_modules/@stdlib/cli/ctor/lib/index.js [hunk 6]
```diff
@@ -25,23 +25,24 @@
 *
 * @example
 * var CLI = require( '@stdlib/cli/ctor' );
-*
+
```
Comment (kgryte) [inline lib/node_modules/@stdlib/cli/ctor/lib/index.js]:
```suggestion
*
```

File: lib/node_modules/@stdlib/cli/ctor/lib/index.js [hunk 7]
```diff
@@ -27,21 +27,22 @@
...
+* 'help',
+* 'version'
+* ]
+* }
 * };
 * var cli = new CLI( opts );
 * // returns <CLI>
 *
 * cli.close();
+*
```
Comment (kgryte) [inline lib/node_modules/@stdlib/cli/ctor/lib/index.js]:
```suggestion
```

**Review by kgryte — APPROVED** [review]
