### PR TITLE
chore: fix JavaScript lint errors (issue #10042)

### LINKED ISSUE #10042: Fix JavaScript lint errors
## JavaScript Linting Failures

  Linting failures were detected in the automated JavaScript lint workflow run.

  ### Workflow Details

  - Run: https://github.com/stdlib-js/stdlib/actions/runs/21572784615
  - Type: JavaScript Linting
  - Date: 2026-02-02 00:14:15 UTC

  ### Error Details
  ```
  make[1]: Entering directory '/home/runner/work/stdlib/stdlib'

Linting file: lib/node_modules/@stdlib/string/pad/examples/index.js

Linting file: lib/node_modules/@stdlib/random/discrete-uniform/examples/index.js
-1.000000, -10.000000, 7.000000
-3.000000, -3.000000, -1.000000
-5.000000, -2.000000, -5.000000
3.000000, 5.000000, 2.000000
-3.000000, -10.000000, 10.000000
-1.000000, -10.000000, 7.000000
-3.000000, -3.000000, -1.000000
-5.000000, -2.000000, -5.000000
3.000000, 5.000000, 2.000000
-3.000000, -10.000000, 10.000000

Linting file: lib/node_modules/@stdlib/stats/strided/dvariance/examples/index.js

Linting file: lib/node_modules/@stdlib/object/deep-set/examples/index.js

/home/runner/work/stdlib/stdlib/lib/node_modules/@stdlib/object/deep-set/examples/index.js
  33:8  error  Using the `new Array()` constructor is not allowed; use an array literal with push instead  stdlib/no-new-array

✖ 1 problem (1 error, 0 warnings)

Linting failed.

Linting file: lib/node_modules/@stdlib/array/base/count-same-value/examples/index.js

Linting file: lib/node_modules/@stdlib/blas/ext/find-index/examples/index.js

Linting file: lib/node_modules/@stdlib/stats/base/dists/laplace/skewness/examples/index.js
µ: 3.3926, b: 13.1336, skew(X;µ,b): 0.0000
µ: 0.3310, b: 9.5725, skew(X;µ,b): 0.0000
µ: 2.4996, b: 18.5584, skew(X;µ,b): 0.0000
µ: -1.1157, b: 17.7963, skew(X;µ,b): 0.0000
µ: -4.4399, b: 12.5984, skew(X;µ,b): 0.0000
µ: 0.9996, b: 9.5782, skew(X;µ,b): 0.0000
µ: 4.5371, b: 14.4764, skew(X;µ,b): 0.0000
µ: 3.5155, b: 10.9122, skew(X;µ,b): 0.0000
µ: -1.0463, b: 14.4134, skew(X;µ,b): 0.0000
µ: -4.2077, b: 10.5168, skew(X;µ,b): 0.0000

Linting file: lib/node_modules/@stdlib/array/typed-integer-dtypes/examples/index.js

Linting file: lib/node_modules/@stdlib/math/base/tools/evalrationalf/examples/index.js
make[1]: *** [/home/runner/work/stdlib/stdlib/tools/make/lib/lint/javascript/eslint.mk:261: eslint-files] Error 1
make[1]: Leaving directory '/home/runner/work/stdlib/stdlib'
make: *** [/home/runner/work/stdlib/stdlib/tools/make/lib/lint/javascript/Makefile:158: lint-javascript-files] Error 2
  ```

  ### Pull Request Instructions

  -   Please use the following PR title format:
  "chore: fix JavaScript lint errors (issue #<ISSUE_NUMBER>)".
  -   Reference this issue in the "Related Issues" section of the PR body as "resolves #<ISSUE_NUMBER>".

### PR DESCRIPTION
**Pull request by bhargava-d16**
---
type: pre_commit_static_analysis_report
description: Results of running static analysis checks when committing changes. report:
  - task: lint_filenames status: passed
  - task: lint_editorconfig status: passed
  - task: lint_markdown status: na
  - task: lint_package_json status: na
  - task: lint_repl_help status: na
  - task: lint_javascript_src status: na
  - task: lint_javascript_cli status: na
  - task: lint_javascript_examples status: passed
  - task: lint_javascript_tests status: na
  - task: lint_javascript_benchmarks status: na
  - task: lint_python status: na
  - task: lint_r status: na
  - task: lint_c_src status: na
  - task: lint_c_examples status: na
  - task: lint_c_benchmarks status: na
  - task: lint_c_tests_fixtures status: na
  - task: lint_shell status: na
  - task: lint_typescript_declarations status: passed
  - task: lint_typescript_tests status: na
  - task: lint_license_headers status: passed ---

Resolves #10042 

## Description

> What is the purpose of this pull request?

This pull request:

-   Resolves lint error

## Related Issues

> Does this pull request have any related issues?

This pull request has the following related issues:

-   #10042 

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

### AI Assistance

> When authoring the changes proposed in this PR, did you use any kind of AI assistance?

-   [x] Yes
-   [ ] No

If you answered "yes" above, how did you use AI assistance?

-   [ ] Code generation (e.g., when writing an implementation or fixing a bug)
-   [ ] Test/benchmark generation
-   [ ] Documentation (including examples)
-   [ ] Research and understanding

#### Disclosure

> If you answered "yes" to using AI assistance, please provide a short disclosure indicating how you used AI assistance. This helps reviewers determine how much scrutiny to apply when reviewing your contribution. Example disclosures: "This PR was written primarily by Claude Code." or "I consulted ChatGPT to understand the codebase, but the proposed changes were fully authored manually by myself.".

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

### CODE REVIEW

File: lib/node_modules/@stdlib/object/deep-set/examples/index.js [hunk 1]
```diff
@@ -30,7 +30,8 @@ function set( val ) {
 	return val * 10.0;
 }
 
-data = new Array( 100 );
+data = [];
+data.length = 100;
 for ( i = 0; i < data.length; i++ ) {
 	data[ i ] = {
```
Comment (GeoDaoyu) [inline lib/node_modules/@stdlib/object/deep-set/examples/index.js]: use an array literal with push instead

**Review by GeoDaoyu — COMMENTED** [review]
Using the `new Array()` constructor is not allowed; use an array literal with push instead  stdlib/no-new-array
This is two lint errors

File: lib/node_modules/@stdlib/object/deep-set/examples/index.js [hunk 2]
```diff
@@ -30,12 +30,12 @@ function set( val ) {
...
-data = new Array( 100 );
-for ( i = 0; i < data.length; i++ ) {
-	data[ i ] = {
+data = [];
+for ( i = 0; i < 100; i++ ) {
+	data.push({
 		'x': Date.now(),
 		'y': [ randu(), randu(), i ]
-	};
+	});
```
Comment (Planeshifter) [inline lib/node_modules/@stdlib/object/deep-set/examples/index.js]: Missing spaces inside the parentheses. Per our conventions, function calls should have spaces: `foo( bar )`.

```suggestion
	data.push( {
		'x': Date.now(),
		'y': [ randu(), randu(), i ]
	} );
```

**Review by kgryte — APPROVED** [review]
LGTM. Thanks for the review @GeoDaoyu!
