### PR TITLE
chore: fix C lint errors (issue #9357)

### LINKED ISSUE #9357: Fix C lint errors
## C Linting Failures

Linting failures were detected in the automated lint workflow run.

### Workflow Details

-   Run: https://github.com/stdlib-js/stdlib/actions/runs/20495846700
-   Type: C Linting
-   Date: 2025-12-25 00:19:48 UTC

### Error Details

```

lib/node_modules/@stdlib/stats/base/snanstdevwd/examples/c/example.c:25:8: style: Variable 'x' can be declared as const array [constVariable]
 float x[] = { 1.0, 2.0, 0.0/0.0, 3.0, 0.0/0.0, 4.0, 5.0, 6.0, 0.0/0.0, 7.0, 8.0, 0.0/0.0 };
       ^
```

### Pull Request Instructions

-   Please use the following PR title format:
"chore: fix C lint errors (issue #<ISSUE_NUMBER>)".
-   Reference this issue in the "Related Issues" section of the PR body as "resolves #<ISSUE_NUMBER>".

### PR DESCRIPTION
**Pull request by GeoDaoyu**
Resolves #9357.

## Description

> What is the purpose of this pull request?

This pull request:

-   fix C lint errors

## Related Issues

> Does this pull request have any related issues?

This pull request has the following related issues:

-   #9357

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

According to
lib/node_modules/@stdlib/stats/base/snanstdevwd/src/snanstdevwd.c

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

### AI Assistance

> When authoring the changes proposed in this PR, did you use any kind of AI assistance?

-   [ ] Yes
-   [x] No

If you answered "yes" above, how did you use AI assistance?

-   [ ] Code generation (e.g., when writing an implementation or fixing a bug)
-   [ ] Test/benchmark generation
-   [ ] Documentation (including examples)
-   [ ] Research and understanding

#### Disclosure

> If you answered "yes" to using AI assistance, please provide a short disclosure indicating how you used AI assistance. This helps reviewers determine how much scrutiny to apply when reviewing your contribution. Example disclosures: "This PR was written primarily by Claude Code." or "I consulted ChatGPT to understand the codebase, but the proposed changes were fully authored manually by myself.".

{{TODO: add disclosure if applicable}}

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

### CODE REVIEW

File: lib/node_modules/@stdlib/stats/base/snanstdevwd/examples/c/example.c [hunk 1]
```diff
@@ -22,13 +22,13 @@
 
 int main( void ) {
 	// Create a strided array:
-	float x[] = { 1.0, 2.0, 0.0/0.0, 3.0, 0.0/0.0, 4.0, 5.0, 6.0, 0.0/0.0, 7.0, 8.0, 0.0/0.0 };
+	const float x[] = { 1.0, 2.0, 0.0/0.0, 3.0, 0.0/0.0, 4.0, 5.0, 6.0, 0.0/0.0, 7.0, 8.0, 0.0/0.0 };
```
Comment (kgryte) [inline lib/node_modules/@stdlib/stats/base/snanstdevwd/examples/c/example.c]:
```suggestion
	const float x[] = { 1.0f, 2.0f, 0.0f/0.0f, 3.0f, 0.0f/0.0f, 4.0f, 5.0f, 6.0f, 0.0f/0.0f, 7.0f, 8.0f, 0.0f/0.0f };
```

**Review by kgryte — COMMENTED** [review]
This looks good. @GeoDaoyu do we also need to update the README or no?

**Comment by GeoDaoyu** [comment]
> 外观不错。@GeoDaoyu我们是否还需要更新README文件？

which README do you mean?
this? lib/node_modules/@stdlib/stats/base/snanstdevwd/README.md

what should I do?

**Comment by kgryte** [comment]
@GeoDaoyu Correct. My question is whether we need to copy over the changes in the example.c file to the README, provided the README includes the C example.

**Comment by GeoDaoyu** [comment]
I think we don't need to update the README.
Because all the examples in the readme are in js, not in c.

**Comment by kgryte** [comment]
You're right. That package doesn't appear to have been updated yet. Thanks for checking!

**Comment by GeoDaoyu** [comment]
If we should add c examples to README.
Should we add an another RFC? There are too many examples like this.

**Review by kgryte — APPROVED** [review]

**Comment by kgryte** [comment]
We do need to add C examples, but we've been doing that as we migrate the strided packages from `stats/base` to `stats/strided`. No need to open an RFC at the moment, as that migration is currently blocked.
