### PR TITLE
chore: fix JavaScript lint errors (issue #8169)

### LINKED ISSUE #8169: Fix JavaScript lint errors
## JavaScript Linting Failures

  Linting failures were detected in the automated JavaScript lint workflow run.

  ### Workflow Details

  - Run: https://github.com/stdlib-js/stdlib/actions/runs/18146741745
  - Type: JavaScript Linting
  - Date: 2025-10-01 00:12:54 UTC

  ### Error Details
  ```
  make[1]: Entering directory '/home/runner/work/stdlib/stdlib'

Linting file: lib/node_modules/@stdlib/plot/base/ctor/lib/props/line-opacity/set.js

Linting file: lib/node_modules/@stdlib/ndarray/base/for-each/lib/0d.js
0

Linting file: lib/node_modules/@stdlib/plot/components/svg/graph/lib/props/translate-x/set.js

Linting file: lib/node_modules/@stdlib/math/base/special/polygamma/lib/polyval_p10.js

Linting file: lib/node_modules/@stdlib/streams/node/debug/lib/main.js

Linting file: lib/node_modules/@stdlib/_tools/eslint/rules/no-multiple-empty-lines/lib/index.js

Linting file: lib/node_modules/@stdlib/console/log-each-map/lib/index.js
1 + 4 = 5
2 + 5 = 7
3 + 6 = 9
0.50 * 0.50 = 0.25
1.00 * 0.75 = 0.75
1.50 * 1.00 = 1.50
foo+baz = foobaz
bar+beep = barbeep

Linting file: lib/node_modules/@stdlib/_tools/eslint/rules/jsdoc-doctest-decimal-point/lib/main.js

Linting file: lib/node_modules/@stdlib/complex/reviver/lib/main.js

Linting file: lib/node_modules/@stdlib/assert/is-probability/lib/object.js

Linting file: lib/node_modules/@stdlib/plot/components/svg/title/lib/props/text/get.js

Linting file: lib/node_modules/@stdlib/_tools/lint/header-filenames/lib/sync.js

Linting file: lib/node_modules/@stdlib/_tools/github/create-issue/lib/request.js

Linting file: lib/node_modules/@stdlib/array/mostly-safe-casts/lib/index.js

Linting file: lib/node_modules/@stdlib/strided/base/unary/lib/unary.js

Linting file: lib/node_modules/@stdlib/random/iter/beta/lib/main.js

Linting file: lib/node_modules/@stdlib/assert/is-ragged-nested-array/lib/index.js

Linting file: lib/node_modules/@stdlib/utils/async/reduce-right/lib/limit.js

/home/runner/work/stdlib/stdlib/lib/node_modules/@stdlib/utils/async/reduce-right/lib/limit.js
  100:3  error  Function 'cb' should be moved to outer function scope  stdlib/no-unnecessary-nested-functions

✖ 1 problem (1 error, 0 warnings)

Linting failed.

Linting file: lib/node_modules/@stdlib/blas/ext/base/dnansumpw/lib/index.js

Linting file: lib/node_modules/@stdlib/_tools/github/create-token/lib/headers.js
make[1]: *** [/home/runner/work/stdlib/stdlib/tools/make/lib/lint/javascript/eslint.mk:261: eslint-files] Error 1
make[1]: Leaving directory '/home/runner/work/stdlib/stdlib'
make: *** [/home/runner/work/stdlib/stdlib/tools/make/lib/lint/javascript/Makefile:158: lint-javascript-files] Error 2
make[1]: Entering directory '/home/runner/work/stdlib/stdlib'

Linting file: lib/node_modules/@stdlib/random/streams/exponential/benchmark/benchmark.throughput.js

Linting file: lib/node_modules/@stdlib/math/base/assert/is-integerf/benchmark/benchmark.native.js

Linting file: lib/node_modules/@stdlib/ndarray/base/every/benchmark/benchmark.5d_blocked_columnmajor.js

Linting file: lib/node_modules/@stdlib/array/byte-orders/benchmark/benchmark.js

Linting file: lib/node_modules/@stdlib/array/bool/benchmark/benchmark.find.js

Linting file: lib/node_modules/@stdlib/assert/is-nonpositive-number/benchmark/benchmark.js

/home/runner/work/stdlib/stdlib/lib/node_modules/@stdlib/assert/is-nonpositive-number/benchmark/benchmark.js
  19:1  error  Unused eslint-disable directive (no problems were reported from 'no-new-wrappers')

✖ 1 problem (1 error, 0 warnings)
  1 error and 0 warnings potentially fixable with the `--fix` option.

Linting failed.

Linting file: lib/node_modules/@stdlib/stats/base/dists/logistic/pdf/benchmark/benchmark.native.js

Linting file: lib/node_modules/@stdlib/blas/base/dswap/benchmark/benchmark.ndarray.js

Linting file: lib/node_modules/@stdlib/stats/strided/dstdevwd/benchmark/benchmark.ndarray.js

Linting file: lib/node_modules/@stdlib/blas/ext/base/sapxsumors/benchmark/benchmark.ndarray.js

Linting file: lib/node_modules/@stdlib/fs/resolve-parent-paths/benchmark/benchmark.js
make[1]: *** [/home/runner/work/stdlib/stdlib/tools/make/lib/lint/javascript/eslint.mk:261: eslint-files] Error 1
make[1]: Leaving directory '/home/runner/work/stdlib/stdlib'
make: *** [/home/runner/work/stdlib/stdlib/tools/make/lib/lint/javascript/Makefile:158: lint-javascript-files] Error 2
  ```

  ### Pull Request Instructions

  -   Please use the following PR title format:
  "chore: fix JavaScript lint errors (issue #<ISSUE_NUMBER>)".
  -   Reference this issue in the "Related Issues" section of the PR body as "resolves #<ISSUE_NUMBER>".

### PR DESCRIPTION
**Pull request by Payal-Goswami**
Resolves #8169.

## Description

This pull request fixes the linting issues reported in #8169:

-  Moved cb function to outer scope in utils/async/reduce-right/lib/limit.js to comply with stdlib/no-unnecessary-nested-functions.
- Removed unused eslint-disable directive in assert/is-nonpositive-number/benchmark/benchmark.js

## Related Issues

This pull request:

-   resolves #8169 

## Questions

No.

## Other

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

### CODE REVIEW

File: lib/node_modules/@stdlib/utils/async/reduce-right/lib/limit.js [hunk 1]
```diff
@@ -75,6 +75,27 @@ function limit( collection, acc, opts, fcn, done ) {
...
+		}
+		if ( error ) {
+			flg = true;
+			return clbk( error );
+		}
+		debug( 'Accumulator: %s', JSON.stringify( result ) );
+		acc = result;
+		clbk();
+	}
+	/**
```
Comment (Planeshifter) [inline lib/node_modules/@stdlib/utils/async/reduce-right/lib/limit.js:99]:
```suggestion
	}

	/**
```

**Review by Planeshifter — APPROVED** [review]
looks good, thank you!
