### PR TITLE
fix: rename pow.h to pow_int.h to match package name

### LINKED ISSUE #11230: [BUG]: wrong header name for `@stdlib/math/base/special/fast/pow-int`
### Description

The file basename is `pow.h` instead of `pow_int.h` , it should match it's package name but in snakecase, rather than kebabcase.

### Environments

N/A

### Checklist

- [x] Read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [x] Searched for existing issues and pull requests.

### PR DESCRIPTION
**Pull request by Md-Zaid45**
Resolves #11230.

This pull request:
- Renames `pow.h` to `pow_int.h` to match the package name (`pow-int`) in snake_case, as required by the naming convention.

This pull request has the following related issues:
- #11230

No.

No.

- [x] Read, understood, and followed the [contributing guidelines][contributing].

- [x] No

* * *
@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

### CODE REVIEW

File: lib/node_modules/@stdlib/math/base/special/fast/pow-int/src/main.c [hunk 1]
```diff
@@ -16,7 +16,7 @@
 * limitations under the License.
 */
 
-#include "stdlib/math/base/special/fast/pow.h"
+#include "stdlib/math/base/special/fast/pow_int.h"
```
Comment (Planeshifter) [inline lib/node_modules/@stdlib/math/base/special/fast/pow-int/src/main.c:19]: This same update needs to happen in two more files that were missed:

- `examples/c/example.c` (line 19): still includes `pow.h`
- `benchmark/c/native/benchmark.c` (line 19): still includes `pow.h`

Both need to be updated to include `pow_int.h`; otherwise, they'll fail to compile.

**Review by Planeshifter — CHANGES_REQUESTED** [review]
Thanks for this PR!

File: lib/node_modules/@stdlib/math/base/special/fast/pow-int/src/main.c (hunk 1 above)
Comment (Md-Zaid45) [reply lib/node_modules/@stdlib/math/base/special/fast/pow-int/src/main.c:19]: Thanks for catching that. I'll update both files

**Review by kgryte — APPROVED** [review]
LGTM
