### PR TITLE
fix: javascript lint errors (issue #7107)

### LINKED ISSUE #7107: Fix JavaScript lint errors
## JavaScript Linting Failures

  Linting failures were detected in the automated JavaScript lint workflow run.

  ### Workflow Details

  - Run: https://github.com/stdlib-js/stdlib/actions/runs/15288239198
  - Type: JavaScript Linting
  - Date: 2025-05-28 00:07:19 UTC

  ### Error Details
  ```
  make[1]: Entering directory '/home/runner/work/stdlib/stdlib'

Linting file: lib/node_modules/@stdlib/namespace/lib/namespace/base/strided/q.js

Linting file: lib/node_modules/@stdlib/assert/is-arraybuffer-view/lib/polyfill.js

/home/runner/work/stdlib/stdlib/lib/node_modules/@stdlib/assert/is-arraybuffer-view/lib/polyfill.js
  49:1  error  Missing empty line between require statement and code in JSDoc example  stdlib/jsdoc-example-require-spacing

✖ 1 problem (1 error, 0 warnings)

Linting failed.

Linting file: lib/node_modules/@stdlib/utils/map-reduce/lib/ndarray.js

/home/runner/work/stdlib/stdlib/lib/node_modules/@stdlib/utils/map-reduce/lib/ndarray.js
  94:66  warning  Unknown word: "cceil"  @cspell/spellchecker
  94:92  warning  Unknown word: "cadd"   @cspell/spellchecker

✖ 2 problems (0 errors, 2 warnings)


Linting file: lib/node_modules/@stdlib/_tools/github/create-token/lib/headers.js

Linting file: lib/node_modules/@stdlib/string/base/slice-grapheme-clusters/lib/index.js

/home/runner/work/stdlib/stdlib/lib/node_modules/@stdlib/string/base/slice-grapheme-clusters/lib/index.js
  35:33  warning  Unknown word: "अनुच्छेद"  @cspell/spellchecker

✖ 1 problem (0 errors, 1 warning)


Linting file: lib/node_modules/@stdlib/math/strided/special/dmskcbrt/lib/index.js

Linting file: lib/node_modules/@stdlib/stats/base/dists/invgamma/lib/index.js

Linting file: lib/node_modules/@stdlib/math/iter/sequences/negafibonacci/lib/main.js

/home/runner/work/stdlib/stdlib/lib/node_modules/@stdlib/math/iter/sequences/negafibonacci/lib/main.js
  37:41  warning  Unknown word: "nega"  @cspell/spellchecker
  41:62  warning  Unknown word: "nega"  @cspell/spellchecker
  41:95  warning  Unknown word: "nega"  @cspell/spellchecker

✖ 3 problems (0 errors, 3 warnings)


Linting file: lib/node_modules/@stdlib/stats/base/dists/t/logpdf/lib/index.js

Linting file: lib/node_modules/@stdlib/array/min-dtype/lib/main.js

Linting file: lib/node_modules/@stdlib/strided/base/nullary-addon-dispatch/lib/index.js

Linting file: lib/node_modules/@stdlib/ndarray/base/for-each/lib/7d_accessors.js
0 + 0i
0 + 0i
0 + 0i
0 + 0i

Linting file: lib/node_modules/@stdlib/stats/base/nanmax-by/lib/main.js

Linting file: lib/node_modules/@stdlib/array/typed-signed-integer-dtypes/lib/index.js

Linting file: lib/node_modules/@stdlib/math/iter/special/acosh/lib/main.js

Linting file: lib/node_modules/@stdlib/fs/unlink/lib/main.js

Oops! Something went wrong! :(

ESLint: 8.57.1

Error: ENOENT: no such file or directory, unlink './beep/boop.txt'
Linting failed.

Linting file: lib/node_modules/@stdlib/stats/strided/sdsmeanors/lib/sdsmeanors.js

Linting file: lib/node_modules/@stdlib/random/base/kumaraswamy/lib/index.js

Linting file: lib/node_modules/@stdlib/namespace/lib/namespace/base/y.js

Linting file: lib/node_modules/@stdlib/stats/base/dists/lognormal/cdf/lib/factory.js

Linting file: lib/node_modules/@stdlib/stats/chi2gof/lib/main.js

/home/runner/work/stdlib/stdlib/lib/node_modules/@stdlib/stats/chi2gof/lib/main.js
  135:28  warning  Unexpected 'warning' comment: 'WARNING: this relies on PMF functions...'  no-warning-comments
  206:50  warning  Unexpected 'todo' comment: 'TODO: consider replacing with low-level...'   no-warning-comments

✖ 2 problems (0 errors, 2 warnings)

make[1]: *** [/home/runner/work/stdlib/stdlib/tools/make/lib/lint/javascript/eslint.mk:255: eslint-files] Error 1
make[1]: Leaving directory '/home/runner/work/stdlib/stdlib'
make: *** [/home/runner/work/stdlib/stdlib/tools/make/lib/lint/javascript/Makefile:158: lint-javascript-files] Error 2
  ```

  ### Pull Request Instructions

  -   Please use the following PR title format:
  "chore: fix JavaScript lint errors (issue #<ISSUE_NUMBER>)".
  -   Reference this issue in the "Related Issues" section of the PR body as "resolves #<ISSUE_NUMBER>".

### PR DESCRIPTION
**Pull request by TusharBhardwaj441**
---
type: pre_commit_static_analysis_report
description: Results of running static analysis checks when committing changes. report:
  - task: lint_filenames status: passed
  - task: lint_editorconfig status: passed
  - task: lint_markdown status: na
  - task: lint_package_json status: na
  - task: lint_repl_help status: na
  - task: lint_javascript_src status: passed
  - task: lint_javascript_cli status: na
  - task: lint_javascript_examples status: na
  - task: lint_javascript_tests status: na
  - task: lint_javascript_benchmarks status: na
  - task: lint_python status: na
  - task: lint_r status: na
  - task: lint_c_src status: na
  - task: lint_c_examples status: na
  - task: lint_c_benchmarks status: na
  - task: lint_c_tests_fixtures status: na
  - task: lint_shell status: na
  - task: lint_typescript_declarations status: na
  - task: lint_typescript_tests status: na
  - task: lint_license_headers status: passed ---

Resolves #7107 

## Description

> What is the purpose of this pull request?
    fix JavaScript lint errors

## Related Issues

> Does this pull request have any related issues?
 No

This pull request:

-   resolves #7107 

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [X] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

### CODE REVIEW

File: lib/node_modules/@stdlib/stats/chi2gof/lib/main.js [hunk 1]
```diff
@@ -132,7 +132,7 @@ function chi2gof( x, y ) {
 		if ( pmf instanceof Error ) {
 			throw pmf;
 		}
-		nargs += pmf.length - 1; // WARNING: this relies on PMF functions having an explicit arity
```
Comment (kgryte) [inline lib/node_modules/@stdlib/stats/chi2gof/lib/main.js]: Please do not replace these labels. They are intentional.

File: lib/node_modules/@stdlib/assert/is-arraybuffer-view/lib/polyfill.js [hunk 2]
```diff
@@ -39,6 +39,7 @@ var isDataView = require( '@stdlib/assert/is-dataview' );
 *
 * @example
 * var Int8Array = require( '@stdlib/array/int8' );
+
```
Comment (kgryte) [inline lib/node_modules/@stdlib/assert/is-arraybuffer-view/lib/polyfill.js]:
```suggestion
*
```

**Review by kgryte — APPROVED** [review]
LGTM after clean-up.
