### PR TITLE
fix: resolve ESLint errors by replacing new Array()

### LINKED ISSUE #6032: Fix JavaScript lint errors
## JavaScript Linting Failures

Linting failures were detected in the automated JavaScript lint workflow run.

### Workflow Details

- Run: https://github.com/stdlib-js/stdlib/actions/runs/13846921716
- Type: JavaScript Linting
- Date: 2025-03-14 00:07:44 UTC

### Error Details
```
make[1]: Entering directory '/home/runner/work/stdlib/stdlib'

Linting file: lib/node_modules/@stdlib/ndarray/base/unary-accumulate/lib/7d_blocked_accessors.js

Linting file: lib/node_modules/@stdlib/plot/base/ctor/lib/props/x-num-ticks/set.js

Linting file: lib/node_modules/@stdlib/string/remove-punctuation/lib/main.js

Linting file: lib/node_modules/@stdlib/utils/map-arguments/lib/main.js

Linting file: lib/node_modules/@stdlib/blas/base/csrot/lib/main.js

Linting file: lib/node_modules/@stdlib/_tools/eslint/rules/jsdoc-code-block-style/lib/index.js

Linting file: lib/node_modules/@stdlib/math/base/special/minf/lib/native.js

Linting file: lib/node_modules/@stdlib/plot/sparklines/unicode/tristate/lib/index.js

Linting file: lib/node_modules/@stdlib/array/base/broadcasted-unary4d/lib/index.js

Linting file: lib/node_modules/@stdlib/assert/is-eval-error/lib/index.js

Linting file: lib/node_modules/@stdlib/stats/base/dists/logistic/variance/lib/main.js

Linting file: lib/node_modules/@stdlib/_tools/github/rank-followers/lib/pipeline.js

/home/runner/work/stdlib/stdlib/lib/node_modules/@stdlib/_tools/github/rank-followers/lib/pipeline.js
  43:8   error  Using the `new Array()` constructor is not allowed; use an array literal with push instead  stdlib/no-new-array
  81:15  error  Using the `new Array()` constructor is not allowed; use an array literal with push instead  stdlib/no-new-array

✖ 2 problems (2 errors, 0 warnings)

Linting failed.

Linting file: lib/node_modules/@stdlib/stats/base/sdsmeanors/lib/index.js

Linting file: lib/node_modules/@stdlib/math/iter/special/bessely0/lib/index.js

Linting file: lib/node_modules/@stdlib/stats/base/dists/rayleigh/entropy/lib/native.js

Linting file: lib/node_modules/@stdlib/complex/promotion-rules/lib/index.js

Linting file: lib/node_modules/@stdlib/array/base/every/lib/main.js

Linting file: lib/node_modules/@stdlib/slice/ctor/lib/index.js
make[1]: *** [/home/runner/work/stdlib/stdlib/tools/make/lib/lint/javascript/eslint.mk:255: eslint-files] Error 1
make[1]: Leaving directory '/home/runner/work/stdlib/stdlib'
make: *** [/home/runner/work/stdlib/stdlib/tools/make/lib/lint/javascript/Makefile:158: lint-javascript-files] Error 2
```

### PR DESCRIPTION
**Pull request by AlyAbdelmoneim**
Resolves #6032.

## Description

> What is the purpose of this pull request?

This pull request:

-   Addresses issue #6032 by implementing the necessary changes to improve the functionality of the feature, by using push instead of pre-allocating the memory.

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves #6032.

## Questions

> Any questions for reviewers of this pull request?

I encountered an issue when running the linting process due to an error related to EditorConfig. The error message indicated that the "path" argument was invalid, specifically that it was undefined. I would appreciate any guidance on how to resolve this or improve the configuration for linting.

## Other

> During the commit process, an error occurred in the linting task related to EditorConfig. The error traceback indicated that the "path" argument was expected to be a string but was undefined, causing the linting task to fail. I manually resolved this issue and ran the commit successfully after ensuring the configuration was correct. Any feedback on improving the linting process would be helpful.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

### CODE REVIEW

**Review by Planeshifter — CHANGES_REQUESTED** [review]
Notice the lint error message:

> Using the `new Array()` constructor is not allowed; use an array literal with push instead

We want to use `.push` instead of pre-allocating space for all the elements.

**Comment by AlyAbdelmoneim** [comment]
Also can you explain for me why using **.push** is better than pre-allocating ? I thought pre-allocating is better performance-wise.
Thank youu

File: lib/node_modules/@stdlib/_tools/github/rank-followers/lib/pipeline.js [hunk 1]
```diff
@@ -40,9 +40,10 @@ function toArray( obj ) {
 	var out;
 	var i;
 	keys = objectKeys( obj );
-	out = new Array( keys.length );
+	out = [];
+
```
Comment (kgryte) [inline lib/node_modules/@stdlib/_tools/github/rank-followers/lib/pipeline.js]:
```suggestion
```

File: lib/node_modules/@stdlib/_tools/github/rank-followers/lib/pipeline.js [hunk 2]
```diff
@@ -78,9 +79,10 @@ function pipeline( opts, clbk ) {
 		if ( error ) {
 			return done( error );
 		}
-		usernames = new Array( data.length );
+		usernames = [];
+
```
Comment (kgryte) [inline lib/node_modules/@stdlib/_tools/github/rank-followers/lib/pipeline.js]:
```suggestion
```

**Review by kgryte — APPROVED** [review]
LGTM

**Comment by kgryte** [comment]
@AlyAbdelmoneim Re: perf. Not with `Array`. The reason is that `new Array( N )` can put the returned value in dictionary mode which can significantly slow performance. Instead, it is advisable to use `.push` in order to ensure "fast" mode and contiguous elements.
