### PR TITLE
chore: fix JavaScript lint errors (issue #8559)

### LINKED ISSUE #8559: Fix JavaScript lint errors
## JavaScript Linting Failures

  Linting failures were detected in the automated JavaScript lint workflow run.

  ### Workflow Details

  - Run: https://github.com/stdlib-js/stdlib/actions/runs/19520430108
  - Type: JavaScript Linting
  - Date: 2025-11-20 00:12:55 UTC

  ### Error Details
  ```
  make[1]: Entering directory '/home/runner/work/stdlib/stdlib'

Linting file: lib/node_modules/@stdlib/ndarray/base/any-by/lib/9d_accessors.js

Linting file: lib/node_modules/@stdlib/math/array/special/lib/index.js

Linting file: lib/node_modules/@stdlib/_tools/lint/license-header-glob/lib/sync.js

/home/runner/work/stdlib/stdlib/lib/node_modules/@stdlib/_tools/lint/license-header-glob/lib/sync.js
  40:1  error  Displayed return value is `[...]`, but expected `[]` instead  stdlib/jsdoc-doctest

✖ 1 problem (1 error, 0 warnings)
  1 error and 0 warnings potentially fixable with the `--fix` option.

Linting failed.

Linting file: lib/node_modules/@stdlib/assert/has-iterator-symbol-support/lib/main.js

Linting file: lib/node_modules/@stdlib/ndarray/base/includes/lib/4d_blocked_accessors.js

Linting file: lib/node_modules/@stdlib/namespace/lib/namespace/j.js

Linting file: lib/node_modules/@stdlib/constants/time/minutes-in-week/lib/index.js

Linting file: lib/node_modules/@stdlib/utils/async/parallel/lib/validate.js

Linting file: lib/node_modules/@stdlib/ndarray/base/nullary/lib/2d_accessors.js

Linting file: lib/node_modules/@stdlib/blas/base/wasm/idamax/lib/main.js

Linting file: lib/node_modules/@stdlib/utils/dsv/base/parse/lib/states/init.js

Linting file: lib/node_modules/@stdlib/_tools/eslint/rules/jsdoc-ordered-list-marker-style/lib/main.js

/home/runner/work/stdlib/stdlib/lib/node_modules/@stdlib/_tools/eslint/rules/jsdoc-ordered-list-marker-style/lib/main.js
  127:2  error  Function 'copyLocationInfo' should be moved to module scope  stdlib/no-unnecessary-nested-functions

✖ 1 problem (1 error, 0 warnings)

Linting failed.

Linting file: lib/node_modules/@stdlib/_tools/remark/plugins/remark-img-equations/lib/main.js

Linting file: lib/node_modules/@stdlib/iter/shift/lib/index.js

Linting file: lib/node_modules/@stdlib/ndarray/base/assign/lib/0d_accessors.js

Linting file: lib/node_modules/@stdlib/blas/ext/base/zsumkbn/lib/ndarray.native.js

Linting file: lib/node_modules/@stdlib/math/strided/special/cbrt-by/lib/index.js

Linting file: lib/node_modules/@stdlib/stats/base/dists/frechet/median/lib/native.js

Linting file: lib/node_modules/@stdlib/stats/strided/sstdevyc/lib/index.js

Linting file: lib/node_modules/@stdlib/blas/ext/sorthp/lib/base.js
make[1]: *** [/home/runner/work/stdlib/stdlib/tools/make/lib/lint/javascript/eslint.mk:261: eslint-files] Error 1
make[1]: Leaving directory '/home/runner/work/stdlib/stdlib'
make: *** [/home/runner/work/stdlib/stdlib/tools/make/lib/lint/javascript/Makefile:158: lint-javascript-files] Error 2
make[1]: Entering directory '/home/runner/work/stdlib/stdlib'

Linting file: lib/node_modules/@stdlib/blas/ext/base/slinspace/examples/index.js

Linting file: lib/node_modules/@stdlib/ndarray/base/buffer-dtype/examples/index.js

Linting file: lib/node_modules/@stdlib/stats/incr/mmda/examples/index.js

Linting file: lib/node_modules/@stdlib/assert/is-equal-int8array/examples/index.js

Linting file: lib/node_modules/@stdlib/stats/strided/dnanvariance/examples/index.js

Linting file: lib/node_modules/@stdlib/math/base/assert/is-safe-integer/examples/index.js

Linting file: lib/node_modules/@stdlib/ndarray/base/dtype-alignment/examples/index.js
float64 => 8
float32 => 4
int8 => 1
uint8 => 1
uint8c => 1
int16 => 2
uint16 => 2
int32 => 4
uint32 => 4
binary => 1
generic => null
foobar => null

Linting file: lib/node_modules/@stdlib/os/platform/examples/index.js

Linting file: lib/node_modules/@stdlib/assert/is-enumerable-property/examples/index.js

/home/runner/work/stdlib/stdlib/lib/node_modules/@stdlib/assert/is-enumerable-property/examples/index.js
  25:12  error  No spaces allowed between an opening parenthesis or bracket and a nested object or array expression at the end of a line  stdlib/eol-open-bracket-spacing
  53:8   error  No spaces allowed between an opening parenthesis or bracket and a nested object or array expression at the end of a line  stdlib/eol-open-bracket-spacing
  57:8   error  No spaces allowed between an opening parenthesis or bracket and a nested object or array expression at the end of a line  stdlib/eol-open-bracket-spacing

✖ 3 problems (3 errors, 0 warnings)
  3 errors and 0 warnings potentially fixable with the `--fix` option.

Linting failed.

Linting file: lib/node_modules/@stdlib/stats/base/dists/logistic/entropy/examples/index.js
µ: 2.5507, s: 9.8913, h(X;µ,s): 4.2917
µ: -3.4550, s: 1.0327, h(X;µ,s): 2.0322
µ: 4.6803, s: 2.4982, h(X;µ,s): 2.9156
µ: 1.6140, s: 11.7428, h(X;µ,s): 4.4632
µ: 4.0299, s: 6.4167, h(X;µ,s): 3.8589
µ: 2.4653, s: 0.3619, h(X;µ,s): 0.9835
µ: -3.8738, s: 11.9571, h(X;µ,s): 4.4813
µ: 0.1313, s: 18.2864, h(X;µ,s): 4.9062
µ: 1.2913, s: 12.5023, h(X;µ,s): 4.5259
µ: -3.4176, s: 6.6217, h(X;µ,s): 3.8904

Linting file: lib/node_modules/@stdlib/stats/strided/dmeanli/examples/index.js
make[1]: *** [/home/runner/work/stdlib/stdlib/tools/make/lib/lint/javascript/eslint.mk:261: eslint-files] Error 1
make[1]: Leaving directory '/home/runner/work/stdlib/stdlib'
make: *** [/home/runner/work/stdlib/stdlib/tools/make/lib/lint/javascript/Makefile:158: lint-javascript-files] Error 2
  ```

  ### Pull Request Instructions

  -   Please use the following PR title format:
  "chore: fix JavaScript lint errors (issue #<ISSUE_NUMBER>)".
  -   Reference this issue in the "Related Issues" section of the PR body as "resolves #<ISSUE_NUMBER>".

### PR DESCRIPTION
**Pull request by kaushal-kumar-it**
---
type: pre_commit_static_analysis_report
description: Results of running static analysis checks when committing changes. report:
  - task: lint_filenames status: passed
  - task: lint_editorconfig status: passed
  - task: lint_markdown status: na
  - task: lint_package_json status: na
  - task: lint_repl_help status: na
  - task: lint_javascript_src status: passed
  - task: lint_javascript_cli status: na
  - task: lint_javascript_examples status: passed
  - task: lint_javascript_tests status: na
  - task: lint_javascript_benchmarks status: na
  - task: lint_python status: na
  - task: lint_r status: na
  - task: lint_c_src status: na
  - task: lint_c_examples status: na
  - task: lint_c_benchmarks status: na
  - task: lint_c_tests_fixtures status: na
  - task: lint_shell status: na
  - task: lint_typescript_declarations status: passed
  - task: lint_typescript_tests status: na
  - task: lint_license_headers status: passed
---

Resolves #8559.

## Description

> What is the purpose of this pull request?

This pull request:

- Fixes JavaScript linting errors detected by stdlib-bot.
- Corrected `license-header-glob/lib/sync.js` return value formatting.
- Moved `copyLocationInfo` function to module scope in `jsdoc-ordered-list-marker-style/lib/main.js`.
- Fixed spacing in `is-enumerable-property/examples/index.js` to comply with eslint rules.

## Related Issues

> Does this pull request have any related issues?

This pull request has the following related issues:

- #8559

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [X] Read, understood, and followed the [contributing guidelines][contributing].

### AI Assistance

> When authoring the changes proposed in this PR, did you use any kind of AI assistance?

-   [ ] Yes
-   [X] No

If you answered "yes" above, how did you use AI assistance?

-   [ ] Code generation (e.g., when writing an implementation or fixing a bug)
-   [ ] Test/benchmark generation
-   [ ] Documentation (including examples)
-   [ ] Research and understanding

#### Disclosure

> If you answered "yes" to using AI assistance, please provide a short disclosure indicating how you used AI assistance. This helps reviewers determine how much scrutiny to apply when reviewing your contribution. Example disclosures: "This PR was written primarily by Claude Code." or "I consulted ChatGPT to understand the codebase, but the proposed changes were fully authored manually by myself.".

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

### CODE REVIEW

File: lib/node_modules/@stdlib/_tools/lint/license-header-glob/lib/sync.js [hunk 1]
```diff
@@ -56,7 +56,7 @@ var debug = logger( 'lint:license-header-glob:sync' );
 * };
 *
 * var errs = lint( opts );
-* // returns [...]
+* // returns []
```
Comment (kgryte) [inline lib/node_modules/@stdlib/_tools/lint/license-header-glob/lib/sync.js]:
```suggestion
* // e.g., returns [...]
```

**Review by kgryte — DISMISSED** [review]
LGTM after some minor clean-up.

**Review by kgryte — APPROVED** [review]
