### PR TITLE
chore: fix JavaScript lint errors (issue #11750)

### LINKED ISSUE #11750: Fix JavaScript lint errors
## JavaScript Linting Failures

  Linting failures were detected in the automated JavaScript lint workflow run.

  ### Workflow Details

  - Run: https://github.com/stdlib-js/stdlib/actions/runs/24865396338
  - Type: JavaScript Linting
  - Date: 2026-04-24 00:24:14 UTC

  ### Error Details
  ```
  make[1]: Entering directory '/home/runner/work/stdlib/stdlib'

Linting file: lib/node_modules/@stdlib/stats/base/dists/pareto-type1/logcdf/test/test.native.js

Linting file: lib/node_modules/@stdlib/string/num2words/test/test.validate.js

Linting file: lib/node_modules/@stdlib/number/float16/base/assert/is-negative-zero/test/test.js

Linting file: lib/node_modules/@stdlib/math/base/special/minmaxabsf/test/test.native.js

Linting file: lib/node_modules/@stdlib/array/base/cuany-by-right/test/test.main.js

Linting file: lib/node_modules/@stdlib/_tools/static-analysis/js/sloc-glob/test/test.sync.js

Linting file: lib/node_modules/@stdlib/stats/base/ndarray/dstdev/test/test.js

Linting file: lib/node_modules/@stdlib/blas/ext/base/ndarray/ssorthp/test/test.js

Linting file: lib/node_modules/@stdlib/datasets/pace-boston-house-prices/test/test.cli.js

Linting file: lib/node_modules/@stdlib/stats/kstest/test/test.marsaglia.js

/home/runner/work/stdlib/stdlib/lib/node_modules/@stdlib/stats/kstest/test/test.marsaglia.js
  46:65  error  Unused eslint-disable directive (no problems were reported from 'array-element-newline')
  47:70  error  Unused eslint-disable directive (no problems were reported from 'array-element-newline')
  49:13  error  There should be a linebreak after this element                                            array-element-newline
  49:18  error  There should be a linebreak after this element                                            array-element-newline
  49:23  error  There should be a linebreak after this element                                            array-element-newline
  49:34  error  There should be a linebreak after this element                                            array-element-newline
  50:13  error  There should be a linebreak after this element                                            array-element-newline
  50:24  error  There should be a linebreak after this element                                            array-element-newline
  50:35  error  There should be a linebreak after this element                                            array-element-newline
  50:40  error  There should be a linebreak after this element                                            array-element-newline

✖ 10 problems (10 errors, 0 warnings)
  10 errors and 0 warnings potentially fixable with the `--fix` option.

Linting failed.

Linting file: lib/node_modules/@stdlib/math/base/special/fast/absf/test/test.js

Linting file: lib/node_modules/@stdlib/simulate/iter/dirac-comb/test/test.validate.js

Linting file: lib/node_modules/@stdlib/blas/base/zdrot/test/test.js

Linting file: lib/node_modules/@stdlib/assert/is-wasm-memory/test/test.js

Linting file: lib/node_modules/@stdlib/random/frechet/test/test.js

Linting file: lib/node_modules/@stdlib/math/strided/special/dsqrt/test/test.js

Linting file: lib/node_modules/@stdlib/simulate/iter/awun/test/test.js

Linting file: lib/node_modules/@stdlib/ndarray/base/assign-scalar/test/test.2d.js
make[1]: *** [/home/runner/work/stdlib/stdlib/tools/make/lib/lint/javascript/eslint.mk:261: eslint-files] Error 1
make[1]: Leaving directory '/home/runner/work/stdlib/stdlib'
make: *** [/home/runner/work/stdlib/stdlib/tools/make/lib/lint/javascript/Makefile:158: lint-javascript-files] Error 2
  ```

  ### Pull Request Instructions

  -   Please use the following PR title format:
  "chore: fix JavaScript lint errors (issue #<ISSUE_NUMBER>)".
  -   Reference this issue in the "Related Issues" section of the PR body as "resolves #<ISSUE_NUMBER>".

### PR DESCRIPTION
**Pull request by vedparkasharya**
## Description

This PR fixes JavaScript linting errors reported in #11750 in the `test.marsaglia.js` file.

## Problem

The automated lint workflow detected the following errors in `lib/node_modules/@stdlib/stats/kstest/test/test.marsaglia.js`:

```
  46:65  error  Unused eslint-disable directive (no problems were reported from 'array-element-newline')
  47:70  error  Unused eslint-disable directive (no problems were reported from 'array-element-newline')
  49:13  error  There should be a linebreak after this element                                            array-element-newline
  49:18  error  There should be a linebreak after this element                                            array-element-newline
  ...
```

### Changes Made

1. **Removed unused `eslint-disable-line` directives** from the `d` and `n` array declarations (lines 46–47). These directives were no longer needed and triggered `unused-eslint-disable` errors.

2. **Reformatted the `expected` array** so each element is on its own line, satisfying the `array-element-newline` ESLint rule.

**Before:**
```javascript
d = [ 0.3, -0.1, 1.5, 0.5, 0.1, 0.1, 0.05, 0.05, 0.8, 0.274 ]; // eslint-disable-line array-element-newline
n = [ 10.0, 10.0, 10.0, 20.0, 10.0, 20.0, 300.0, 80.0, 1.0, 10.0 ]; // eslint-disable-line array-element-newline
expected = [
	0.7294644, 0.0, 1.0, 0.9999621, 0.0003629,
	0.0237449, 0.5725584, 0.0175789, 0.6, 0.6284796
];
```

**After:**
```javascript
d = [ 0.3, -0.1, 1.5, 0.5, 0.1, 0.1, 0.05, 0.05, 0.8, 0.274 ];
n = [ 10.0, 10.0, 10.0, 20.0, 10.0, 20.0, 300.0, 80.0, 1.0, 10.0 ];
expected = [
	0.7294644,
	0.0,
	1.0,
	0.9999621,
	0.0003629,
	0.0237449,
	0.5725584,
	0.0175789,
	0.6,
	0.6284796
];
```

### Why this solution is correct

- The `d` and `n` arrays are concise single-line declarations that do not violate the project's `array-element-newline` configuration, making the disable comments redundant.
- The `expected` array spans multiple lines, so the `array-element-newline` rule requires each element to be on its own line for consistency and readability.
- No test logic or values were changed; only formatting was updated.

## Related Issues

resolves #11750

## Checklist

- [x] Read, understood, and followed the [contributing guidelines](https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md)

### CODE REVIEW

File: lib/node_modules/@stdlib/stats/kstest/test/test.marsaglia.js [hunk 1]
```diff
@@ -43,11 +43,19 @@ tape( 'the function correctly evaluates the CDF of D_n', function test( t ) {
...
+	n = [ 10.0, 10.0, 10.0, 20.0, 10.0, 20.0, 300.0, 80.0, 1.0, 10.0 ];
 	expected = [
-		0.7294644, 0.0, 1.0, 0.9999621, 0.0003629,
-		0.0237449, 0.5725584, 0.0175789, 0.6, 0.6284796
+		0.7294644,
+		0.0,
+		1.0,
+		0.9999621,
+		0.0003629,
+		0.0237449,
```
Comment (kgryte) [inline lib/node_modules/@stdlib/stats/kstest/test/test.marsaglia.js:55]:
```suggestion

		0.0237449,
```

**Review by kgryte — APPROVED** [review]
