### PR TITLE
chore: fix JavaScript lint errors (issue #10246)

### LINKED ISSUE #10246: Fix JavaScript lint errors
## JavaScript Linting Failures

  Linting failures were detected in the automated JavaScript lint workflow run.

  ### Workflow Details

  - Run: https://github.com/stdlib-js/stdlib/actions/runs/21969217388
  - Type: JavaScript Linting
  - Date: 2026-02-13 00:17:31 UTC

  ### Error Details
  ```
  make[1]: Entering directory '/home/runner/work/stdlib/stdlib'

Linting file: lib/node_modules/@stdlib/number/uint8/base/from-binary-string/examples/index.js

Linting file: lib/node_modules/@stdlib/assert/has-class-support/examples/index.js

Linting file: lib/node_modules/@stdlib/time/seconds-in-year/examples/index.js

Linting file: lib/node_modules/@stdlib/math/base/special/expit/examples/index.js
expit(0.7343) = 0.6757
expit(0.7725) = 0.6841
expit(0.9207) = 0.7152
expit(0.1746) = 0.5435
expit(0.0537) = 0.5134
expit(0.9247) = 0.7160
expit(0.1725) = 0.5430
expit(0.5383) = 0.6314
expit(0.2680) = 0.5666
expit(0.1541) = 0.5384
expit(0.2291) = 0.5570
expit(0.7832) = 0.6864
expit(0.2529) = 0.5629
expit(0.9935) = 0.7298
expit(0.9688) = 0.7249
expit(0.6783) = 0.6634
expit(0.1290) = 0.5322
expit(0.3049) = 0.5756
expit(0.3679) = 0.5910
expit(0.8094) = 0.6920
expit(0.2353) = 0.5586
expit(0.8016) = 0.6903
expit(0.9012) = 0.7112
expit(0.1533) = 0.5382
expit(0.0008) = 0.5002
expit(0.4226) = 0.6041
expit(0.1811) = 0.5452
expit(0.3778) = 0.5933
expit(0.2749) = 0.5683
expit(0.6853) = 0.6649
expit(0.0633) = 0.5158
expit(0.1959) = 0.5488
expit(0.8022) = 0.6904
expit(0.5879) = 0.6429
expit(0.7672) = 0.6829
expit(0.2655) = 0.5660
expit(0.0843) = 0.5211
expit(0.5372) = 0.6312
expit(0.1021) = 0.5255
expit(0.9746) = 0.7260
expit(0.0769) = 0.5192
expit(0.8101) = 0.6921
expit(0.2971) = 0.5737
expit(0.3641) = 0.5900
expit(0.1437) = 0.5359
expit(0.5698) = 0.6387
expit(0.0360) = 0.5090
expit(0.3302) = 0.5818
expit(0.4066) = 0.6003
expit(0.8254) = 0.6954
expit(0.0433) = 0.5108
expit(0.5429) = 0.6325
expit(0.8883) = 0.7085
expit(0.4109) = 0.6013
expit(0.8056) = 0.6912
expit(0.1735) = 0.5433
expit(0.9491) = 0.7209
expit(0.8527) = 0.7011
expit(0.9362) = 0.7183
expit(0.4250) = 0.6047
expit(0.0424) = 0.5106
expit(0.6569) = 0.6586
expit(0.8123) = 0.6926
expit(0.8921) = 0.7093
expit(0.0357) = 0.5089
expit(0.4510) = 0.6109
expit(0.6217) = 0.6506
expit(0.2138) = 0.5532
expit(0.8697) = 0.7047
expit(0.0127) = 0.5032
expit(0.9513) = 0.7214
expit(0.8521) = 0.7010
expit(0.3006) = 0.5746
expit(0.5358) = 0.6308
expit(0.8517) = 0.7009
expit(0.3133) = 0.5777
expit(0.1411) = 0.5352
expit(0.1183) = 0.5295
expit(0.5364) = 0.6310
expit(0.2083) = 0.5519
expit(0.2990) = 0.5742
expit(0.2156) = 0.5537
expit(0.0587) = 0.5147
expit(0.9761) = 0.7263
expit(0.1262) = 0.5315
expit(0.9317) = 0.7174
expit(0.0561) = 0.5140
expit(0.9824) = 0.7276
expit(0.5281) = 0.6290
expit(0.7953) = 0.6890
expit(0.0420) = 0.5105
expit(0.9708) = 0.7253
expit(0.4280) = 0.6054
expit(0.4411) = 0.6085
expit(0.6213) = 0.6505
expit(0.6431) = 0.6555
expit(0.0055) = 0.5014
expit(0.7414) = 0.6773
expit(0.6598) = 0.6592
expit(0.7487) = 0.6789

Linting file: lib/node_modules/@stdlib/assert/is-bigint64array/examples/index.js

/home/runner/work/stdlib/stdlib/lib/node_modules/@stdlib/assert/is-bigint64array/examples/index.js
  77:25  error  Using the `new Array()` constructor is not allowed; use an array literal with push instead  stdlib/no-new-array

✖ 1 problem (1 error, 0 warnings)

Linting failed.

Linting file: lib/node_modules/@stdlib/assert/is-complex128vector-like/examples/index.js

Linting file: lib/node_modules/@stdlib/constants/float32/max-base2-exponent-subnormal/examples/index.js

Linting file: lib/node_modules/@stdlib/blas/ext/base/ndarray/ssorthp/examples/index.js
make[1]: *** [/home/runner/work/stdlib/stdlib/tools/make/lib/lint/javascript/eslint.mk:261: eslint-files] Error 1
make[1]: Leaving directory '/home/runner/work/stdlib/stdlib'
make: *** [/home/runner/work/stdlib/stdlib/tools/make/lib/lint/javascript/Makefile:158: lint-javascript-files] Error 2
make[1]: Entering directory '/home/runner/work/stdlib/stdlib'

Linting file: lib/node_modules/@stdlib/random/streams/logistic/test/test.validate.js

Linting file: lib/node_modules/@stdlib/ndarray/concat1d/test/test.js

Linting file: lib/node_modules/@stdlib/constants/int32/num-bytes/test/test.js

Linting file: lib/node_modules/@stdlib/stats/base/dists/invgamma/variance/test/test.js

Linting file: lib/node_modules/@stdlib/_tools/github/get/test/test.lastpage.js

Linting file: lib/node_modules/@stdlib/stats/base/dists/degenerate/mgf/test/test.js

Linting file: lib/node_modules/@stdlib/stats/strided/sminabs/test/test.sminabs.native.js

Linting file: lib/node_modules/@stdlib/math/base/tools/normhermitepolyf/test/test.factory.js

/home/runner/work/stdlib/stdlib/lib/node_modules/@stdlib/math/base/tools/normhermitepolyf/test/test.factory.js
  34:1  error  Unexpected empty line between require statements  stdlib/no-empty-lines-between-requires
  38:1  error  Unexpected empty line between require statements  stdlib/no-empty-lines-between-requires
  42:1  error  Unexpected empty line between require statements  stdlib/no-empty-lines-between-requires
  46:1  error  Unexpected empty line between require statements  stdlib/no-empty-lines-between-requires
  50:1  error  Unexpected empty line between require statements  stdlib/no-empty-lines-between-requires

✖ 5 problems (5 errors, 0 warnings)
  5 errors and 0 warnings potentially fixable with the `--fix` option.

Linting failed.

Linting file: lib/node_modules/@stdlib/random/streams/chisquare/test/test.js

Linting file: lib/node_modules/@stdlib/number/float64/base/add5/test/test.js

Linting file: lib/node_modules/@stdlib/array/cartesian-product/test/test.js

Linting file: lib/node_modules/@stdlib/constants/int32/test/test.js

Linting file: lib/node_modules/@stdlib/lapack/base/dlassq/test/test.dlassq.js
make[1]: *** [/home/runner/work/stdlib/stdlib/tools/make/lib/lint/javascript/eslint.mk:261: eslint-files] Error 1
make[1]: Leaving directory '/home/runner/work/stdlib/stdlib'
make: *** [/home/runner/work/stdlib/stdlib/tools/make/lib/lint/javascript/Makefile:158: lint-javascript-files] Error 2
  ```

  ### Pull Request Instructions

  -   Please use the following PR title format:
  "chore: fix JavaScript lint errors (issue #<ISSUE_NUMBER>)".
  -   Reference this issue in the "Related Issues" section of the PR body as "resolves #<ISSUE_NUMBER>".

### PR DESCRIPTION
**Pull request by bhargava-d16**
Resolves #10246 

## Description

> What is the purpose of this pull request?

This pull request:

-   Fixes JavaScript lint errors by replacing disallowed new Array() usages

## Related Issues

> Does this pull request have any related issues?

This pull request has the following related issues:

-   #10246 

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

### AI Assistance

> When authoring the changes proposed in this PR, did you use any kind of AI assistance?

-   [ ] Yes
-   [x] No

If you answered "yes" above, how did you use AI assistance?

-   [ ] Code generation (e.g., when writing an implementation or fixing a bug)
-   [ ] Test/benchmark generation
-   [ ] Documentation (including examples)
-   [ ] Research and understanding

#### Disclosure

> If you answered "yes" to using AI assistance, please provide a short disclosure indicating how you used AI assistance. This helps reviewers determine how much scrutiny to apply when reviewing your contribution. Example disclosures: "This PR was written primarily by Claude Code." or "I consulted ChatGPT to understand the codebase, but the proposed changes were fully authored manually by myself.".

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

### CODE REVIEW

File: lib/node_modules/@stdlib/assert/is-bigint64array/examples/index.js [hunk 1]
```diff
@@ -74,7 +74,7 @@ bool = isBigInt64Array( new Float32Array( 10 ) );
 console.error( bool );
 // => false
 
-bool = isBigInt64Array( new Array( 10 ) );
+bool = isBigInt64Array( [] );
```
Comment (Planeshifter) [inline lib/node_modules/@stdlib/assert/is-bigint64array/examples/index.js:77]: The fix here changes the semantics - `new Array( 10 )` creates a sparse array of length 10, while `[]` creates an empty array of length 0. But that's probably okay.

However, the README.md still shows `new Array( 10 )` on line 101, so the examples file and docs are now out of sync. Please update the corresponding line in the README.

File: lib/node_modules/@stdlib/stats/base/snanvariancetk/benchmark/benchmark.js [hunk 2]
```diff
@@ -25,6 +25,7 @@ var randu = require( '@stdlib/random/base/randu' );
 var isnanf = require( '@stdlib/math/base/assert/is-nanf' );
 var pow = require( '@stdlib/math/base/special/pow' );
 var Float32Array = require( '@stdlib/array/float32' );
+var format = require( '@stdlib/string/format' );
```
Comment (Planeshifter) [inline lib/node_modules/@stdlib/stats/base/snanvariancetk/benchmark/benchmark.js]: The benchmark changes in this PR are unrelated to the lint errors reported in issue #10246 (which only covers `stdlib/no-new-array` in `is-bigint64array` and `stdlib/no-empty-lines-between-requires` in `normhermitepolyf`). These `snanvariancetk` benchmark changes should go in a separate PR with their own commit message, since they're already in a separate commit (`bench: refactor to use string interpolation in stats/base/snanvariancetk`) and address a different concern.

**Review by Planeshifter — CHANGES_REQUESTED** [review]

**Review by Planeshifter — APPROVED** [review]
