### PR TITLE
chore: fix C lint errors (issue #11334)

### LINKED ISSUE #11334: Fix C lint errors
## C Linting Failures

Linting failures were detected in the automated lint workflow run.

### Workflow Details

-   Run: https://github.com/stdlib-js/stdlib/actions/runs/24165216740
-   Type: C Linting
-   Date: 2026-04-09 00:21:12 UTC

### Error Details

```
lib/node_modules/@stdlib/ndarray/base/iteration-order/src/main.c:46:64: style: Parameter 'strides' can be declared as pointer to const [constParameterPointer]
int8_t stdlib_ndarray_iteration_order( int64_t ndims, int64_t *strides ) {
                                                               ^
```

### Pull Request Instructions

-   Please use the following PR title format:
"chore: fix C lint errors (issue #<ISSUE_NUMBER>)".
-   Reference this issue in the "Related Issues" section of the PR body as "resolves #<ISSUE_NUMBER>".

### PR DESCRIPTION
**Pull request by GeoDaoyu**
Resolves #11334.

## Description

> What is the purpose of this pull request?

This pull request:

-   fix C lint errors

## Related Issues

> Does this pull request have any related issues?

This pull request has the following related issues:

-   #11334

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

### AI Assistance

> When authoring the changes proposed in this PR, did you use any kind of AI assistance?

-   [ ] Yes
-   [x] No

If you answered "yes" above, how did you use AI assistance?

-   [ ] Code generation (e.g., when writing an implementation or fixing a bug)
-   [ ] Test/benchmark generation
-   [ ] Documentation (including examples)
-   [ ] Research and understanding

#### Disclosure

> If you answered "yes" to using AI assistance, please provide a short disclosure indicating how you used AI assistance. This helps reviewers determine how much scrutiny to apply when reviewing your contribution. Example disclosures: "This PR was written primarily by Claude Code." or "I consulted ChatGPT to understand the codebase, but the proposed changes were fully authored manually by myself.".

{{TODO: add disclosure if applicable}}

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

### CODE REVIEW

File: lib/node_modules/@stdlib/ndarray/base/iteration-order/src/main.c [hunk 1]
```diff
@@ -43,7 +43,7 @@
 * int8_t o = stdlib_ndarray_iteration_order( ndims, strides );
 * // returns 1
 */
-int8_t stdlib_ndarray_iteration_order( int64_t ndims, int64_t *strides ) {
+int8_t stdlib_ndarray_iteration_order( int64_t ndims, const int64_t *strides ) {
```
Comment (kgryte) [inline lib/node_modules/@stdlib/ndarray/base/iteration-order/src/main.c]:
```suggestion
int8_t stdlib_ndarray_iteration_order( const int64_t ndims, const int64_t *strides ) {
```

**Review by kgryte — CHANGES_REQUESTED** [review]
This looks good. @GeoDaoyu Mind making the same changes to the header file and, if documented in the README, to the README? Cheers!

**Review by kgryte — APPROVED** [review]

**Comment by GeoDaoyu** [comment]
Hi, I have modified the header file, and I checked the README(lib/node_modules/@stdlib/ndarray/base/iteration-order/README.md) and found that the README does not need to be modified.

**Comment by kgryte** [comment]
@GeoDaoyu Thank you!
