### PR TITLE
chore: fix C lint errors

### LINKED ISSUE #5347: Fix C lint errors
## C Linting Failures

Linting failures were detected in the automated lint workflow run.

### Workflow Details

-   Run: https://github.com/stdlib-js/stdlib/actions/runs/13447021386
-   Type: C Linting
-   Date: 2025-02-21 00:15:28 UTC

### Error Details

```

lib/node_modules/@stdlib/number/float64/base/normalize/examples/c/example.c:0:0: error: Internal Error. MathLib::toDoubleNumber: conversion failed: 3.14e308 [internalError]

^
```

### PR DESCRIPTION
**Pull request by gkbishnoi07**
Resolves #5347  

## Description

> What is the purpose of this pull request?

This pull request:

-   fixing C lint error 

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves #5347 

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

- [x] Read, understood, and followed the [contributing guidelines](https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md)  

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

### CODE REVIEW

**Comment by gkbishnoi07** [comment]
@Planeshifter @kgryte please review this PRs

File: lib/node_modules/@stdlib/number/float64/base/normalize/examples/c/example.c [hunk 1]
```diff
@@ -22,12 +22,12 @@
 #include <inttypes.h>
 
 int main( void ) {
-	double x[] = { 1.0, 3.14, 0.0, -0.0, 3.14e-308, 3.14e308, 1.0/0.0, 0.0/0.0 };
+	const double x[] = { 3.14, -3.14, 0.0, 0.0/0.0 };;
```
Comment (kgryte) [inline lib/node_modules/@stdlib/number/float64/base/normalize/examples/c/example.c]:
```suggestion
	const double x[] = { 1.0, 3.14, 0.0, -0.0, 3.14e-308, 1.79e308, 1.0/0.0, 0.0/0.0 };;
```

File: lib/node_modules/@stdlib/number/float64/base/normalize/examples/c/example.c [hunk 2]
```diff
@@ -22,12 +22,12 @@
...
 	int32_t exp;
 	double y;
 	int i;
 
-	for ( i = 0; i < 8; i++ ) {
+	for ( i = 0; i < 4; i++ ) {
```
Comment (kgryte) [inline lib/node_modules/@stdlib/number/float64/base/normalize/examples/c/example.c]:
```suggestion
	for ( i = 0; i < 8; i++ ) {
```

File: lib/node_modules/@stdlib/number/float64/base/normalize/examples/c/example.c (hunk 1 above)
Comment (kgryte) [reply lib/node_modules/@stdlib/number/float64/base/normalize/examples/c/example.c]: You need to recognize why the value `3.14e308` was problematic. Namely, because it exceeds the max finite double.

Comment (gkbishnoi07) [reply lib/node_modules/@stdlib/number/float64/base/normalize/examples/c/example.c]: I apologize; I modified this file similarly to other C examples.

**Comment by gkbishnoi07** [comment]
@kgryte will i remove this 3.14e308 to resolve this issue or search for other methods

**Comment by kgryte** [comment]
@gkbishnoi07 Please don't marked conversations as resolved, if they are not resolved. I provided the two suggestions for you to apply to this PR. You should incorporate my suggested changes.

**Comment by gkbishnoi07** [comment]
> @gkbishnoi07 Please don't marked conversations as resolved, if they are not resolved. I provided the two suggestions for you to apply to this PR. You should incorporate my suggested changes.

@kgryte Understood! I'll make the suggested changes and update the PR accordingly. Thanks for your feedback!

**Comment by gkbishnoi07** [comment]
@kgryte all issue resolved please review this PRs

**Review by kgryte — APPROVED** [review]
LGTM
